// AUTO-GENERATED by pnpm make:type. Do not edit.

import type { CliOption } from '~/code/tool/shared/console'

export const options: CliOption[] = [
  {
    "path": [
      "input",
      "file",
      "path"
    ],
    "long": "input-file-path",
    "short": "i",
    "like": "string",
    "list": false,
    "need": true
  },
  {
    "path": [
      "output",
      "file",
      "path"
    ],
    "long": "output-file-path",
    "short": "o",
    "like": "string",
    "list": false,
    "need": true
  },
  {
    "path": [
      "crf"
    ],
    "long": "crf",
    "like": "string",
    "list": false,
    "need": false,
    "note": "H.264 CRF, 0 (lossless) to 51 (worst). Default 28."
  },
  {
    "path": [
      "preset"
    ],
    "long": "preset",
    "like": "string",
    "list": false,
    "need": false,
    "note": "x264 preset (ultrafast to veryslow). Default medium."
  }
]
