// AUTO-GENERATED by pnpm make:type. Do not edit.

import type { CliOption } from '~/code/tool/shared/console'

export const options: CliOption[] = [
  {
    "path": [
      "input",
      "format"
    ],
    "long": "input-format",
    "short": "I",
    "like": "audio_pad_format",
    "list": false,
    "need": false
  },
  {
    "path": [
      "input",
      "file",
      "path"
    ],
    "long": "input-file-path",
    "short": "i",
    "like": "string",
    "list": false,
    "need": true
  },
  {
    "path": [
      "output",
      "format"
    ],
    "long": "output-format",
    "short": "O",
    "like": "audio_pad_format",
    "list": false,
    "need": false
  },
  {
    "path": [
      "output",
      "file",
      "path"
    ],
    "long": "output-file-path",
    "short": "o",
    "like": "string",
    "list": false,
    "need": true
  },
  {
    "path": [
      "to"
    ],
    "long": "to",
    "like": "string",
    "list": false,
    "need": true,
    "note": "Target duration (MM:SS.mmm or seconds)"
  },
  {
    "path": [
      "sampleRate"
    ],
    "long": "sample-rate",
    "like": "natural_number",
    "list": false,
    "need": false
  },
  {
    "path": [
      "channels"
    ],
    "long": "channels",
    "like": "natural_number",
    "list": false,
    "need": false
  }
]
