// AUTO-GENERATED by pnpm make:type. Do not edit.

import type { CliOption } from '~/code/tool/shared/console'

export const options: CliOption[] = [
  {
    "path": [
      "input",
      "file",
      "path"
    ],
    "long": "input-file-path",
    "short": "i",
    "like": "string",
    "list": false,
    "need": true
  },
  {
    "path": [
      "output",
      "file",
      "path"
    ],
    "long": "output-file-path",
    "short": "o",
    "like": "string",
    "list": false,
    "need": true
  },
  {
    "path": [
      "profile"
    ],
    "long": "profile",
    "like": "string",
    "list": false,
    "need": false,
    "note": "Path to a .pp3 profile"
  },
  {
    "path": [
      "jpegQuality"
    ],
    "long": "jpeg-quality",
    "like": "natural_number",
    "list": false,
    "need": false,
    "note": "JPEG quality 1-100"
  },
  {
    "path": [
      "tiffCompression"
    ],
    "long": "tiff-compression",
    "like": "string",
    "list": false,
    "need": false,
    "note": "TIFF compression: none, lzw, or zip"
  }
]
