// AUTO-GENERATED by pnpm make:type. Do not edit.

import type { CliOption } from '~/code/tool/shared/console'

export const options: CliOption[] = [
  {
    "path": [
      "repo"
    ],
    "long": "repo",
    "like": "string",
    "list": false,
    "need": true
  },
  {
    "path": [
      "repoType"
    ],
    "long": "repo-type",
    "like": "hugging_face_repo_type",
    "list": false,
    "need": false
  },
  {
    "path": [
      "directory",
      "path"
    ],
    "long": "directory-path",
    "like": "string",
    "list": false,
    "need": true
  },
  {
    "path": [
      "include"
    ],
    "long": "include",
    "like": "string",
    "list": true,
    "need": false
  },
  {
    "path": [
      "exclude"
    ],
    "long": "exclude",
    "like": "string",
    "list": true,
    "need": false
  },
  {
    "path": [
      "revision"
    ],
    "long": "revision",
    "like": "string",
    "list": false,
    "need": false
  },
  {
    "path": [
      "help"
    ],
    "long": "help",
    "like": "boolean",
    "list": false,
    "need": false
  }
]
