// AUTO-GENERATED by pnpm make:type. Do not edit.

import type { CliOption } from '~/code/tool/shared/console'

export const options: CliOption[] = [
  {
    "path": [
      "input",
      "format"
    ],
    "long": "input-format",
    "like": "wast_input_format",
    "list": false,
    "need": true
  },
  {
    "path": [
      "input",
      "file",
      "path"
    ],
    "long": "input-file-path",
    "like": "string",
    "list": false,
    "need": true
  },
  {
    "path": [
      "output",
      "format"
    ],
    "long": "output-format",
    "like": "wast_output_format",
    "list": false,
    "need": true
  },
  {
    "path": [
      "output",
      "file",
      "path"
    ],
    "long": "output-file-path",
    "like": "string",
    "list": false,
    "need": true
  },
  {
    "path": [
      "pathScope"
    ],
    "long": "path-scope",
    "like": "string",
    "list": false,
    "need": false,
    "note": "This is used from the UI to scope file paths to a specific folder."
  }
]
