// AUTO-GENERATED by pnpm make:type. Do not edit.

import type { CliOption } from '~/code/tool/shared/console'

export const options: CliOption[] = [
  {
    "path": [
      "key"
    ],
    "long": "key",
    "short": "k",
    "like": "string",
    "list": false,
    "need": true
  },
  {
    "path": [
      "value"
    ],
    "long": "value",
    "short": "v",
    "like": "string",
    "list": false,
    "need": true
  },
  {
    "path": [
      "file"
    ],
    "long": "file",
    "short": "f",
    "like": "string",
    "list": false,
    "need": false
  }
]
