// AUTO-GENERATED by pnpm make:type. Do not edit.

import type { CliOption } from '~/code/tool/shared/console'

export const options: CliOption[] = [
  {
    "path": [
      "input",
      "file",
      "path"
    ],
    "long": "input-file-path",
    "short": "i",
    "like": "string",
    "list": false,
    "need": true
  },
  {
    "path": [
      "output",
      "file",
      "path"
    ],
    "long": "output-file-path",
    "short": "o",
    "like": "string",
    "list": false,
    "need": false
  },
  {
    "path": [
      "text"
    ],
    "long": "text",
    "short": "t",
    "like": "string",
    "list": false,
    "need": true,
    "note": "Text to shape through the font"
  },
  {
    "path": [
      "features"
    ],
    "long": "features",
    "like": "string",
    "list": false,
    "need": false,
    "note": "OpenType features, e.g. \"+liga,-kern\""
  },
  {
    "path": [
      "script"
    ],
    "long": "script",
    "like": "string",
    "list": false,
    "need": false,
    "note": "ISO 15924 script tag, e.g. \"latn\""
  },
  {
    "path": [
      "language"
    ],
    "long": "language",
    "like": "string",
    "list": false,
    "need": false,
    "note": "BCP 47 language tag, e.g. \"en\""
  },
  {
    "path": [
      "direction"
    ],
    "long": "direction",
    "like": "string",
    "list": false,
    "need": false,
    "note": "ltr, rtl, ttb, or btt"
  }
]
