// AUTO-GENERATED by pnpm make:type. Do not edit.

import type { CliOption } from '~/code/tool/shared/console'

export const options: CliOption[] = [
  {
    "path": [
      "input",
      "file",
      "path"
    ],
    "long": "input-file-path",
    "short": "i",
    "like": "string",
    "list": false,
    "need": true
  },
  {
    "path": [
      "output",
      "file",
      "path"
    ],
    "long": "output-file-path",
    "short": "o",
    "like": "string",
    "list": false,
    "need": false
  },
  {
    "path": [
      "level"
    ],
    "long": "level",
    "like": "disassemble_jvm_level",
    "list": false,
    "need": false
  },
  {
    "path": [
      "verbose"
    ],
    "long": "verbose",
    "like": "boolean",
    "list": false,
    "need": false
  },
  {
    "path": [
      "constants"
    ],
    "long": "constants",
    "like": "boolean",
    "list": false,
    "need": false
  },
  {
    "path": [
      "lineNumbers"
    ],
    "long": "line-numbers",
    "like": "boolean",
    "list": false,
    "need": false
  },
  {
    "path": [
      "classpath"
    ],
    "long": "classpath",
    "like": "string",
    "list": false,
    "need": false
  },
  {
    "path": [
      "className"
    ],
    "long": "class-name",
    "like": "string",
    "list": false,
    "need": false
  }
]
