// AUTO-GENERATED by pnpm make:type. Do not edit.

import type { CliOption } from '~/code/tool/shared/console'

export const options: CliOption[] = [
  {
    "path": [
      "input",
      "file",
      "path"
    ],
    "long": "input-file-path",
    "short": "i",
    "like": "string",
    "list": false,
    "need": true
  },
  {
    "path": [
      "output",
      "file",
      "path"
    ],
    "long": "output-file-path",
    "short": "o",
    "like": "string",
    "list": false,
    "need": false
  },
  {
    "path": [
      "bytes"
    ],
    "long": "bytes",
    "like": "boolean",
    "list": false,
    "need": false
  },
  {
    "path": [
      "header"
    ],
    "long": "header",
    "like": "boolean",
    "list": false,
    "need": false
  },
  {
    "path": [
      "tokens"
    ],
    "long": "tokens",
    "like": "boolean",
    "list": false,
    "need": false
  },
  {
    "path": [
      "noBar"
    ],
    "long": "no-bar",
    "like": "boolean",
    "list": false,
    "need": false
  }
]
