// AUTO-GENERATED by pnpm make:type. Do not edit.

import type { CliOption } from '~/code/tool/shared/console'

export const options: CliOption[] = [
  {
    "path": [
      "input",
      "file",
      "path"
    ],
    "long": "input-file-path",
    "short": "i",
    "like": "string",
    "list": false,
    "need": true
  },
  {
    "path": [
      "output",
      "file",
      "path"
    ],
    "long": "output-file-path",
    "short": "o",
    "like": "string",
    "list": false,
    "need": true
  },
  {
    "path": [
      "videoCodec"
    ],
    "long": "video-codec",
    "like": "string",
    "list": false,
    "need": false
  },
  {
    "path": [
      "crf"
    ],
    "long": "crf",
    "like": "natural_number",
    "list": false,
    "need": false
  },
  {
    "path": [
      "preset"
    ],
    "long": "preset",
    "like": "string",
    "list": false,
    "need": false
  },
  {
    "path": [
      "width"
    ],
    "long": "width",
    "like": "natural_number",
    "list": false,
    "need": false
  },
  {
    "path": [
      "pixelFormat"
    ],
    "long": "pixel-format",
    "like": "string",
    "list": false,
    "need": false
  },
  {
    "path": [
      "audioCodec"
    ],
    "long": "audio-codec",
    "like": "string",
    "list": false,
    "need": false
  },
  {
    "path": [
      "audioBitrate"
    ],
    "long": "audio-bitrate",
    "like": "string",
    "list": false,
    "need": false
  },
  {
    "path": [
      "faststart"
    ],
    "long": "faststart",
    "like": "boolean",
    "list": false,
    "need": false
  },
  {
    "path": [
      "silent"
    ],
    "long": "silent",
    "like": "boolean",
    "list": false,
    "need": false
  }
]
