// AUTO-GENERATED by pnpm make:type. Do not edit.

import type { CliOption } from '~/code/tool/shared/console'

export const options: CliOption[] = [
  {
    "path": [
      "input",
      "format"
    ],
    "long": "input-format",
    "like": "string",
    "list": false,
    "need": true
  },
  {
    "path": [
      "input",
      "file",
      "path"
    ],
    "long": "input-file-path",
    "like": "string",
    "list": false,
    "need": true
  },
  {
    "path": [
      "output",
      "format"
    ],
    "long": "output-format",
    "like": "string",
    "list": false,
    "need": true
  },
  {
    "path": [
      "output",
      "file",
      "path"
    ],
    "long": "output-file-path",
    "like": "string",
    "list": false,
    "need": false
  },
  {
    "path": [
      "pathScope"
    ],
    "long": "path-scope",
    "like": "string",
    "list": false,
    "need": false,
    "note": "This is used from the UI to scope file paths to a specific folder."
  },
  {
    "path": [
      "colorCount"
    ],
    "long": "color-count",
    "like": "natural_number",
    "list": false,
    "need": false
  },
  {
    "path": [
      "colorMatrix",
      "row"
    ],
    "long": "color-matrix-row",
    "like": "natural_number",
    "list": false,
    "need": false
  },
  {
    "path": [
      "colorMatrix",
      "column"
    ],
    "long": "color-matrix-column",
    "like": "natural_number",
    "list": false,
    "need": false
  },
  {
    "path": [
      "colorMatrix",
      "value"
    ],
    "long": "color-matrix-value",
    "like": "decimal",
    "list": true,
    "need": false
  },
  {
    "path": [
      "colorSpace"
    ],
    "long": "color-space",
    "like": "image_magick_color_space",
    "list": false,
    "need": false
  },
  {
    "path": [
      "compare"
    ],
    "long": "compare",
    "like": "boolean",
    "list": false,
    "need": false
  },
  {
    "path": [
      "compression"
    ],
    "long": "compression",
    "like": "image_magick_compression",
    "list": false,
    "need": false
  },
  {
    "path": [
      "density"
    ],
    "long": "density",
    "like": "natural_number",
    "list": false,
    "need": false
  },
  {
    "path": [
      "quality"
    ],
    "long": "quality",
    "like": "natural_number",
    "list": false,
    "need": false
  }
]
