// AUTO-GENERATED by pnpm make:type. Do not edit.

import type { CliOption } from '~/code/tool/shared/console'

export const options: CliOption[] = [
  {
    "path": [
      "input",
      "file",
      "path"
    ],
    "long": "input-file-path",
    "short": "i",
    "like": "string",
    "list": false,
    "need": true
  },
  {
    "path": [
      "output",
      "file",
      "path"
    ],
    "long": "output-file-path",
    "short": "o",
    "like": "string",
    "list": false,
    "need": true
  },
  {
    "path": [
      "text"
    ],
    "long": "text",
    "short": "t",
    "like": "string",
    "list": false,
    "need": false,
    "note": "Glyphs to keep, e.g. \"Hello world\""
  },
  {
    "path": [
      "unicodes"
    ],
    "long": "unicodes",
    "short": "u",
    "like": "string",
    "list": false,
    "need": false,
    "note": "Codepoints/ranges, e.g. \"U+0020-007F,U+00A9\""
  },
  {
    "path": [
      "layoutFeatures"
    ],
    "long": "layout-features",
    "like": "string",
    "list": false,
    "need": false,
    "note": "Comma list of OpenType features to keep (default: common)"
  },
  {
    "path": [
      "flavor"
    ],
    "long": "flavor",
    "like": "string",
    "list": false,
    "need": false,
    "note": "Output wrapper: `woff`, `woff2`, or unset for raw sfnt"
  }
]
