/**
 * Programmatic Node.js API for `@cluesurf/task`. Usage:
 *
 *   import Task from '@cluesurf/task'
 *   const task = new Task()
 *   await task.convert({
 *     input:  { format: 'png', file: { path: 'a.png' } },
 *     output: { format: 'jpg', file: { path: 'a.jpg' } },
 *   })
 *
 * Types come from `~/code/form/export/node` (auto-generated by
 * `pnpm make:type`) — every method's parameter is the union of
 * generated `<Verb>NodeInput` shapes, so TypeScript narrows on the
 * `format` / `language` discriminator at the call site.
 *
 * Each method lazy-imports its handler on first call so cold boot
 * only pays for type-stripped routing — heavy native deps
 * (ffmpeg, imagemagick, duckdb, …) load when their verb runs.
 */

import type {
  CompileNodeInput,
  CompileNodeOutput,
  CompressNodeInput,
  CompressNodeOutput,
  ConvertNodeInput,
  ConvertNodeOutput,
  DecryptNodeInput,
  DecryptNodeOutput,
  DisassembleNodeInput,
  DisassembleNodeOutput,
  DumpNodeInput,
  DumpNodeOutput,
  EncryptNodeInput,
  EncryptNodeOutput,
  FlipNodeInput,
  FlipNodeOutput,
  FormatNodeInput,
  FormatNodeOutput,
  InspectNodeInput,
  InspectNodeOutput,
  NormalizeNodeInput,
  NormalizeNodeOutput,
  PadNodeInput,
  PadNodeOutput,
  RemoveNodeInput,
  RemoveNodeOutput,
  RenderNodeInput,
  RenderNodeOutput,
  RotateNodeInput,
  RotateNodeOutput,
  ShapeNodeInput,
  ShapeNodeOutput,
  SplitNodeInput,
  SplitNodeOutput,
  SubsetNodeInput,
  SubsetNodeOutput,
  TrimNodeInput,
  TrimNodeOutput,
  UpdateNodeInput,
  UpdateNodeOutput,
} from '~/code/form/export/node'

import type { Archive } from '~/code/form/action/archive/index'
import type { Highlight } from '~/code/form/action/highlight/index'
import type {
  CombineNodeInput,
  CombineNodeOutput,
} from '~/code/call/combine/node'
import type { MergeNodeInput } from '~/code/call/merge/node'
import type { SearchNodeInput } from '~/code/call/search/node'
import type {
  FetchNodeInput,
  FetchNodeOutput,
} from '~/code/call/fetch/shared'
import type {
  SyncNodeInput,
  SyncNodeOutput,
} from '~/code/call/sync/shared'
import type { DetectBidiNodeInput } from '~/code/call/detect/bidi/node'
import type { ResizeVideoNodeInput } from '~/code/call/resize/video/node'
import type {
  OptimizeVideoNodeInput,
  OptimizeVideoNodeOutput,
} from '~/code/call/optimize/video/node'
import type { QuerySqlDuckdbNodeInput } from '~/code/call/query/sql/duckdb/node'
import type { QueryDbNodeInput } from '~/code/call/query/db/node'

// Verbs added in the recent batch — typed but not yet on the
// `Task` class until we wire the discriminated dispatch below.
import type {
  InspectTlsNodeInput,
  InspectTlsNodeOutput,
} from '~/code/call/inspect/tls/node'
import type {
  InspectDnsNodeInput,
  InspectDnsNodeOutput,
} from '~/code/call/inspect/dns/node'
import type { InspectFileNodeLocalInput } from '~/code/form/action/inspect/file/node'
import type {
  ParseEntityNodeInput,
  ParseEntityNodeOutput,
} from '~/code/call/parse/entity/node'
import type {
  ParseLinkNodeInput,
  ParseLinkNodeOutput,
} from '~/code/call/parse/link/node'
import type {
  ParseTableNodeInput,
  ParseTableNodeOutput,
} from '~/code/call/parse/table/node'
import type {
  TransformDataNodeInput,
  TransformDataNodeOutput,
} from '~/code/call/transform/data/node'
import type { ScanEnvNodeInput } from '~/code/call/scan/env/node'
import type { ProfileCpuSamplyNodeInput } from '~/code/call/profile/cpu/samply/node'
import type { ProfileCpuZeroxNodeInput } from '~/code/call/profile/cpu/zerox/node'
import type { ProfileCpuClinicNodeInput } from '~/code/call/profile/cpu/clinic/node'
import type { TraceProcessStraceNodeInput } from '~/code/call/trace/process/strace/node'
import type { TraceProcessDtrussNodeInput } from '~/code/call/trace/process/dtruss/node'
import type { TraceProcessProcmonNodeInput } from '~/code/call/trace/process/procmon/node'

export type TaskOptions = {
  host?: string
  code?: string
}

export type MediaKind =
  | 'image'
  | 'audio'
  | 'video'
  | 'font'
  | 'document'
  | 'archive'
  | 'data'
  | 'wasm'
  | 'jvm'
  | 'dotnet'

const KIND_BY_EXT: Record<string, MediaKind> = {
  png: 'image',
  jpg: 'image',
  jpeg: 'image',
  gif: 'image',
  webp: 'image',
  bmp: 'image',
  tiff: 'image',
  tif: 'image',
  heic: 'image',
  avif: 'image',
  svg: 'image',

  mp3: 'audio',
  wav: 'audio',
  flac: 'audio',
  ogg: 'audio',
  opus: 'audio',
  m4a: 'audio',
  aac: 'audio',

  mp4: 'video',
  mov: 'video',
  mkv: 'video',
  webm: 'video',
  avi: 'video',
  m4v: 'video',

  ttf: 'font',
  otf: 'font',
  woff: 'font',
  woff2: 'font',
  eot: 'font',
  ttx: 'font',

  pdf: 'document',
  docx: 'document',
  odt: 'document',
  epub: 'document',

  zip: 'archive',
  tar: 'archive',
  gz: 'archive',
  tgz: 'archive',
  '7z': 'archive',
  rar: 'archive',
  xz: 'archive',
  zst: 'archive',

  csv: 'data',
  tsv: 'data',
  json: 'data',
  jsonl: 'data',
  yaml: 'data',
  yml: 'data',
  toml: 'data',
  xml: 'data',
  parquet: 'data',
  avro: 'data',

  wasm: 'wasm',
  class: 'jvm',
  jar: 'jvm',
  dll: 'dotnet',
  exe: 'dotnet',
}

function extFromPath(p: string): string {
  const i = p.lastIndexOf('.')
  return i === -1 ? '' : p.slice(i + 1).toLowerCase()
}

function pathOf(input: unknown): string {
  const i = input as
    | {
        input?: { file?: { path?: unknown } }
        file?: { path?: unknown }
      }
    | null
    | undefined
  const p = i?.input?.file?.path ?? i?.file?.path
  return typeof p === 'string' ? p : ''
}

function kindOf(input: unknown): MediaKind | undefined {
  const i = input as
    | { input?: { format?: unknown }; format?: unknown }
    | null
    | undefined
  const fmt = String(i?.input?.format ?? i?.format ?? '').toLowerCase()
  return KIND_BY_EXT[fmt] ?? KIND_BY_EXT[extFromPath(pathOf(input))]
}

// ── Set / Detect input shapes (no generated union) ─────────────

export type SetEolInput = {
  eol: 'lf' | 'crlf'
  file: string
  output?: string
}
export type SetEncodingInput = {
  encoding: string
  file: string
  output?: string
}
export type SetMetadataInput = {
  input: { file: { path: string } }
  output?: { file?: { path: string } }
  title?: string
  artist?: string
  album?: string
}
export type SetInput = SetEolInput | SetEncodingInput | SetMetadataInput

export type QueryInput =
  | (QuerySqlDuckdbNodeInput & { tool?: 'duckdb' })
  | (QueryDbNodeInput & { tool: 'psql' | 'postgres' | 'pg' })

/**
 * Discriminated `task.parse(...)` input — `thing` selects the
 * sub-handler. The `entity` / `link` / `table` variants get full
 * IDE autocomplete on their respective option fields.
 */
export type ParseInput =
  | (ParseEntityNodeInput & { thing: 'entity' })
  | (ParseLinkNodeInput & { thing: 'link' })
  | (ParseTableNodeInput & { thing: 'table' })

export type ParseOutput =
  | ParseEntityNodeOutput
  | ParseLinkNodeOutput
  | ParseTableNodeOutput

/** Discriminated `task.transform(...)` — only `data` for now. */
export type TransformInput = TransformDataNodeInput & { thing: 'data' }
export type TransformOutput = TransformDataNodeOutput

/** Discriminated `task.scan(...)` — only `env` ships through Task today. */
export type ScanInput = ScanEnvNodeInput & { thing: 'env' }

/**
 * `task.profile(...)` input. Today only `cpu` is wired; the
 * `tool` field picks samply (default), 0x, or clinic.
 */
export type ProfileInput =
  | (ProfileCpuSamplyNodeInput & { thing: 'cpu'; tool?: 'samply' })
  | (ProfileCpuZeroxNodeInput & { thing: 'cpu'; tool: '0x' })
  | (ProfileCpuClinicNodeInput & { thing: 'cpu'; tool: 'clinic' })

/**
 * `task.trace(...)` input. Auto-picks per-OS backend; override
 * with `tool` for explicit dispatch.
 */
export type TraceInput =
  | (TraceProcessStraceNodeInput & { thing: 'process'; tool?: 'strace' })
  | (TraceProcessDtrussNodeInput & { thing: 'process'; tool: 'dtruss' })
  | (TraceProcessProcmonNodeInput & { thing: 'process'; tool: 'procmon' })

/**
 * `task.inspect(...)` extended with the new tls / dns variants.
 * Defaulting to file-inspection keeps the prior behavior — pass
 * `thing: 'tls'` or `thing: 'dns'` to route to the new verbs.
 */
export type InspectInput =
  | (InspectFileNodeLocalInput & { thing?: 'file' })
  | (InspectTlsNodeInput & { thing: 'tls' })
  | (InspectDnsNodeInput & { thing: 'dns' })

export type InspectOutput =
  | InspectNodeOutput
  | InspectTlsNodeOutput
  | InspectDnsNodeOutput

/** Pull the format / language discriminator off `FormatNodeInput`. */
export type FormatLanguage = FormatNodeInput extends { format: infer F }
  ? F
  : never

/**
 * Public-API format input. Either a strict generated variant
 * (`format: 'python' | 'rust' | …`) or a `language` shorthand
 * the dispatcher maps onto `format`. `language` is strictly
 * typed to the supported set — autocomplete shows exactly the
 * languages we route. Pass-through of the strict union still
 * works for callers who already have a `FormatNodeInput`.
 */
export type FormatInput =
  | FormatNodeInput
  | {
      language: FormatLanguage
      input: { file: { path: string } }
      output?: { file?: { path: string } }
    }

export default class Task {
  private host: string
  private code?: string

  constructor(options: TaskOptions = {}) {
    this.host = options.host ?? 'https://task.surf'
    this.code = options.code
  }

  /** Tag input with `handle: 'internal'` so handler dispatch lands on the local-internal branch. */
  private local<T>(input: T): T {
    if (input && typeof input === 'object' && !('handle' in input)) {
      return { ...input, handle: 'internal' } as T
    }
    return input
  }

  /** Lazy-import a module and call its default export. */
  private async run<I, O>(mod: string, input: I): Promise<O> {
    const m = await import(mod)
    return m.default(this.local(input)) as Promise<O>
  }

  /** Lazy-import a module and call a named export. */
  private async call<I, O>(
    mod: string,
    name: string,
    input: I,
  ): Promise<O> {
    const m = await import(mod)
    return m[name](this.local(input)) as Promise<O>
  }

  /** Pick a handler by media kind, with optional fallback. */
  private byKind<I, O>(
    input: I,
    routes: Partial<Record<MediaKind, string>>,
    fallback?: string,
  ): Promise<O> {
    const kind = kindOf(input)
    const mod = (kind && routes[kind]) ?? fallback
    if (!mod) {
      throw new Error(
        `No handler for kind ${kind ?? 'unknown'} (path=${pathOf(input)})`,
      )
    }
    return this.run<I, O>(mod, input)
  }

  // ── Single-handler verbs ───────────────────────────

  archive(i: Archive): Promise<{ file: { path: string } }> {
    return this.run('~/code/call/archive/node', i)
  }
  combine(i: CombineNodeInput): Promise<CombineNodeOutput> {
    return this.run('~/code/call/combine/node', i)
  }
  crop(i: PadNodeInput): Promise<PadNodeOutput> {
    return this.run('~/code/call/crop/document/node', i)
  }
  decrypt(i: DecryptNodeInput): Promise<DecryptNodeOutput> {
    return this.run('~/code/call/decrypt/file/node', i)
  }
  dump(i: DumpNodeInput): Promise<DumpNodeOutput> {
    return this.run('~/code/call/dump/font/node', i)
  }
  encrypt(i: EncryptNodeInput): Promise<EncryptNodeOutput> {
    return this.run('~/code/call/encrypt/file/node', i)
  }
  fetch(i: FetchNodeInput): Promise<FetchNodeOutput> {
    return this.run('~/code/call/fetch/node', i)
  }
  flip(i: FlipNodeInput): Promise<FlipNodeOutput> {
    return this.run('~/code/call/flip/image/node', i)
  }
  highlight(i: Highlight): Promise<{ file: { path: string } }> {
    return this.run('~/code/call/highlight/node', i)
  }
  /**
   * Inspect a file (default), a TLS chain, or a DNS lookup. The
   * `thing` discriminator routes; omit it for backward compat
   * with the prior file-only signature.
   */
  inspect(input: InspectInput): Promise<InspectOutput> {
    const thing = (input as { thing?: string }).thing ?? 'file'
    if (thing === 'tls') {
      return this.call(
        '~/code/call/inspect/tls/node',
        'inspectTlsNode',
        stripThing(input),
      )
    }
    if (thing === 'dns') {
      return this.call(
        '~/code/call/inspect/dns/node',
        'inspectDnsNode',
        stripThing(input),
      )
    }
    return this.run('~/code/call/inspect/file/node', stripThing(input))
  }
  merge(i: MergeNodeInput): Promise<{ file: { path: string } }> {
    return this.run('~/code/call/merge/node', i)
  }
  normalize(i: NormalizeNodeInput): Promise<NormalizeNodeOutput> {
    return this.run('~/code/call/normalize/audio/node', i)
  }
  pad(i: PadNodeInput): Promise<PadNodeOutput> {
    return this.run('~/code/call/pad/node', i)
  }
  render(i: RenderNodeInput): Promise<RenderNodeOutput> {
    return this.run('~/code/call/render/font/node', i)
  }
  search(i: SearchNodeInput): Promise<unknown> {
    return this.run('~/code/call/search/node', i)
  }
  shape(i: ShapeNodeInput): Promise<ShapeNodeOutput> {
    return this.run('~/code/call/shape/font/node', i)
  }
  split(i: SplitNodeInput): Promise<SplitNodeOutput> {
    return this.run('~/code/call/split/node', i)
  }
  subset(i: SubsetNodeInput): Promise<SubsetNodeOutput> {
    return this.run('~/code/call/subset/font/node', i)
  }
  sync(i: SyncNodeInput): Promise<SyncNodeOutput> {
    return this.run('~/code/call/sync/node', i)
  }
  verify(i: { input: { file: { path: string } } }): Promise<unknown> {
    return this.run('~/code/call/verify/image/node', i)
  }

  // ── Format-pair dispatch ───────────────────────────

  convert(i: ConvertNodeInput): Promise<ConvertNodeOutput> {
    return this.run('~/code/call/convert/node', i)
  }

  // ── Query dispatch ─────────────────────────────────

  query(input: QueryInput): Promise<string> {
    const tool = String(
      (input as { tool?: string }).tool ?? 'duckdb',
    ).toLowerCase()
    if (tool === 'duckdb') {
      return this.call(
        '~/code/call/query/sql/duckdb/node',
        'querySqlDuckdbNode',
        input,
      )
    }
    if (tool === 'psql' || tool === 'postgres' || tool === 'pg') {
      return this.call(
        '~/code/call/query/db/node',
        'queryDbNode',
        input,
      )
    }
    throw new Error(`query: unsupported tool "${tool}"`)
  }

  // ── Thing-dispatched verbs added in the recent batch ──

  /**
   * Pull entities / links / tables out of text or markup. The
   * `thing` discriminator picks the sub-handler; each variant
   * gives full IDE autocomplete on its own option fields.
   */
  parse(input: ParseInput): Promise<ParseOutput> {
    const thing = (input as { thing: string }).thing
    switch (thing) {
      case 'entity':
        return this.call('~/code/call/parse/entity/node', 'parseEntityNode', stripThing(input))
      case 'link':
        return this.call('~/code/call/parse/link/node', 'parseLinkNode', stripThing(input))
      case 'table':
        return this.call('~/code/call/parse/table/node', 'parseTableNode', stripThing(input))
      default:
        throw new Error(`parse: unsupported thing "${thing}"`)
    }
  }

  /**
   * Reshape a structured-data file via a config map / jq
   * expression / SQL query.
   */
  transform(input: TransformInput): Promise<TransformOutput> {
    return this.call(
      '~/code/call/transform/data/node',
      'transformDataNode',
      stripThing(input),
    )
  }

  /**
   * Pull embedded images out of pdf / docx / html. The `format`
   * field (or input.file extension) picks the parser.
   */
  isolate(input: IsolateImageInput): Promise<IsolateImageOutput> {
    return this.call(
      '~/code/call/isolate/image/node',
      'isolateImageNode',
      input,
    )
  }

  /**
   * Scan a path for leaked secrets. Today only `thing: 'env'`
   * is wired through Task; other scan variants stay CLI-only
   * because they take richer input shapes.
   */
  scan(input: ScanInput): Promise<unknown> {
    const thing = (input as { thing: string }).thing
    if (thing === 'env') {
      return this.call('~/code/call/scan/env/node', 'scanEnvNode', stripThing(input))
    }
    throw new Error(`scan: unsupported thing "${thing}" via Task class — use the CLI`)
  }

  /**
   * Sample a process / fresh command into a flamegraph. The
   * `tool` field picks the backend; otherwise we sniff the
   * command head — `node` / `npx` / `tsx` → 0x, anything else
   * → samply.
   */
  profile(input: ProfileInput): Promise<unknown> {
    const tool =
      (input as { tool?: string }).tool ?? defaultProfileTool(input)
    switch (tool) {
      case 'samply':
        return this.call('~/code/call/profile/cpu/samply/node', 'profileCpuSamplyNode', stripMeta(input))
      case '0x':
        return this.call('~/code/call/profile/cpu/zerox/node', 'profileCpuZeroxNode', stripMeta(input))
      case 'clinic':
        return this.call('~/code/call/profile/cpu/clinic/node', 'profileCpuClinicNode', stripMeta(input))
      default:
        throw new Error(`profile: unsupported tool "${tool}"`)
    }
  }

  /**
   * Trace a process via strace (linux) / dtruss (macOS) /
   * procmon (windows). Auto-picks per `os.platform()`; force
   * with `tool`.
   */
  trace(input: TraceInput): Promise<unknown> {
    const tool =
      (input as { tool?: string }).tool ?? defaultTraceTool()
    switch (tool) {
      case 'strace':
        return this.call('~/code/call/trace/process/strace/node', 'traceProcessStraceNode', stripMeta(input))
      case 'dtruss':
        return this.call('~/code/call/trace/process/dtruss/node', 'traceProcessDtrussNode', stripMeta(input))
      case 'procmon':
        return this.call('~/code/call/trace/process/procmon/node', 'traceProcessProcmonNode', stripMeta(input))
      default:
        throw new Error(`trace: unsupported tool "${tool}"`)
    }
  }

  // ── Kind-dispatched verbs ──────────────────────────

  compress(i: CompressNodeInput): Promise<CompressNodeOutput> {
    return this.byKind(
      i,
      COMPRESS_BY_KIND,
      '~/code/call/compress/image/node',
    )
  }

  trim(i: TrimNodeInput): Promise<TrimNodeOutput> {
    return this.byKind(i, TRIM_BY_KIND, '~/code/call/trim/image/node')
  }

  resize(i: ResizeVideoNodeInput): Promise<unknown> {
    return this.byKind(i, RESIZE_BY_KIND, '~/code/call/resize/image/node')
  }

  rotate(i: RotateNodeInput): Promise<RotateNodeOutput> {
    return this.byKind(i, ROTATE_BY_KIND, '~/code/call/rotate/image/node')
  }

  update(i: UpdateNodeInput): Promise<UpdateNodeOutput> {
    return this.byKind(i, UPDATE_BY_KIND, '~/code/call/update/image/node')
  }

  optimize(
    i: OptimizeVideoNodeInput,
  ): Promise<OptimizeVideoNodeOutput> {
    return this.byKind(
      i,
      OPTIMIZE_BY_KIND,
      '~/code/call/optimize/image/local/node',
    )
  }

  disassemble(i: DisassembleNodeInput): Promise<DisassembleNodeOutput> {
    const fields = i as {
      ghidraHome?: string
      profile?: string
    }
    if (
      fields.ghidraHome ||
      fields.profile === 'imports' ||
      fields.profile === 'exports'
    ) {
      return this.run('~/code/call/disassemble/ghidra/node', i)
    }
    return this.byKind(
      i,
      DISASSEMBLE_BY_KIND,
      '~/code/call/disassemble/radare/node',
    )
  }

  // ── Language-dispatched verbs ──────────────────────

  /**
   * Compile source to a binary / WASM / IR. Dispatch is by
   * `input.format` (the source language); falls back to the file
   * extension when no format is given. Accepts the strict
   * generated `CompileNodeInput` for autocomplete, plus a looser
   * `string` form so `'xyz'` and other unknown-by-design values
   * round-trip through the dispatcher's "unsupported" path.
   */
  compile(input: CompileNodeInput): Promise<CompileNodeOutput> {
    const i = input as { input?: { format?: unknown } }
    const lang = String(
      i.input?.format ?? extFromPath(pathOf(input)),
    ).toLowerCase()
    const mod = COMPILE_BY_LANG[lang]
    if (!mod) throw new Error(`compile: unsupported language "${lang}"`)
    return this.run(mod, input)
  }

  /**
   * Format source code in place. The public API uses `language`
   * as the human-readable discriminator; we map it onto the
   * generated handler's `format` field internally. C / C++ /
   * Objective-C all route through clang-format with the language
   * name in `format` so the underlying parser picks the right
   * grammar.
   */
  format(input: FormatInput): Promise<FormatNodeOutput> {
    const i = input as { language?: string; format?: string }
    const lang = String(i.language ?? i.format ?? '').toLowerCase()
    if (!lang) throw new Error('format: language required')
    const mod = FORMAT_BY_LANG[lang]
    if (!mod) throw new Error(`format: unsupported language "${lang}"`)
    const next = { ...input, format: lang } as FormatNodeInput
    delete (next as { language?: string }).language
    return this.run(mod, next)
  }

  // ── Field-dispatched verbs ─────────────────────────

  remove(input: RemoveNodeInput): Promise<RemoveNodeOutput> {
    const i = input as {
      tag?: unknown
      preset?: unknown
      password?: unknown
      background?: unknown
    }
    if (i.tag || i.preset)
      return this.run('~/code/call/remove/exif/node', input)
    if (i.password !== undefined)
      return this.run('~/code/call/remove/password/node', input)
    if (i.background)
      return this.run('~/code/call/remove/transparency/node', input)
    return this.run('~/code/call/remove/metadata/node', input)
  }

  /**
   * Set a property on a file. The discriminator is which property
   * you provide — `encoding`, `eol`, or one of the id3-style
   * metadata fields.
   */
  set(input: SetInput): Promise<unknown> {
    const i = input as Partial<
      SetEolInput & SetEncodingInput & SetMetadataInput
    >
    if (i.encoding) {
      return this.call(
        '~/code/call/set/encoding/node',
        'setEncodingNode',
        {
          target: i.encoding,
          file: i.file!,
          output: i.output as string | undefined,
        },
      )
    }
    if (i.eol) {
      return this.call('~/code/call/set/eol/node', 'setEolNode', {
        target: i.eol,
        file: i.file!,
        output: i.output as string | undefined,
      })
    }
    if (i.title || i.artist || i.album) {
      return this.run('~/code/call/set/metadata/node', input)
    }
    throw new Error('set: specify encoding, eol, or metadata fields')
  }

  detect(input: DetectBidiNodeInput): Promise<unknown> {
    return this.call(
      '~/code/call/detect/bidi/node',
      'detectBidiNode',
      input,
    )
  }
}

const COMPRESS_BY_KIND: Partial<Record<MediaKind, string>> = {
  audio: '~/code/call/compress/audio/node',
  video: '~/code/call/compress/video/node',
  font: '~/code/call/compress/font/node',
}

const TRIM_BY_KIND: Partial<Record<MediaKind, string>> = {
  audio: '~/code/call/trim/audio/node',
  video: '~/code/call/trim/video/node',
}

const RESIZE_BY_KIND: Partial<Record<MediaKind, string>> = {
  video: '~/code/call/resize/video/node',
}

const ROTATE_BY_KIND: Partial<Record<MediaKind, string>> = {
  video: '~/code/call/rotate/video/node',
}

const UPDATE_BY_KIND: Partial<Record<MediaKind, string>> = {
  font: '~/code/call/update/font/node',
  video: '~/code/call/update/video/node',
}

const OPTIMIZE_BY_KIND: Partial<Record<MediaKind, string>> = {
  video: '~/code/call/optimize/video/node',
}

const DISASSEMBLE_BY_KIND: Partial<Record<MediaKind, string>> = {
  wasm: '~/code/call/disassemble/wasm/node',
  jvm: '~/code/call/disassemble/jvm/node',
  dotnet: '~/code/call/disassemble/dotnet/node',
}

const COMPILE_BY_LANG: Record<string, string> = {
  c: '~/code/call/compile/code/c/node',
  h: '~/code/call/compile/code/c/node',
  cpp: '~/code/call/compile/code/cpp/node',
  cc: '~/code/call/compile/code/cpp/node',
  cxx: '~/code/call/compile/code/cpp/node',
  rs: '~/code/call/compile/code/rust/node',
  rust: '~/code/call/compile/code/rust/node',
  swift: '~/code/call/compile/code/swift/node',
  go: '~/code/call/compile/code/go/node',
  zig: '~/code/call/compile/code/zig/node',
  hs: '~/code/call/compile/code/haskell/node',
  haskell: '~/code/call/compile/code/haskell/node',
  ml: '~/code/call/compile/code/ocaml/node',
  ocaml: '~/code/call/compile/code/ocaml/node',
  dart: '~/code/call/compile/code/dart/node',
  nim: '~/code/call/compile/code/nim/node',
  cr: '~/code/call/compile/code/crystal/node',
  crystal: '~/code/call/compile/code/crystal/node',
  v: '~/code/call/compile/code/v/node',
  ts: '~/code/call/compile/code/tsc/node',
  tsc: '~/code/call/compile/code/tsc/node',
  wast: '~/code/call/compile/code/wast/node',
  wat: '~/code/call/compile/code/wast/node',
  'kotlin-jvm': '~/code/call/compile/code/kotlin-jvm/node',
  'kotlin-native': '~/code/call/compile/code/kotlin-native/node',
  'wasm-emcc': '~/code/call/compile/code/wasm-emcc/node',
  'wasm-wasi': '~/code/call/compile/code/wasm-wasi/node',
  'wasm-pack': '~/code/call/compile/code/wasm-pack/node',
  'llvm-opt': '~/code/call/compile/code/llvm-opt/node',
  'llvm-llc': '~/code/call/compile/code/llvm-llc/node',
}

const FORMAT_BY_LANG: Record<string, string> = {
  c: '~/code/call/format/code/clang/node',
  cpp: '~/code/call/format/code/clang/node',
  objc: '~/code/call/format/code/clang/node',
  python: '~/code/call/format/code/python/node',
  rust: '~/code/call/format/code/rust/node',
  swift: '~/code/call/format/code/swift/node',
  kotlin: '~/code/call/format/code/kotlin/node',
  ruby: '~/code/call/format/code/ruby/node',
  go: '~/code/call/format/code/go/node',
  java: '~/code/call/format/code/java/node',
  shell: '~/code/call/format/code/shell/node',
  sql: '~/code/call/format/code/sql/node',
  dart: '~/code/call/format/code/dart/node',
  haskell: '~/code/call/format/code/haskell/node',
  ocaml: '~/code/call/format/code/ocaml/node',
  zig: '~/code/call/format/code/zig/node',
  lua: '~/code/call/format/code/lua/node',
  nix: '~/code/call/format/code/nix/node',
  toml: '~/code/call/format/code/toml/node',
  perl: '~/code/call/format/code/perl/node',
  php: '~/code/call/format/code/php/node',
  scala: '~/code/call/format/code/scala/node',
  clojure: '~/code/call/format/code/clojure/node',
  elixir: '~/code/call/format/code/elixir/node',
  elm: '~/code/call/format/code/elm/node',
  erlang: '~/code/call/format/code/erlang/node',
  gleam: '~/code/call/format/code/gleam/node',
  crystal: '~/code/call/format/code/crystal/node',
  d: '~/code/call/format/code/d/node',
  purescript: '~/code/call/format/code/purescript/node',
  terraform: '~/code/call/format/code/terraform/node',
  assembly: '~/code/call/format/code/assembly/node',
  asm: '~/code/call/format/code/assembly/node',
}

/* ── Helpers for the thing-dispatched methods above ──────────── */

function stripThing<T extends { thing?: string }>(input: T): Omit<T, 'thing'> {
  const { thing: _ignored, ...rest } = input
  void _ignored
  return rest
}

function stripMeta<T extends { thing?: string; tool?: string }>(
  input: T,
): Omit<T, 'thing' | 'tool'> {
  const { thing: _t, tool: _u, ...rest } = input
  void _t
  void _u
  return rest
}

function defaultProfileTool(input: unknown): 'samply' | '0x' | 'clinic' {
  const cmd =
    (input as { command?: unknown[] }).command?.[0] ?? ''
  if (typeof cmd === 'string' && /^(node|nodejs|npx|tsx|ts-node)$/i.test(cmd)) {
    return '0x'
  }
  return 'samply'
}

function defaultTraceTool(): 'strace' | 'dtruss' | 'procmon' {
  const platform = process.platform
  if (platform === 'linux') return 'strace'
  if (platform === 'darwin') return 'dtruss'
  if (platform === 'win32') return 'procmon'
  throw new Error(`trace: no default backend for platform "${platform}"`)
}

/* ── Isolate (extract embedded images) ───────────────────────── */

export type IsolateImageInput = {
  input: {
    file: { path: string }
    /** Override format detection. Otherwise picked from extension. */
    format?: 'pdf' | 'docx' | 'html'
  }
  output: { directory: { path: string } }
  /** Filename prefix for the emitted images (default `image`). */
  prefix?: string
}

export type IsolateImageOutput = {
  files: Array<{ path: string; bytes: number; mime?: string }>
}

export { Task, kindOf, extFromPath }
