// AUTO-GENERATED by pnpm make:type. Do not edit.

import type { CliOption } from '~/code/tool/shared/console'

export const options: CliOption[] = [
  {
    "path": [
      "input",
      "file",
      "path"
    ],
    "long": "input-file-path",
    "short": "i",
    "like": "string",
    "list": false,
    "need": true
  },
  {
    "path": [
      "output",
      "file",
      "path"
    ],
    "long": "output-file-path",
    "short": "o",
    "like": "string",
    "list": false,
    "need": false
  },
  {
    "path": [
      "folding"
    ],
    "long": "folding",
    "like": "boolean",
    "list": false,
    "need": false
  },
  {
    "path": [
      "inline"
    ],
    "long": "inline",
    "like": "boolean",
    "list": false,
    "need": false
  },
  {
    "path": [
      "noDebugNames"
    ],
    "long": "no-debug-names",
    "like": "boolean",
    "list": false,
    "need": false
  }
]
