// AUTO-GENERATED by pnpm make:type. Do not edit.

import type { CliOption } from '~/code/tool/shared/console'

export const options: CliOption[] = [
  {
    "path": [
      "input",
      "file",
      "path"
    ],
    "long": "input-file-path",
    "short": "i",
    "like": "string",
    "list": false,
    "need": true
  },
  {
    "path": [
      "output",
      "file",
      "path"
    ],
    "long": "output-file-path",
    "short": "o",
    "like": "string",
    "list": false,
    "need": true
  },
  {
    "path": [
      "outputFormat"
    ],
    "long": "output-format",
    "like": "string",
    "list": false,
    "need": false,
    "note": "Output format: svg, eps, or ps"
  },
  {
    "path": [
      "threshold"
    ],
    "long": "threshold",
    "like": "decimal",
    "list": false,
    "need": false,
    "note": "Black-level threshold for the input bitmap (0.0-1.0)"
  },
  {
    "path": [
      "turdsize"
    ],
    "long": "turdsize",
    "like": "natural_number",
    "list": false,
    "need": false,
    "note": "Speckle size filter"
  }
]
