// AUTO-GENERATED by pnpm make:type. Do not edit.

import type { CliOption } from '~/code/tool/shared/console'

export const options: CliOption[] = [
  {
    "path": [
      "input",
      "file",
      "path"
    ],
    "long": "input-file-path",
    "short": "i",
    "like": "string",
    "list": false,
    "need": true
  },
  {
    "path": [
      "output",
      "file",
      "path"
    ],
    "long": "output-file-path",
    "short": "o",
    "like": "string",
    "list": false,
    "need": false
  },
  {
    "path": [
      "tool"
    ],
    "long": "tool",
    "like": "disassemble_radare_tool",
    "list": false,
    "need": false
  },
  {
    "path": [
      "script"
    ],
    "long": "script",
    "like": "string",
    "list": false,
    "need": false
  },
  {
    "path": [
      "profile"
    ],
    "long": "profile",
    "like": "disassemble_radare_profile",
    "list": false,
    "need": false
  },
  {
    "path": [
      "commands"
    ],
    "long": "commands",
    "like": "string",
    "list": true,
    "need": false
  }
]
