// AUTO-GENERATED by pnpm make:type. Do not edit.

import type { CliOption } from '~/code/tool/shared/console'

export const options: CliOption[] = [
  {
    "path": [
      "tool"
    ],
    "long": "tool",
    "like": "string",
    "list": false,
    "need": false
  },
  {
    "path": [
      "input",
      "format"
    ],
    "long": "input-format",
    "short": "I",
    "like": "string",
    "list": false,
    "need": true
  },
  {
    "path": [
      "input",
      "file",
      "path"
    ],
    "long": "input-file-path",
    "short": "i",
    "like": "string",
    "list": false,
    "need": true
  },
  {
    "path": [
      "output",
      "format"
    ],
    "long": "output-format",
    "short": "O",
    "like": "string",
    "list": false,
    "need": true
  },
  {
    "path": [
      "output",
      "file",
      "path"
    ],
    "long": "output-file-path",
    "short": "o",
    "like": "string",
    "list": false,
    "need": true
  }
]
