// AUTO-GENERATED by pnpm make:type. Do not edit.

import type { CliOption } from '~/code/tool/shared/console'

export const options: CliOption[] = [
  {
    "path": [
      "input",
      "file",
      "path"
    ],
    "long": "input-file-path",
    "short": "i",
    "like": "string",
    "list": false,
    "need": true
  },
  {
    "path": [
      "output",
      "file",
      "path"
    ],
    "long": "output-file-path",
    "short": "o",
    "like": "string",
    "list": false,
    "need": false
  },
  {
    "path": [
      "as"
    ],
    "long": "as",
    "short": "O",
    "like": "string",
    "list": false,
    "need": false,
    "note": "`ttx` (full) or `fea` (GSUB/GPOS only). Default: ttx."
  }
]
