// AUTO-GENERATED by pnpm make:type. Do not edit.

import type { CliOption } from '~/code/tool/shared/console'

export const options: CliOption[] = [
  {
    "path": [
      "input",
      "file",
      "path"
    ],
    "long": "input-file-path",
    "short": "i",
    "like": "string",
    "list": false,
    "need": true
  },
  {
    "path": [
      "output",
      "file",
      "path"
    ],
    "long": "output-file-path",
    "short": "o",
    "like": "string",
    "list": false,
    "need": false
  },
  {
    "path": [
      "segments"
    ],
    "long": "segments",
    "short": "s",
    "like": "string",
    "list": false,
    "need": true,
    "note": "`silence` or a fixed chunk length in seconds (e.g. `30`)"
  },
  {
    "path": [
      "silenceDb"
    ],
    "long": "silence-db",
    "like": "string",
    "list": false,
    "need": false,
    "note": "Noise floor for silencedetect (default -30dB)"
  },
  {
    "path": [
      "silenceDuration"
    ],
    "long": "silence-duration",
    "like": "string",
    "list": false,
    "need": false,
    "note": "Minimum silence duration in seconds (default 0.5)"
  }
]
