/**
 * `task disassemble ghidra` — headless Ghidra analyze + export.
 * Generates a Jython post-script for the chosen profile and
 * shells out to `analyzeHeadless`.
 */

import fs from 'node:fs/promises'
import os from 'node:os'
import path from 'node:path'
import type { DisassembleGhidraNodeLocalInput } from '~/code/form/action/disassemble/ghidra/node'
import {
  DisassembleGhidraNodeInputParser,
  DisassembleGhidraNodeLocalInputParser,
  DisassembleGhidraNodeOutputParser,
} from '~/code/form/action/disassemble/ghidra/node/take'
import { ensureParentDir } from '~/code/tool/node/file'
import { createNodeHandler } from '~/code/tool/node/handler'
import {
  resolveExternalInput,
  resolveInternalInput,
} from '~/code/tool/node/resolve'
import { spawnAndWait } from '~/code/tool/node/spawn'
import { buildCommandToDisassembleGhidra } from './command'

type GhidraProfile =
  | 'functions'
  | 'calls'
  | 'imports'
  | 'exports'
  | 'strings'

async function runLocal(input: DisassembleGhidraNodeLocalInput) {
  const inputPath = input.input.file.path
  const profile = (input.profile ?? 'functions') as GhidraProfile
  const outputPath =
    input.output?.file?.path ??
    `${inputPath}.${profile === 'calls' ? 'dot' : 'txt'}`
  await ensureParentDir(outputPath)

  const headlessBin = await locateAnalyzeHeadless(input.ghidraHome)
  const projectDir =
    input.projectDir ??
    (await fs.mkdtemp(path.join(os.tmpdir(), 'task-ghidra-')))
  const projectName = input.projectName ?? 'task-disasm'
  const scriptPath =
    input.script ??
    (await materializePostScript(profile, outputPath))
  const scriptDir = path.dirname(scriptPath)
  const scriptName = path.basename(scriptPath)

  const command = buildCommandToDisassembleGhidra({
    headlessBin,
    inputPath,
    projectDir,
    projectName,
    scriptDir,
    scriptName,
    keepProject: input.keepProject,
    quiet: input.quiet,
  })

  try {
    await spawnAndWait({
      verb: 'disassemble ghidra',
      bin: command.bin,
      args: command.args,
      quiet: input.quiet,
    })
  } finally {
    if (!input.script)
      await fs.unlink(scriptPath).catch(() => undefined)
    if (!input.projectDir && !input.keepProject) {
      await fs
        .rm(projectDir, { recursive: true, force: true })
        .catch(() => undefined)
    }
  }

  return { file: { path: outputPath } }
}

async function locateAnalyzeHeadless(
  home?: string,
): Promise<string> {
  const candidates: string[] = []
  if (home)
    candidates.push(path.join(home, 'support', 'analyzeHeadless'))
  if (process.env.GHIDRA_INSTALL_DIR) {
    candidates.push(
      path.join(
        process.env.GHIDRA_INSTALL_DIR,
        'support',
        'analyzeHeadless',
      ),
    )
  }
  candidates.push('analyzeHeadless')
  for (const c of candidates) {
    if (c === 'analyzeHeadless') return c
    try {
      await fs.access(c)
      return c
    } catch {
      /* try next */
    }
  }
  throw new Error(
    'disassemble ghidra: analyzeHeadless not found. Pass --ghidra-home, set GHIDRA_INSTALL_DIR, or put it on PATH.',
  )
}

async function materializePostScript(
  profile: GhidraProfile,
  outputPath: string,
): Promise<string> {
  const body = SCRIPT_BODIES[profile](outputPath)
  const dir = await fs.mkdtemp(
    path.join(os.tmpdir(), 'task-ghidra-script-'),
  )
  const file = path.join(
    dir,
    `Export${profile.charAt(0).toUpperCase() + profile.slice(1)}.py`,
  )
  await fs.writeFile(file, body, 'utf8')
  return file
}

function pyStr(s: string): string {
  return `'${s.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`
}

const HEADER = `# Auto-generated by @cluesurf/task\n`

const SCRIPT_BODIES: Record<
  GhidraProfile,
  (out: string) => string
> = {
  functions: out =>
    HEADER +
    `\nfm = currentProgram.getFunctionManager()\nwith open(${pyStr(out)}, 'w') as fh:\n    for f in fm.getFunctions(True):\n        fh.write('%s\\t%d\\t%s\\n' % (f.getEntryPoint(), f.getBody().getNumAddresses(), f.getName()))\n`,
  calls: out =>
    HEADER +
    `\nfm = currentProgram.getFunctionManager()\nwith open(${pyStr(out)}, 'w') as fh:\n    fh.write('digraph G {\\n')\n    for f in fm.getFunctions(True):\n        src = f.getName().replace('"', "'")\n        for callee in f.getCalledFunctions(monitor):\n            dst = callee.getName().replace('"', "'")\n            fh.write('  "%s" -> "%s";\\n' % (src, dst))\n    fh.write('}\\n')\n`,
  imports: out =>
    HEADER +
    `\nst = currentProgram.getSymbolTable()\nwith open(${pyStr(out)}, 'w') as fh:\n    for s in st.getExternalSymbols():\n        fh.write('%s\\t%s\\n' % (s.getName(), s.getParentNamespace().getName()))\n`,
  exports: out =>
    HEADER +
    `\nst = currentProgram.getSymbolTable()\nwith open(${pyStr(out)}, 'w') as fh:\n    for s in st.getSymbolIterator():\n        if s.isExternalEntryPoint():\n            fh.write('%s\\t%s\\n' % (s.getAddress(), s.getName()))\n`,
  strings: out =>
    HEADER +
    `\nlisting = currentProgram.getListing()\nwith open(${pyStr(out)}, 'w') as fh:\n    for d in listing.getDefinedData(True):\n        v = d.getValue()\n        if v is not None and hasattr(v, 'toString'):\n            fh.write('%s\\t%s\\n' % (d.getAddress(), v.toString()))\n`,
}

const [disassembleGhidraNode, testDisassembleGhidraNode] =
  createNodeHandler({
    parsers: {
      input: DisassembleGhidraNodeInputParser,
      local: DisassembleGhidraNodeLocalInputParser,
      output: DisassembleGhidraNodeOutputParser,
    },
    resolvers: {
      external: resolveExternalInput,
      internal: resolveInternalInput,
    },
    runLocal,
  })

export default disassembleGhidraNode
export { disassembleGhidraNode, testDisassembleGhidraNode }
