/**
 * `task disassemble ghidra` — headless Ghidra analyze + export.
 *
 * Ghidra ships a CLI at `<install>/support/analyzeHeadless` that
 * creates a project, imports a binary, runs analysis, and then
 * executes a post-script. We generate the post-script on the fly
 * (Jython) for one of a few canned profiles:
 *
 *   functions  → one line per function: `addr  size  name`
 *   calls      → call graph in DOT (`digraph G { ... }`)
 *   imports    → resolved import symbols
 *   exports    → exported symbols
 *   strings    → defined strings + addresses
 *
 * The Ghidra install location is found via:
 *   1. `--ghidra-home <dir>`
 *   2. `GHIDRA_INSTALL_DIR` env var
 *   3. `analyzeHeadless` directly on PATH (some package managers
 *      drop it there)
 *
 * Project state is dropped after the run unless `--keep-project` —
 * we use a temp dir so successive runs don't accumulate state.
 */

import fs from 'node:fs/promises'
import os from 'node:os'
import path from 'node:path'
import { ensureParentDir } from '~/code/tool/node/file'
import { spawnAndWait } from '~/code/tool/node/spawn'
import { buildCommandToDisassembleGhidra } from './command'
import {
  parseDisassembleGhidraNode,
  testDisassembleGhidraNode,
  type DisassembleGhidraNodeInput,
  type DisassembleGhidraNodeOutput,
  type GhidraProfile,
} from './shared'

export type {
  DisassembleGhidraNodeInput,
  DisassembleGhidraNodeOutput,
  GhidraProfile,
}
export { testDisassembleGhidraNode }

export async function disassembleGhidraNode(
  source: DisassembleGhidraNodeInput,
): Promise<DisassembleGhidraNodeOutput> {
  const src = parseDisassembleGhidraNode(source)
  const profile: GhidraProfile = src.profile ?? 'functions'
  const out =
    src.output ??
    `${src.input}.${profile === 'calls' ? 'dot' : 'txt'}`
  await ensureParentDir(out)

  const headlessBin = await locateAnalyzeHeadless(src.ghidraHome)

  const projectDir =
    src.projectDir ??
    (await fs.mkdtemp(path.join(os.tmpdir(), 'task-ghidra-')))
  const projectName = src.projectName ?? 'task-disasm'

  const scriptPath =
    src.script ?? (await materializePostScript(profile, out))
  const scriptDir = path.dirname(scriptPath)
  const scriptName = path.basename(scriptPath)

  const command = buildCommandToDisassembleGhidra({
    source: src,
    headlessBin,
    projectDir,
    projectName,
    scriptDir,
    scriptName,
  })

  try {
    await spawnAndWait({
      verb: 'disassemble ghidra',
      bin: command.bin,
      args: command.args,
      quiet: src.quiet,
    })
  } finally {
    if (!src.script)
      await fs.unlink(scriptPath).catch(() => undefined)
    if (!src.projectDir && !src.keepProject) {
      await fs
        .rm(projectDir, { recursive: true, force: true })
        .catch(() => undefined)
    }
  }

  return { file: { path: out } }
}

async function locateAnalyzeHeadless(home?: string): Promise<string> {
  const candidates: string[] = []
  if (home) {
    candidates.push(path.join(home, 'support', 'analyzeHeadless'))
  }
  if (process.env.GHIDRA_INSTALL_DIR) {
    candidates.push(
      path.join(
        process.env.GHIDRA_INSTALL_DIR,
        'support',
        'analyzeHeadless',
      ),
    )
  }
  candidates.push('analyzeHeadless') // PATH lookup

  for (const c of candidates) {
    if (c === 'analyzeHeadless') return c // let spawn resolve it
    try {
      await fs.access(c)
      return c
    } catch {
      /* try next */
    }
  }
  throw new Error(
    'disassemble ghidra: analyzeHeadless not found. Pass --ghidra-home <install>, ' +
      'set GHIDRA_INSTALL_DIR, or `brew install ghidra` and put it on PATH.',
  )
}

/**
 * Write a Jython post-script for the requested profile to a temp
 * file and return its path. These run inside the headless analyzer
 * with the standard Ghidra script API in scope.
 */
async function materializePostScript(
  profile: GhidraProfile,
  outputPath: string,
): Promise<string> {
  const body = SCRIPT_BODIES[profile](outputPath)
  const dir = await fs.mkdtemp(
    path.join(os.tmpdir(), 'task-ghidra-script-'),
  )
  const file = path.join(dir, `Export${capitalize(profile)}.py`)
  await fs.writeFile(file, body, 'utf8')
  return file
}

const HEADER = `# Auto-generated by @cluesurf/task — disassemble ghidra
# This script runs inside Ghidra's headless analyzer.
`

const SCRIPT_BODIES: Record<
  GhidraProfile,
  (out: string) => string
> = {
  functions: out =>
    HEADER +
    `
fm = currentProgram.getFunctionManager()
with open(${py(out)}, 'w') as fh:
    for f in fm.getFunctions(True):
        fh.write('%s\\t%d\\t%s\\n' % (
            f.getEntryPoint(), f.getBody().getNumAddresses(), f.getName()))
`,
  calls: out =>
    HEADER +
    `
fm = currentProgram.getFunctionManager()
with open(${py(out)}, 'w') as fh:
    fh.write('digraph G {\\n')
    for f in fm.getFunctions(True):
        src = f.getName().replace('"', "'")
        for callee in f.getCalledFunctions(monitor):
            dst = callee.getName().replace('"', "'")
            fh.write('  "%s" -> "%s";\\n' % (src, dst))
    fh.write('}\\n')
`,
  imports: out =>
    HEADER +
    `
st = currentProgram.getSymbolTable()
with open(${py(out)}, 'w') as fh:
    for s in st.getExternalSymbols():
        fh.write('%s\\t%s\\n' % (s.getName(), s.getParentNamespace().getName()))
`,
  exports: out =>
    HEADER +
    `
st = currentProgram.getSymbolTable()
with open(${py(out)}, 'w') as fh:
    for s in st.getSymbolIterator():
        if s.isExternalEntryPoint():
            fh.write('%s\\t%s\\n' % (s.getAddress(), s.getName()))
`,
  strings: out =>
    HEADER +
    `
listing = currentProgram.getListing()
with open(${py(out)}, 'w') as fh:
    for d in listing.getDefinedData(True):
        v = d.getValue()
        if v is not None and hasattr(v, 'toString'):
            fh.write('%s\\t%s\\n' % (d.getAddress(), v.toString()))
`,
}

function py(s: string): string {
  return `'${s.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`
}

function capitalize(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1)
}

