// AUTO-GENERATED by pnpm make:type. Do not edit.

import type { CliOption } from '~/code/tool/shared/console'

export const options: CliOption[] = [
  {
    "path": [
      "input",
      "file",
      "path"
    ],
    "long": "input-file-path",
    "short": "i",
    "like": "string",
    "list": false,
    "need": true
  },
  {
    "path": [
      "output",
      "file",
      "path"
    ],
    "long": "output-file-path",
    "short": "o",
    "like": "string",
    "list": false,
    "need": true
  },
  {
    "path": [
      "optimize"
    ],
    "long": "optimize",
    "like": "natural_number",
    "list": false,
    "need": false,
    "note": "Optimization level 1-3"
  },
  {
    "path": [
      "lossy"
    ],
    "long": "lossy",
    "like": "natural_number",
    "list": false,
    "need": false,
    "note": "Lossy quantization level (0 = lossless, 200 = most lossy)"
  },
  {
    "path": [
      "resize"
    ],
    "long": "resize",
    "like": "string",
    "list": false,
    "need": false,
    "note": "Resize output, e.g. 400x300 or _x300"
  },
  {
    "path": [
      "colors"
    ],
    "long": "colors",
    "like": "natural_number",
    "list": false,
    "need": false,
    "note": "Reduce palette to N colors (max 256)"
  }
]
