// AUTO-GENERATED by pnpm make:type. Do not edit.

import type { CliOption } from '~/code/tool/shared/console'

export const options: CliOption[] = [
  {
    "path": [
      "input",
      "file",
      "path"
    ],
    "long": "input-file-path",
    "short": "i",
    "like": "string",
    "list": false,
    "need": true
  },
  {
    "path": [
      "output",
      "file",
      "path"
    ],
    "long": "output-file-path",
    "short": "o",
    "like": "string",
    "list": false,
    "need": true
  },
  {
    "path": [
      "xmp"
    ],
    "long": "xmp",
    "like": "string",
    "list": false,
    "need": false,
    "note": "Optional XMP sidecar with develop parameters"
  },
  {
    "path": [
      "highQuality"
    ],
    "long": "high-quality",
    "like": "boolean",
    "list": false,
    "need": false,
    "note": "High-quality resampling (slower)"
  },
  {
    "path": [
      "upscale"
    ],
    "long": "upscale",
    "like": "boolean",
    "list": false,
    "need": false,
    "note": "Upscale output beyond the input pixel dimensions"
  }
]
