// AUTO-GENERATED by pnpm make:type. Do not edit.

import type { CliOption } from '~/code/tool/shared/console'

export const options: CliOption[] = [
  {
    "path": [
      "input",
      "file",
      "path"
    ],
    "long": "input-file-path",
    "short": "i",
    "like": "string",
    "list": false,
    "need": true
  },
  {
    "path": [
      "output",
      "file",
      "path"
    ],
    "long": "output-file-path",
    "short": "o",
    "like": "string",
    "list": false,
    "need": true
  },
  {
    "path": [
      "fps"
    ],
    "long": "fps",
    "like": "natural_number",
    "list": false,
    "need": false,
    "note": "Target framerate"
  },
  {
    "path": [
      "quality"
    ],
    "long": "quality",
    "like": "natural_number",
    "list": false,
    "need": false,
    "note": "Quality 1-100 (interpreted per output format)"
  },
  {
    "path": [
      "loop"
    ],
    "long": "loop",
    "like": "natural_number",
    "list": false,
    "need": false,
    "note": "Loop count (0 = infinite) for gif/apng/webp"
  },
  {
    "path": [
      "outputFormat"
    ],
    "long": "output-format",
    "like": "string",
    "list": false,
    "need": false,
    "note": "Output format override"
  }
]
