// AUTO-GENERATED by pnpm make:type. Do not edit.

import type { CliOption } from '~/code/tool/shared/console'

export const options: CliOption[] = [
  {
    "path": [
      "input",
      "file",
      "path"
    ],
    "long": "input-file-path",
    "short": "i",
    "like": "string",
    "list": false,
    "need": true
  },
  {
    "path": [
      "output",
      "file",
      "path"
    ],
    "long": "output-file-path",
    "short": "o",
    "like": "string",
    "list": false,
    "need": false
  },
  {
    "path": [
      "subtitles"
    ],
    "long": "subtitles",
    "short": "s",
    "like": "string",
    "list": false,
    "need": false,
    "note": "Path to a .srt / .vtt / .ass subtitle file"
  }
]
