// AUTO-GENERATED by pnpm make:type. Do not edit.

import type { CliOption } from '~/code/tool/shared/console'

export const options: CliOption[] = [
  {
    "path": [
      "input",
      "format"
    ],
    "long": "input-format",
    "like": "string",
    "list": false,
    "need": true
  },
  {
    "path": [
      "input",
      "file",
      "path"
    ],
    "long": "input-file-path",
    "like": "string",
    "list": false,
    "need": true
  },
  {
    "path": [
      "output",
      "format"
    ],
    "long": "output-format",
    "like": "string",
    "list": false,
    "need": true
  },
  {
    "path": [
      "output",
      "file",
      "path"
    ],
    "long": "output-file-path",
    "like": "string",
    "list": false,
    "need": false
  },
  {
    "path": [
      "pathScope"
    ],
    "long": "path-scope",
    "like": "string",
    "list": false,
    "need": false,
    "note": "This is used from the UI to scope file paths to a specific folder."
  },
  {
    "path": [
      "audioCodec"
    ],
    "long": "audio-codec",
    "like": "ffmpeg_codec_audio",
    "list": false,
    "need": false
  },
  {
    "path": [
      "videoCodec"
    ],
    "long": "video-codec",
    "like": "ffmpeg_codec_video",
    "list": false,
    "need": false
  },
  {
    "path": [
      "audioBitRate"
    ],
    "long": "audio-bit-rate",
    "like": "integer",
    "list": false,
    "need": false
  },
  {
    "path": [
      "videoBitRate"
    ],
    "long": "video-bit-rate",
    "like": "integer",
    "list": false,
    "need": false
  },
  {
    "path": [
      "frameRate"
    ],
    "long": "frame-rate",
    "short": "r",
    "like": "integer",
    "list": false,
    "need": false
  },
  {
    "path": [
      "fps"
    ],
    "long": "fps",
    "like": "integer",
    "list": false,
    "need": false
  },
  {
    "path": [
      "strict"
    ],
    "long": "strict",
    "like": "ffmpeg_strict_option",
    "list": false,
    "need": false
  },
  {
    "path": [
      "overwrite"
    ],
    "long": "overwrite",
    "short": "f",
    "like": "boolean",
    "list": false,
    "need": false
  },
  {
    "path": [
      "progress"
    ],
    "long": "progress",
    "short": "p",
    "like": "boolean",
    "list": false,
    "need": false
  },
  {
    "path": [
      "scaleWidth"
    ],
    "long": "scale-width",
    "like": "integer",
    "list": false,
    "need": false
  },
  {
    "path": [
      "scaleHeight"
    ],
    "long": "scale-height",
    "like": "integer",
    "list": false,
    "need": false
  },
  {
    "path": [
      "audioChannels"
    ],
    "long": "audio-channels",
    "like": "integer",
    "list": false,
    "need": false
  },
  {
    "path": [
      "audioSamplingFrequency"
    ],
    "long": "audio-sampling-frequency",
    "like": "integer",
    "list": false,
    "need": false
  },
  {
    "path": [
      "subtitleCodec"
    ],
    "long": "subtitle-codec",
    "like": "ffmpeg_codec_subtitle",
    "list": false,
    "need": false
  },
  {
    "path": [
      "rotation"
    ],
    "long": "rotation",
    "like": "decimal",
    "list": false,
    "need": false
  }
]
