// AUTO-GENERATED by pnpm make:type. Do not edit.

import type { CliOption } from '~/code/tool/shared/console'

export const options: CliOption[] = [
  {
    "path": [
      "input",
      "file",
      "path"
    ],
    "long": "input-file-path",
    "short": "i",
    "like": "string",
    "list": false,
    "need": true
  },
  {
    "path": [
      "output",
      "file",
      "path"
    ],
    "long": "output-file-path",
    "short": "o",
    "like": "string",
    "list": false,
    "need": true
  },
  {
    "path": [
      "title"
    ],
    "long": "title",
    "like": "string",
    "list": false,
    "need": false
  },
  {
    "path": [
      "artist"
    ],
    "long": "artist",
    "like": "string",
    "list": false,
    "need": false
  },
  {
    "path": [
      "album"
    ],
    "long": "album",
    "like": "string",
    "list": false,
    "need": false
  },
  {
    "path": [
      "albumArtist"
    ],
    "long": "album-artist",
    "like": "string",
    "list": false,
    "need": false
  },
  {
    "path": [
      "composer"
    ],
    "long": "composer",
    "like": "string",
    "list": false,
    "need": false
  },
  {
    "path": [
      "track"
    ],
    "long": "track",
    "like": "string",
    "list": false,
    "need": false
  },
  {
    "path": [
      "disc"
    ],
    "long": "disc",
    "like": "string",
    "list": false,
    "need": false
  },
  {
    "path": [
      "genre"
    ],
    "long": "genre",
    "like": "string",
    "list": false,
    "need": false
  },
  {
    "path": [
      "year"
    ],
    "long": "year",
    "like": "string",
    "list": false,
    "need": false
  },
  {
    "path": [
      "publisher"
    ],
    "long": "publisher",
    "like": "string",
    "list": false,
    "need": false
  },
  {
    "path": [
      "website"
    ],
    "long": "website",
    "like": "string",
    "list": false,
    "need": false
  },
  {
    "path": [
      "comment"
    ],
    "long": "comment",
    "like": "string",
    "list": false,
    "need": false
  },
  {
    "path": [
      "cover",
      "file",
      "path"
    ],
    "long": "cover-file-path",
    "like": "string",
    "list": false,
    "need": false
  },
  {
    "path": [
      "lyrics",
      "file",
      "path"
    ],
    "long": "lyrics-file-path",
    "like": "string",
    "list": false,
    "need": false
  },
  {
    "path": [
      "lyrics",
      "language"
    ],
    "long": "lyrics-language",
    "like": "string",
    "list": false,
    "need": false
  }
]
