// AUTO-GENERATED by pnpm make:type. Do not edit.

import type { CliOption } from '~/code/tool/shared/console'

export const options: CliOption[] = [
  {
    "path": [
      "input",
      "file",
      "path"
    ],
    "long": "input-file-path",
    "short": "i",
    "like": "string",
    "list": false,
    "need": true
  },
  {
    "path": [
      "output",
      "file",
      "path"
    ],
    "long": "output-file-path",
    "short": "o",
    "like": "string",
    "list": false,
    "need": true
  },
  {
    "path": [
      "outputFormat"
    ],
    "long": "output-format",
    "like": "string",
    "list": false,
    "need": false,
    "note": "Output format: svg, eps, dxf, or pdf"
  },
  {
    "path": [
      "colors"
    ],
    "long": "colors",
    "like": "natural_number",
    "list": false,
    "need": false,
    "note": "Number of colors to reduce to before tracing"
  },
  {
    "path": [
      "despeckleLevel"
    ],
    "long": "despeckle-level",
    "like": "natural_number",
    "list": false,
    "need": false,
    "note": "Despeckle level"
  }
]
