// AUTO-GENERATED by pnpm make:type. Do not edit.

import type { CliOption } from '~/code/tool/shared/console'

export const options: CliOption[] = [
  {
    "path": [
      "input",
      "file",
      "path"
    ],
    "long": "input-file-path",
    "short": "i",
    "like": "string",
    "list": false,
    "need": true
  },
  {
    "path": [
      "audio",
      "file",
      "path"
    ],
    "long": "audio-file-path",
    "short": "a",
    "like": "string",
    "list": false,
    "need": true
  },
  {
    "path": [
      "output",
      "file",
      "path"
    ],
    "long": "output-file-path",
    "short": "o",
    "like": "string",
    "list": false,
    "need": true
  },
  {
    "path": [
      "videoCodec"
    ],
    "long": "video-codec",
    "like": "string",
    "list": false,
    "need": false
  },
  {
    "path": [
      "audioCodec"
    ],
    "long": "audio-codec",
    "like": "string",
    "list": false,
    "need": false
  },
  {
    "path": [
      "audioBitrate"
    ],
    "long": "audio-bitrate",
    "like": "string",
    "list": false,
    "need": false
  },
  {
    "path": [
      "sampleRate"
    ],
    "long": "sample-rate",
    "like": "natural_number",
    "list": false,
    "need": false
  },
  {
    "path": [
      "pixelFormat"
    ],
    "long": "pixel-format",
    "like": "string",
    "list": false,
    "need": false
  },
  {
    "path": [
      "tune"
    ],
    "long": "tune",
    "like": "string",
    "list": false,
    "need": false
  }
]
