// AUTO-GENERATED by pnpm make:type. Do not edit.

import type { CliOption } from '~/code/tool/shared/console'

export const options: CliOption[] = [
  {
    "path": [
      "input",
      "file",
      "path"
    ],
    "long": "input-file-path",
    "short": "i",
    "like": "string",
    "list": false,
    "need": true
  },
  {
    "path": [
      "output",
      "file",
      "path"
    ],
    "long": "output-file-path",
    "short": "o",
    "like": "string",
    "list": false,
    "need": true
  },
  {
    "path": [
      "tool"
    ],
    "long": "tool",
    "like": "encrypt_file_tool",
    "list": false,
    "need": false,
    "note": "Backend (default: inferred from output extension)"
  },
  {
    "path": [
      "passphrase"
    ],
    "long": "passphrase",
    "like": "string",
    "list": false,
    "need": false
  },
  {
    "path": [
      "recipients"
    ],
    "long": "recipients",
    "like": "string",
    "list": true,
    "need": false
  },
  {
    "path": [
      "cipher"
    ],
    "long": "cipher",
    "like": "string",
    "list": false,
    "need": false,
    "note": "OpenSSL cipher (default aes-256-cbc)"
  },
  {
    "path": [
      "armor"
    ],
    "long": "armor",
    "like": "boolean",
    "list": false,
    "need": false,
    "note": "GPG ASCII armor"
  }
]
