// AUTO-GENERATED by pnpm make:type. Do not edit.

import type { CliOption } from '~/code/tool/shared/console'

export const options: CliOption[] = [
  {
    "path": [
      "input",
      "file",
      "path"
    ],
    "long": "input-file-path",
    "short": "i",
    "like": "string",
    "list": false,
    "need": true
  },
  {
    "path": [
      "output",
      "file",
      "path"
    ],
    "long": "output-file-path",
    "short": "o",
    "like": "string",
    "list": false,
    "need": true
  },
  {
    "path": [
      "start"
    ],
    "long": "start",
    "short": "s",
    "like": "string",
    "list": false,
    "need": false,
    "note": "Start offset (seconds or HH:MM:SS)"
  },
  {
    "path": [
      "end"
    ],
    "long": "end",
    "short": "e",
    "like": "string",
    "list": false,
    "need": false,
    "note": "End offset (seconds or HH:MM:SS)"
  },
  {
    "path": [
      "duration"
    ],
    "long": "duration",
    "short": "d",
    "like": "string",
    "list": false,
    "need": false,
    "note": "Alternate to --end: length of the cut"
  }
]
