// AUTO-GENERATED by pnpm make:type. Do not edit.

import type { CliOption } from '~/code/tool/shared/console'

export const options: CliOption[] = [
  {
    "path": [
      "pattern"
    ],
    "long": "pattern",
    "like": "string",
    "list": false,
    "need": false
  },
  {
    "path": [
      "path"
    ],
    "long": "path",
    "like": "string",
    "list": false,
    "need": false
  },
  {
    "path": [
      "name"
    ],
    "long": "name",
    "like": "boolean",
    "list": false,
    "need": false
  },
  {
    "path": [
      "type"
    ],
    "long": "type",
    "like": "string",
    "list": false,
    "need": false
  },
  {
    "path": [
      "files"
    ],
    "long": "files",
    "like": "boolean",
    "list": false,
    "need": false
  },
  {
    "path": [
      "count"
    ],
    "long": "count",
    "like": "boolean",
    "list": false,
    "need": false
  },
  {
    "path": [
      "hidden"
    ],
    "long": "hidden",
    "like": "boolean",
    "list": false,
    "need": false
  },
  {
    "path": [
      "ignoreCase"
    ],
    "long": "ignore-case",
    "like": "boolean",
    "list": false,
    "need": false
  },
  {
    "path": [
      "fixed"
    ],
    "long": "fixed",
    "like": "boolean",
    "list": false,
    "need": false
  },
  {
    "path": [
      "maxCount"
    ],
    "long": "max-count",
    "like": "natural_number",
    "list": false,
    "need": false
  }
]
