// AUTO-GENERATED by pnpm make:type. Do not edit.

import type { CliOption } from '~/code/tool/shared/console'

export const options: CliOption[] = [
  {
    "path": [
      "input",
      "file",
      "path"
    ],
    "long": "input-file-path",
    "short": "i",
    "like": "string",
    "list": false,
    "need": true
  },
  {
    "path": [
      "output",
      "file",
      "path"
    ],
    "long": "output-file-path",
    "short": "o",
    "like": "string",
    "list": false,
    "need": true
  },
  {
    "path": [
      "outputFormat"
    ],
    "long": "output-format",
    "like": "string",
    "list": false,
    "need": false,
    "note": "Output format: png, pdf, ps, eps, or svg"
  },
  {
    "path": [
      "width"
    ],
    "long": "width",
    "like": "natural_number",
    "list": false,
    "need": false,
    "note": "Output width in pixels"
  },
  {
    "path": [
      "height"
    ],
    "long": "height",
    "like": "natural_number",
    "list": false,
    "need": false,
    "note": "Output height in pixels"
  },
  {
    "path": [
      "dpi"
    ],
    "long": "dpi",
    "like": "natural_number",
    "list": false,
    "need": false,
    "note": "DPI for raster output. Default 96."
  },
  {
    "path": [
      "background"
    ],
    "long": "background",
    "like": "string",
    "list": false,
    "need": false,
    "note": "Background color (#fff, none, etc.)"
  }
]
