// AUTO-GENERATED by pnpm make:type. Do not edit.

import type { CliOption } from '~/code/tool/shared/console'

export const options: CliOption[] = [
  {
    "path": [
      "input",
      "file",
      "path"
    ],
    "long": "input-file-path",
    "short": "i",
    "like": "string",
    "list": false,
    "need": true
  },
  {
    "path": [
      "output",
      "file",
      "path"
    ],
    "long": "output-file-path",
    "short": "o",
    "like": "string",
    "list": false,
    "need": true
  },
  {
    "path": [
      "text"
    ],
    "long": "text",
    "short": "t",
    "like": "string",
    "list": false,
    "need": true,
    "note": "Text sample to render"
  },
  {
    "path": [
      "fontSize"
    ],
    "long": "font-size",
    "like": "natural_number",
    "list": false,
    "need": false,
    "note": "Font size in points (default: 128)"
  },
  {
    "path": [
      "features"
    ],
    "long": "features",
    "like": "string",
    "list": false,
    "need": false,
    "note": "OpenType features, e.g. \"+liga,-kern\""
  }
]
