// AUTO-GENERATED by pnpm make:type. Do not edit.

import type { CliOption } from '~/code/tool/shared/console'

export const options: CliOption[] = [
  {
    "path": [
      "input",
      "file",
      "path"
    ],
    "long": "input-file-path",
    "short": "i",
    "like": "string",
    "list": false,
    "need": true
  },
  {
    "path": [
      "output",
      "file",
      "path"
    ],
    "long": "output-file-path",
    "short": "o",
    "like": "string",
    "list": false,
    "need": true
  },
  {
    "path": [
      "target"
    ],
    "long": "target",
    "like": "string",
    "list": false,
    "need": false,
    "note": "Integrated loudness target in LUFS (default −16)"
  },
  {
    "path": [
      "peak"
    ],
    "long": "peak",
    "like": "string",
    "list": false,
    "need": false,
    "note": "True-peak ceiling in dBTP (default −1)"
  },
  {
    "path": [
      "range"
    ],
    "long": "range",
    "like": "string",
    "list": false,
    "need": false,
    "note": "Loudness range target in LU (default 11)"
  }
]
