// AUTO-GENERATED by pnpm make:type. Do not edit.

import type { CliOption } from '~/code/tool/shared/console'

export const options: CliOption[] = [
  {
    "path": [
      "input",
      "file",
      "path"
    ],
    "long": "input-file-path",
    "short": "i",
    "like": "string",
    "list": false,
    "need": true
  },
  {
    "path": [
      "output",
      "file",
      "path"
    ],
    "long": "output-file-path",
    "short": "o",
    "like": "string",
    "list": false,
    "need": true
  },
  {
    "path": [
      "quality"
    ],
    "long": "quality",
    "like": "natural_number",
    "list": false,
    "need": false,
    "note": "Quality 0-100. Ignored when lossless."
  },
  {
    "path": [
      "lossless"
    ],
    "long": "lossless",
    "like": "boolean",
    "list": false,
    "need": false,
    "note": "Use lossless codec"
  },
  {
    "path": [
      "delay"
    ],
    "long": "delay",
    "like": "natural_number",
    "list": false,
    "need": false,
    "note": "Frame delay in milliseconds"
  },
  {
    "path": [
      "loop"
    ],
    "long": "loop",
    "like": "natural_number",
    "list": false,
    "need": false,
    "note": "Loop count (0 = infinite)"
  }
]
