// AUTO-GENERATED by pnpm make:type. Do not edit.

import type { CliOption } from '~/code/tool/shared/console'

export const options: CliOption[] = [
  {
    "path": [
      "input",
      "file",
      "path"
    ],
    "long": "input-file-path",
    "short": "i",
    "like": "string",
    "list": false,
    "need": true
  },
  {
    "path": [
      "output",
      "file",
      "path"
    ],
    "long": "output-file-path",
    "short": "o",
    "like": "string",
    "list": false,
    "need": true
  },
  {
    "path": [
      "width"
    ],
    "long": "width",
    "short": "w",
    "like": "natural_number",
    "list": false,
    "need": false,
    "note": "Target width (preserves aspect if height omitted)"
  },
  {
    "path": [
      "height"
    ],
    "long": "height",
    "like": "natural_number",
    "list": false,
    "need": false,
    "note": "Target height"
  }
]
