// AUTO-GENERATED by pnpm make:type. Do not edit.

import type { CliOption } from '~/code/tool/shared/console'

export const options: CliOption[] = [
  {
    "path": [
      "input",
      "file",
      "path"
    ],
    "long": "input-file-path",
    "short": "i",
    "like": "string",
    "list": false,
    "need": true
  },
  {
    "path": [
      "output",
      "file",
      "path"
    ],
    "long": "output-file-path",
    "short": "o",
    "like": "string",
    "list": false,
    "need": true
  },
  {
    "path": [
      "outputFormat"
    ],
    "long": "output-format",
    "like": "string",
    "list": false,
    "need": false,
    "note": "Output format: tiff or ppm"
  },
  {
    "path": [
      "cameraWhiteBalance"
    ],
    "long": "camera-white-balance",
    "like": "boolean",
    "list": false,
    "need": false,
    "note": "Use camera white balance. Default true."
  },
  {
    "path": [
      "srgb"
    ],
    "long": "srgb",
    "like": "boolean",
    "list": false,
    "need": false,
    "note": "Apply sRGB output gamma. Default true."
  }
]
