// AUTO-GENERATED by pnpm make:type. Do not edit.

import type { CliOption } from '~/code/tool/shared/console'

export const options: CliOption[] = [
  {
    "path": [
      "input",
      "format"
    ],
    "long": "input-format",
    "like": "c_input_format",
    "list": false,
    "need": true
  },
  {
    "path": [
      "input",
      "file",
      "path"
    ],
    "long": "input-file-path",
    "like": "string",
    "list": false,
    "need": true
  },
  {
    "path": [
      "output",
      "format"
    ],
    "long": "output-format",
    "like": "backend_compilation_output",
    "list": false,
    "need": true
  },
  {
    "path": [
      "output",
      "file",
      "path"
    ],
    "long": "output-file-path",
    "like": "string",
    "list": false,
    "need": true
  },
  {
    "path": [
      "output",
      "syntax"
    ],
    "long": "output-syntax",
    "like": "assembly_syntax",
    "list": false,
    "need": false
  },
  {
    "path": [
      "output",
      "architecture"
    ],
    "long": "output-architecture",
    "like": "llvm_architecture",
    "list": false,
    "need": false
  },
  {
    "path": [
      "pathScope"
    ],
    "long": "path-scope",
    "like": "string",
    "list": false,
    "need": false,
    "note": "This is used from the UI to scope file paths to a specific folder."
  },
  {
    "path": [
      "optimizationLevel"
    ],
    "long": "optimization-level",
    "like": "llvm_optimization_level",
    "list": false,
    "need": false
  },
  {
    "path": [
      "fastMath"
    ],
    "long": "fast-math",
    "like": "boolean",
    "list": false,
    "need": false
  }
]
