// AUTO-GENERATED by pnpm make:type. Do not edit.

import type { CliOption } from '~/code/tool/shared/console'

export const options: CliOption[] = [
  {
    "path": [
      "input",
      "file",
      "path"
    ],
    "long": "input-file-path",
    "short": "i",
    "like": "string",
    "list": false,
    "need": true
  },
  {
    "path": [
      "output",
      "file",
      "path"
    ],
    "long": "output-file-path",
    "short": "o",
    "like": "string",
    "list": false,
    "need": true
  },
  {
    "path": [
      "delay"
    ],
    "long": "delay",
    "like": "natural_number",
    "list": false,
    "need": false,
    "note": "Frame delay in 1/100s. Default 10 (= 10 fps)."
  },
  {
    "path": [
      "skipDuplicates"
    ],
    "long": "skip-duplicates",
    "like": "boolean",
    "list": false,
    "need": false,
    "note": "Skip frames that are pixel-identical"
  }
]
