// AUTO-GENERATED by pnpm make:type. Do not edit.

import type { CliOption } from '~/code/tool/shared/console'

export const options: CliOption[] = [
  {
    "path": [
      "input",
      "file",
      "path"
    ],
    "long": "input-file-path",
    "short": "i",
    "like": "string",
    "list": false,
    "need": true
  },
  {
    "path": [
      "output",
      "file",
      "path"
    ],
    "long": "output-file-path",
    "short": "o",
    "like": "string",
    "list": false,
    "need": false
  },
  {
    "path": [
      "profile"
    ],
    "long": "profile",
    "like": "string",
    "list": false,
    "need": false
  },
  {
    "path": [
      "script"
    ],
    "long": "script",
    "like": "string",
    "list": false,
    "need": false
  },
  {
    "path": [
      "ghidraHome"
    ],
    "long": "ghidra-home",
    "like": "string",
    "list": false,
    "need": false
  },
  {
    "path": [
      "projectDir"
    ],
    "long": "project-dir",
    "like": "string",
    "list": false,
    "need": false
  },
  {
    "path": [
      "projectName"
    ],
    "long": "project-name",
    "like": "string",
    "list": false,
    "need": false
  },
  {
    "path": [
      "keepProject"
    ],
    "long": "keep-project",
    "like": "boolean",
    "list": false,
    "need": false
  },
  {
    "path": [
      "verbose"
    ],
    "long": "verbose",
    "like": "boolean",
    "list": false,
    "need": false
  },
  {
    "path": [
      "quiet"
    ],
    "long": "quiet",
    "like": "boolean",
    "list": false,
    "need": false
  }
]
