// AUTO-GENERATED by pnpm make:type. Do not edit.

import type { CliOption } from '~/code/tool/shared/console'

export const options: CliOption[] = [
  {
    "path": [
      "input",
      "file",
      "path"
    ],
    "long": "input-file-path",
    "short": "i",
    "like": "string",
    "list": false,
    "need": true
  },
  {
    "path": [
      "output",
      "file",
      "path"
    ],
    "long": "output-file-path",
    "short": "o",
    "like": "string",
    "list": false,
    "need": false
  },
  {
    "path": [
      "tag"
    ],
    "long": "tag",
    "like": "string",
    "list": true,
    "need": false,
    "note": "ExifTool tag names to strip"
  },
  {
    "path": [
      "preset"
    ],
    "long": "preset",
    "like": "string",
    "list": true,
    "need": false,
    "note": "Preset groups: gps, device, user"
  },
  {
    "path": [
      "overwrite"
    ],
    "long": "overwrite",
    "like": "boolean",
    "list": false,
    "need": false,
    "note": "Edit the input file in place"
  }
]
