import makeTree from '@cluesurf/form/make'
import type { Load } from '@cluesurf/form'
import * as MESH from '~/code/base'
import NAME from '~/code/base/name'
import fsp from 'fs/promises'
import path from 'path'
import { camelCase, upperFirst } from 'lodash'

const toPascalCase = (str: string): string => upperFirst(camelCase(str))

void make()

async function make(): Promise<void> {
  const options: Load = {
    name: NAME,
    mesh: MESH,
    link: MESH,
    testLink: '~/code/form/code',
    codeLink: './code',
  }

  const tree = await makeTree(options)

  for (const name in tree.form) {
    const link = name.replace('~', '.')
    const base = path.dirname(link)
    await fsp.mkdir(base, { recursive: true })
    await fsp.writeFile(`${link}.ts`, tree.form[name] as string)
  }

  for (const name in tree.take) {
    const link = name.replace('~', '.')
    const base = path.dirname(link)
    await fsp.mkdir(base, { recursive: true })
    await fsp.writeFile(`${link}.ts`, tree.take[name] as string)
  }

  for (const name in tree.base) {
    const link = name.replace('~', '.')
    const base = path.dirname(link)
    await fsp.mkdir(base, { recursive: true })
    await fsp.writeFile(`${link}.ts`, tree.base[name] as string)
  }

  await writeTaskInterface('node')
  await writeTaskInterface('browser')
}

type Runtime = 'node' | 'browser'

type Overload = {
  action: string
  inputType: string
  outputType: string
  inputImport: string
  outputImport: string
}

async function writeTaskInterface(runtime: Runtime): Promise<void> {
  const inputSuffix = `_${runtime}_input`
  const outputSuffix = `_${runtime}_output`
  const overloads: Array<Overload> = []

  const mesh = MESH as unknown as Record<string, { save?: string }>

  for (const formName of Object.keys(mesh)) {
    if (!formName.endsWith(inputSuffix)) continue

    const baseName = formName.slice(0, -inputSuffix.length)
    const outputName = `${baseName}${outputSuffix}`

    const inputForm = mesh[formName]
    const outputForm = mesh[outputName]

    if (!inputForm?.save || !outputForm?.save) continue

    const action = baseName.split('_')[0]
    if (!action) continue

    overloads.push({
      action,
      inputType: toPascalCase(formName),
      outputType: toPascalCase(outputName),
      inputImport: inputForm.save,
      outputImport: outputForm.save,
    })
  }

  overloads.sort((a, b) => {
    if (a.action !== b.action) return a.action.localeCompare(b.action)
    return a.inputType.localeCompare(b.inputType)
  })

  const imports = collectImports(overloads)
  const importLines: Array<string> = []
  for (const [importPath, names] of imports) {
    const sorted = Array.from(names).sort()
    importLines.push(
      `import type {\n  ${sorted.join(',\n  ')},\n} from '${importPath}'`,
    )
  }

  const methodsByAction = new Map<string, Array<Overload>>()
  for (const overload of overloads) {
    const bucket = methodsByAction.get(overload.action) ?? []
    bucket.push(overload)
    methodsByAction.set(overload.action, bucket)
  }

  const methodLines: Array<string> = []
  for (const action of Array.from(methodsByAction.keys()).sort()) {
    const bucket = methodsByAction.get(action)!
    for (const overload of bucket) {
      methodLines.push(
        `  ${action}(input: ${overload.inputType}): Promise<${overload.outputType}>`,
      )
    }
    methodLines.push('')
  }

  const header = `// AUTO-GENERATED by pnpm make:type. Do not edit.\n`
  const body = [
    header,
    importLines.join('\n'),
    '',
    `export interface Task {`,
    methodLines.join('\n').trimEnd(),
    `}`,
    '',
  ].join('\n')

  const outPath = path.join('.', 'code', 'form', 'task', `${runtime}.ts`)
  await fsp.mkdir(path.dirname(outPath), { recursive: true })
  await fsp.writeFile(outPath, body)
}

function collectImports(
  overloads: Array<Overload>,
): Map<string, Set<string>> {
  const imports = new Map<string, Set<string>>()
  for (const overload of overloads) {
    addImport(imports, overload.inputImport, overload.inputType)
    addImport(imports, overload.outputImport, overload.outputType)
  }
  return imports
}

function addImport(
  imports: Map<string, Set<string>>,
  path: string,
  name: string,
): void {
  const bucket = imports.get(path) ?? new Set<string>()
  bucket.add(name)
  imports.set(path, bucket)
}

