import makeTree from '@cluesurf/form/make'
import type { Load } from '@cluesurf/form'
import * as MESH from '~/code/base'
import NAME from '~/code/base/name'
import fsp from 'fs/promises'
import path from 'path'
import { camelCase, upperFirst } from 'lodash'

const toPascalCase = (str: string): string => upperFirst(camelCase(str))

void make()

async function make(): Promise<void> {
  const options: Load = {
    name: NAME,
    mesh: MESH as unknown as Load['mesh'],
    link: MESH as unknown as Load['link'],
    testLink: '~/code/form/code',
    codeLink: './code',
  }

  const tree = await makeTree(options)

  for (const name in tree.form) {
    const link = name.replace('~', '.')
    const base = path.dirname(link)
    await fsp.mkdir(base, { recursive: true })
    await fsp.writeFile(`${link}.ts`, tree.form[name] as string)
  }

  for (const name in tree.take) {
    const link = name.replace('~', '.')
    const base = path.dirname(link)
    await fsp.mkdir(base, { recursive: true })
    await fsp.writeFile(`${link}.ts`, tree.take[name] as string)
  }

  for (const name in tree.base) {
    const link = name.replace('~', '.')
    const base = path.dirname(link)
    await fsp.mkdir(base, { recursive: true })
    await fsp.writeFile(`${link}.ts`, tree.base[name] as string)
  }

  await writeTaskInterface('node')
  await writeTaskInterface('browser')
}

// Legacy barrels at `code/form/{shared,node,browser}/` were
// removed — they eagerly pulled in every parser + type, defeating
// the per-action lazy-load design. The codemod
// `make/rewrite-imports.ts` migrated call sites to per-module
// imports. Kept here as a dormant helper only in case a bulk
// re-audit is ever needed; not invoked from `make()`.
async function writeLegacyBarrels(): Promise<void> {
  const objectDir = path.join('.', 'code', 'form', 'object')
  const actionDir = path.join('.', 'code', 'form', 'action')

  const objectIndexPaths = await listLeafFiles({
    root: objectDir,
    fileName: 'index.ts',
  })
  const objectTakePaths = await listLeafFiles({
    root: objectDir,
    fileName: 'take.ts',
  })
  const actionNodeIndexPaths = await listFilesWithParent({
    root: actionDir,
    parent: 'node',
    fileName: 'index.ts',
  })
  const actionNodeTakePaths = await listFilesWithParent({
    root: actionDir,
    parent: 'node',
    fileName: 'take.ts',
  })
  const actionBrowserIndexPaths = await listFilesWithParent({
    root: actionDir,
    parent: 'browser',
    fileName: 'index.ts',
  })
  const actionBrowserTakePaths = await listFilesWithParent({
    root: actionDir,
    parent: 'browser',
    fileName: 'take.ts',
  })
  const actionCliIndexPaths = await listFilesWithParent({
    root: actionDir,
    parent: 'cli',
    fileName: 'index.ts',
  })
  const actionCliTakePaths = await listFilesWithParent({
    root: actionDir,
    parent: 'cli',
    fileName: 'take.ts',
  })
  const actionSharedIndexPaths = await listFilesWithParent({
    root: actionDir,
    parent: 'shared',
    fileName: 'index.ts',
  })
  const actionSharedTakePaths = await listFilesWithParent({
    root: actionDir,
    parent: 'shared',
    fileName: 'take.ts',
  })

  const header =
    `// AUTO-GENERATED by pnpm make:type. Do not edit.\n` +
    `// Legacy aggregator barrel. Migrate callers to per-action imports.\n\n`

  const toSpec = (absPath: string): string =>
    '~/' + absPath.replace(/^\.\//, '').replace(/\.ts$/, '')

  const writeBarrel = async ({
    outPath,
    specs,
  }: {
    outPath: string
    specs: string[]
  }): Promise<void> => {
    const unique = Array.from(new Set(specs)).sort()
    const body = header + unique.map(s => `export * from '${s}'`).join('\n') + '\n'
    await fsp.mkdir(path.dirname(outPath), { recursive: true })
    await fsp.writeFile(outPath, body)
  }

  // Legacy barrels re-export BOTH sides (types from `index.ts` and
  // parsers/records from `take.ts`) in one file. Callers historically
  // imported e.g. `CompileCppNodeInput` (type from index.ts) AND
  // `CompileCppNodeInputParser` (zod schema from take.ts) from the
  // same `~/code/form/node/take` path, so every barrel merges both.
  const sharedSpecs = [
    ...objectIndexPaths,
    ...objectTakePaths,
    ...actionCliIndexPaths,
    ...actionCliTakePaths,
    ...actionSharedIndexPaths,
    ...actionSharedTakePaths,
  ]
  const nodeSpecs = [
    ...sharedSpecs,
    ...actionNodeIndexPaths,
    ...actionNodeTakePaths,
  ]
  const browserSpecs = [
    ...sharedSpecs,
    ...actionBrowserIndexPaths,
    ...actionBrowserTakePaths,
  ]

  await writeBarrel({
    outPath: path.join('.', 'code', 'form', 'shared', 'index.ts'),
    specs: sharedSpecs.map(toSpec),
  })
  await writeBarrel({
    outPath: path.join('.', 'code', 'form', 'shared', 'take.ts'),
    specs: sharedSpecs.map(toSpec),
  })
  await writeBarrel({
    outPath: path.join('.', 'code', 'form', 'node', 'index.ts'),
    specs: nodeSpecs.map(toSpec),
  })
  await writeBarrel({
    outPath: path.join('.', 'code', 'form', 'node', 'take.ts'),
    specs: nodeSpecs.map(toSpec),
  })
  await writeBarrel({
    outPath: path.join('.', 'code', 'form', 'node', 'data.ts'),
    specs: nodeSpecs.map(toSpec),
  })
  await writeBarrel({
    outPath: path.join('.', 'code', 'form', 'browser', 'index.ts'),
    specs: browserSpecs.map(toSpec),
  })
  await writeBarrel({
    outPath: path.join('.', 'code', 'form', 'browser', 'take.ts'),
    specs: browserSpecs.map(toSpec),
  })
}

async function listLeafFiles({
  root,
  fileName,
}: {
  root: string
  fileName: string
}): Promise<string[]> {
  const entries = await safeReadDir(root)
  const results: string[] = []
  for (const entry of entries) {
    if (!entry.isDirectory()) continue
    const candidate = path.join(root, entry.name, fileName)
    try {
      await fsp.stat(candidate)
      results.push(candidate)
    } catch {
      // no-op: entry has no matching file
    }
  }
  return results
}

async function listFilesWithParent({
  root,
  parent,
  fileName,
}: {
  root: string
  parent: string
  fileName: string
}): Promise<string[]> {
  const results: string[] = []
  await walk({
    dir: root,
    visit: async absPath => {
      if (path.basename(absPath) !== fileName) return
      if (path.basename(path.dirname(absPath)) !== parent) return
      results.push(absPath)
    },
  })
  return results
}

async function walk({
  dir,
  visit,
}: {
  dir: string
  visit: (absPath: string) => Promise<void>
}): Promise<void> {
  const entries = await safeReadDir(dir)
  for (const entry of entries) {
    const absPath = path.join(dir, entry.name)
    if (entry.isDirectory()) {
      await walk({ dir: absPath, visit })
    } else if (entry.isFile()) {
      await visit(absPath)
    }
  }
}

async function safeReadDir(
  dir: string,
): Promise<{ name: string; isDirectory(): boolean; isFile(): boolean }[]> {
  try {
    return await fsp.readdir(dir, { withFileTypes: true })
  } catch {
    return []
  }
}

type Runtime = 'node' | 'browser'

type Overload = {
  action: string
  inputType: string
  outputType: string
  inputImport: string
  outputImport: string
}

async function writeTaskInterface(runtime: Runtime): Promise<void> {
  const inputSuffix = `_${runtime}_input`
  const outputSuffix = `_${runtime}_output`
  const overloads: Array<Overload> = []

  const mesh = MESH as unknown as Record<string, { save?: string }>

  for (const formName of Object.keys(mesh)) {
    if (!formName.endsWith(inputSuffix)) continue

    const baseName = formName.slice(0, -inputSuffix.length)
    const outputName = `${baseName}${outputSuffix}`

    const inputForm = mesh[formName]
    const outputForm = mesh[outputName]

    if (!inputForm?.save || !outputForm?.save) continue

    const action = baseName.split('_')[0]
    if (!action) continue

    overloads.push({
      action,
      inputType: toPascalCase(formName),
      outputType: toPascalCase(outputName),
      inputImport: inputForm.save,
      outputImport: outputForm.save,
    })
  }

  overloads.sort((a, b) => {
    if (a.action !== b.action) return a.action.localeCompare(b.action)
    return a.inputType.localeCompare(b.inputType)
  })

  const imports = collectImports(overloads)
  const importLines: Array<string> = []
  for (const [importPath, names] of imports) {
    const sorted = Array.from(names).sort()
    importLines.push(
      `import type {\n  ${sorted.join(',\n  ')},\n} from '${importPath}'`,
    )
  }

  const methodsByAction = new Map<string, Array<Overload>>()
  for (const overload of overloads) {
    const bucket = methodsByAction.get(overload.action) ?? []
    bucket.push(overload)
    methodsByAction.set(overload.action, bucket)
  }

  const methodLines: Array<string> = []
  const unionLines: Array<string> = []

  for (const action of Array.from(methodsByAction.keys()).sort()) {
    const bucket = methodsByAction.get(action)!
    for (const overload of bucket) {
      methodLines.push(
        `  ${action}(input: ${overload.inputType}): Promise<${overload.outputType}>`,
      )
    }
    methodLines.push('')

    const actionPascal = toPascalCase(action)
    const runtimePascal = toPascalCase(runtime)
    const inputUnion = bucket.map(o => o.inputType).join('\n  | ')
    const outputUnion = bucket.map(o => o.outputType).join('\n  | ')
    unionLines.push(
      `export type ${actionPascal}${runtimePascal}Input =\n  | ${inputUnion}`,
    )
    unionLines.push(
      `export type ${actionPascal}${runtimePascal}Output =\n  | ${outputUnion}`,
    )
    unionLines.push('')
  }

  const header = `// AUTO-GENERATED by pnpm make:type. Do not edit.\n`
  const body = [
    header,
    importLines.join('\n'),
    '',
    `export interface TaskSurface {`,
    methodLines.join('\n').trimEnd(),
    `}`,
    '',
    unionLines.join('\n').trimEnd(),
    '',
  ].join('\n')

  const outPath = path.join('.', 'code', 'form', 'export', `${runtime}.ts`)
  await fsp.mkdir(path.dirname(outPath), { recursive: true })
  await fsp.writeFile(outPath, body)
}

function collectImports(
  overloads: Array<Overload>,
): Map<string, Set<string>> {
  const imports = new Map<string, Set<string>>()
  for (const overload of overloads) {
    addImport(imports, overload.inputImport, overload.inputType)
    addImport(imports, overload.outputImport, overload.outputType)
  }
  return imports
}

function addImport(
  imports: Map<string, Set<string>>,
  path: string,
  name: string,
): void {
  const bucket = imports.get(path) ?? new Set<string>()
  bucket.add(name)
  imports.set(path, bucket)
}

