import makeTree from '@cluesurf/form/make'
import type { Load, Form } from '@cluesurf/form'
import * as MESH from '~/code/base'
import NAME from '~/code/base/name'
import {
  collectCliOptions,
  type CliOption,
} from '~/code/tool/shared/console'
import fsp from 'fs/promises'
import path from 'path'
import { camelCase, upperFirst } from 'lodash'

const toPascalCase = (str: string): string => upperFirst(camelCase(str))

void make()

async function make(): Promise<void> {
  const options: Load = {
    name: NAME,
    mesh: MESH as unknown as Load['mesh'],
    link: MESH as unknown as Load['link'],
    testLink: '~/code/form/code',
    codeLink: './code',
  }

  const tree = await makeTree(options)

  for (const name in tree.form) {
    const link = name.replace('~', '.')
    const base = path.dirname(link)
    await fsp.mkdir(base, { recursive: true })
    await fsp.writeFile(`${link}.ts`, tree.form[name]!)
  }

  for (const name in tree.take) {
    const link = name.replace('~', '.')
    const base = path.dirname(link)
    await fsp.mkdir(base, { recursive: true })
    await fsp.writeFile(`${link}.ts`, tree.take[name]!)
  }

  for (const name in tree.base) {
    const link = name.replace('~', '.')
    const base = path.dirname(link)
    await fsp.mkdir(base, { recursive: true })
    await fsp.writeFile(`${link}.ts`, tree.base[name]!)
  }

  await writeTaskInterface('node')
  await writeTaskInterface('browser')
  await writeConsoleOptions()
}

async function writeConsoleOptions(): Promise<void> {
  const mesh = MESH as unknown as Record<string, Form>
  const names = await collectConsoleFormNames()
  const manifest: Record<string, string> = {}

  for (const name of names) {
    const form = mesh[name]
    if (!form || form.form !== 'form') continue
    const save = (form as { save?: string }).save
    if (!save) continue

    const options = collectCliOptions(mesh as never, form as never)

    const saveDir = save.replace(/^~/, '.')
    const baseDir = saveDir.endsWith('/cli')
      ? saveDir.slice(0, -'/cli'.length)
      : saveDir
    const outPath = path.join(baseDir, 'console', 'options.ts')
    const body = renderConsoleOptionsFile(options)
    await fsp.mkdir(path.dirname(outPath), { recursive: true })
    await fsp.writeFile(outPath, body)

    // Import path consoles use: strip leading `./code/` and convert
    // to the `~/code/...` alias, without extension.
    const importPath =
      '~/' +
      path
        .join(baseDir, 'console', 'options')
        .replace(/^\.\//, '')
        .split(path.sep)
        .join('/')
    manifest[name] = importPath
  }

  const manifestPath = path.join(
    '.',
    'code',
    'form',
    'action',
    'console-options.json',
  )
  await fsp.mkdir(path.dirname(manifestPath), { recursive: true })
  await fsp.writeFile(manifestPath, JSON.stringify(manifest, null, 2))
}

async function collectConsoleFormNames(): Promise<Set<string>> {
  const names = new Set<string>()
  const root = path.join('.', 'code', 'call')
  await walkConsoleFiles(root, names)
  return names
}

async function walkConsoleFiles(
  dir: string,
  names: Set<string>,
): Promise<void> {
  const entries = await fsp.readdir(dir, { withFileTypes: true })
  for (const entry of entries) {
    const p = path.join(dir, entry.name)
    if (entry.isDirectory()) {
      await walkConsoleFiles(p, names)
      continue
    }
    if (entry.name !== 'console.ts') continue
    const src = await fsp.readFile(p, 'utf8')
    const match = src.match(/formName:\s*['\"]([a-z0-9_]+)['\"]/)
    if (match && match[1]) names.add(match[1])
    for (const m of src.matchAll(
      /\(MESH as any\)\.([a-z0-9_]+)/g,
    )) {
      if (m[1]) names.add(m[1])
    }
  }
}

function renderConsoleOptionsFile(options: CliOption[]): string {
  const header = `// AUTO-GENERATED by pnpm make:type. Do not edit.\n`
  const body = JSON.stringify(options, null, 2)
  return `${header}
import type { CliOption } from '~/code/tool/shared/console'

export const options: CliOption[] = ${body}
`
}

type Runtime = 'node' | 'browser'

type Overload = {
  action: string
  inputType: string
  outputType: string
  inputImport: string
  outputImport: string
}

async function writeTaskInterface(runtime: Runtime): Promise<void> {
  const inputSuffix = `_${runtime}_input`
  const outputSuffix = `_${runtime}_output`
  const overloads: Array<Overload> = []

  const mesh = MESH as unknown as Record<string, { save?: string }>

  for (const formName of Object.keys(mesh)) {
    if (!formName.endsWith(inputSuffix)) continue

    const baseName = formName.slice(0, -inputSuffix.length)
    const outputName = `${baseName}${outputSuffix}`

    const inputForm = mesh[formName]
    const outputForm = mesh[outputName]

    if (!inputForm?.save || !outputForm?.save) continue

    const action = baseName.split('_')[0]
    if (!action) continue

    overloads.push({
      action,
      inputType: toPascalCase(formName),
      outputType: toPascalCase(outputName),
      inputImport: inputForm.save,
      outputImport: outputForm.save,
    })
  }

  overloads.sort((a, b) => {
    if (a.action !== b.action) return a.action.localeCompare(b.action)
    return a.inputType.localeCompare(b.inputType)
  })

  const imports = collectImports(overloads)
  const importLines: Array<string> = []
  for (const [importPath, names] of imports) {
    const sorted = Array.from(names).sort()
    importLines.push(
      `import type {\n  ${sorted.join(',\n  ')},\n} from '${importPath}'`,
    )
  }

  const methodsByAction = new Map<string, Array<Overload>>()
  for (const overload of overloads) {
    const bucket = methodsByAction.get(overload.action) ?? []
    bucket.push(overload)
    methodsByAction.set(overload.action, bucket)
  }

  const methodLines: Array<string> = []
  const unionLines: Array<string> = []

  for (const action of Array.from(methodsByAction.keys()).sort()) {
    const bucket = methodsByAction.get(action)!
    for (const overload of bucket) {
      methodLines.push(
        `  ${action}(input: ${overload.inputType}): Promise<${overload.outputType}>`,
      )
    }
    methodLines.push('')

    const actionPascal = toPascalCase(action)
    const runtimePascal = toPascalCase(runtime)
    const inputUnion = bucket.map(o => o.inputType).join('\n  | ')
    const outputUnion = bucket.map(o => o.outputType).join('\n  | ')
    unionLines.push(
      `export type ${actionPascal}${runtimePascal}Input =\n  | ${inputUnion}`,
    )
    unionLines.push(
      `export type ${actionPascal}${runtimePascal}Output =\n  | ${outputUnion}`,
    )
    unionLines.push('')
  }

  const header = `// AUTO-GENERATED by pnpm make:type. Do not edit.\n`
  const body = [
    header,
    importLines.join('\n'),
    '',
    `export interface TaskSurface {`,
    methodLines.join('\n').trimEnd(),
    `}`,
    '',
    unionLines.join('\n').trimEnd(),
    '',
  ].join('\n')

  const outPath = path.join(
    '.',
    'code',
    'form',
    'export',
    `${runtime}.ts`,
  )
  await fsp.mkdir(path.dirname(outPath), { recursive: true })
  await fsp.writeFile(outPath, body)
}

function collectImports(
  overloads: Array<Overload>,
): Map<string, Set<string>> {
  const imports = new Map<string, Set<string>>()
  for (const overload of overloads) {
    addImport(imports, overload.inputImport, overload.inputType)
    addImport(imports, overload.outputImport, overload.outputType)
  }
  return imports
}

function addImport(
  imports: Map<string, Set<string>>,
  path: string,
  name: string,
): void {
  const bucket = imports.get(path) ?? new Set<string>()
  bucket.add(name)
  imports.set(path, bucket)
}
