// AUTO-GENERATED by pnpm make:type. Do not edit.

import type {
  CompileCBrowserInput,
  CompileCBrowserOutput,
} from '~/code/form/action/compile/code/c/browser'
import type {
  CompileCppBrowserInput,
  CompileCppBrowserOutput,
} from '~/code/form/action/compile/code/cpp/browser'
import type {
  CompileRustBrowserInput,
  CompileRustBrowserOutput,
} from '~/code/form/action/compile/code/rust/browser'
import type {
  CompileSwiftBrowserInput,
  CompileSwiftBrowserOutput,
} from '~/code/form/action/compile/code/swift/browser'
import type {
  CompileWastBrowserInput,
  CompileWastBrowserOutput,
} from '~/code/form/action/compile/code/wast/browser'
import type {
  ConvertArchiveBrowserInput,
  ConvertArchiveBrowserOutput,
} from '~/code/form/action/convert/archive/browser'
import type {
  ConvertDataBrowserInput,
  ConvertDataBrowserOutput,
} from '~/code/form/action/convert/data/browser'
import type {
  ConvertDocumentWithCalibreBrowserInput,
  ConvertDocumentWithCalibreBrowserOutput,
} from '~/code/form/action/convert/calibre/browser'
import type {
  ConvertDocumentWithEnscriptBrowserInput,
  ConvertDocumentWithEnscriptBrowserOutput,
} from '~/code/form/action/convert/enscript/browser'
import type {
  ConvertDocumentWithJupyterBrowserInput,
  ConvertDocumentWithJupyterBrowserOutput,
} from '~/code/form/action/convert/jupyter/browser'
import type {
  ConvertDocumentWithLibreOfficeBrowserInput,
  ConvertDocumentWithLibreOfficeBrowserOutput,
} from '~/code/form/action/convert/libre-office/browser'
import type {
  ConvertDocumentWithPandocBrowserInput,
  ConvertDocumentWithPandocBrowserOutput,
} from '~/code/form/action/convert/pandoc/browser'
import type {
  ConvertFontWithFontForgeBrowserInput,
  ConvertFontWithFontForgeBrowserOutput,
} from '~/code/form/action/convert/font-forge/browser'
import type {
  ConvertHtmlWithPuppeteerBrowserInput,
  ConvertHtmlWithPuppeteerBrowserOutput,
  ConvertMarkdownWithPuppeteerBrowserInput,
  ConvertMarkdownWithPuppeteerBrowserOutput,
  ConvertTxtWithPuppeteerBrowserInput,
  ConvertTxtWithPuppeteerBrowserOutput,
} from '~/code/form/action/convert/puppeteer/browser'
import type {
  ConvertImageWithImageMagickBrowserInput,
  ConvertImageWithImageMagickBrowserOutput,
} from '~/code/form/action/convert/imagemagick/browser'
import type {
  ConvertImageWithInkscapeBrowserInput,
  ConvertImageWithInkscapeBrowserOutput,
} from '~/code/form/action/convert/inkscape/browser'
import type {
  ConvertLatexToPngBrowserInput,
  ConvertLatexToPngBrowserOutput,
} from '~/code/form/action/convert/latex-to-png/browser'
import type {
  ConvertLatexWithPdfLatexBrowserInput,
  ConvertLatexWithPdfLatexBrowserOutput,
} from '~/code/form/action/convert/pdf-latex/browser'
import type {
  ConvertParquetBrowserInput,
  ConvertParquetBrowserOutput,
} from '~/code/form/action/convert/parquet/browser'
import type {
  ConvertVideoWithFfmpegBrowserInput,
  ConvertVideoWithFfmpegBrowserOutput,
} from '~/code/form/action/convert/ffmpeg/browser'
import type {
  DecryptFileBrowserInput,
  DecryptFileBrowserOutput,
} from '~/code/form/action/decrypt/file/browser'
import type {
  DisassembleDotnetBrowserInput,
  DisassembleDotnetBrowserOutput,
} from '~/code/form/action/disassemble/dotnet/browser'
import type {
  DisassembleGhidraBrowserInput,
  DisassembleGhidraBrowserOutput,
} from '~/code/form/action/disassemble/ghidra/browser'
import type {
  DisassembleJvmBrowserInput,
  DisassembleJvmBrowserOutput,
} from '~/code/form/action/disassemble/jvm/browser'
import type {
  DisassembleRadareBrowserInput,
  DisassembleRadareBrowserOutput,
} from '~/code/form/action/disassemble/radare/browser'
import type {
  DisassembleWasmBrowserInput,
  DisassembleWasmBrowserOutput,
} from '~/code/form/action/disassemble/wasm/browser'
import type {
  EncryptFileBrowserInput,
  EncryptFileBrowserOutput,
} from '~/code/form/action/encrypt/file/browser'
import type {
  FormatAssemblyBrowserInput,
  FormatAssemblyBrowserOutput,
  FormatCodeWithClangFormatBrowserInput,
  FormatCodeWithClangFormatBrowserOutput,
  FormatKotlinBrowserInput,
  FormatKotlinBrowserOutput,
  FormatPythonBrowserInput,
  FormatPythonBrowserOutput,
  FormatRustBrowserInput,
  FormatRustBrowserOutput,
  FormatSwiftBrowserInput,
  FormatSwiftBrowserOutput,
} from '~/code/form/action/format/code/browser'
import type {
  RemoveExifBrowserInput,
  RemoveExifBrowserOutput,
} from '~/code/form/action/remove/exif/browser'
import type {
  RemovePasswordBrowserInput,
  RemovePasswordBrowserOutput,
} from '~/code/form/action/remove/password/browser'
import type {
  RemoveProfileBrowserInput,
  RemoveProfileBrowserOutput,
} from '~/code/form/action/remove/profile/browser'
import type {
  RemoveSubtitlesBrowserInput,
  RemoveSubtitlesBrowserOutput,
} from '~/code/form/action/remove/subtitles/browser'
import type {
  RemoveTransparencyBrowserInput,
  RemoveTransparencyBrowserOutput,
} from '~/code/form/action/remove/transparency/browser'
import type {
  SanitizeHtmlBrowserInput,
  SanitizeHtmlBrowserOutput,
} from '~/code/form/action/sanitize/code/browser'

export interface TaskSurface {
  compile(input: CompileCBrowserInput): Promise<CompileCBrowserOutput>
  compile(input: CompileCppBrowserInput): Promise<CompileCppBrowserOutput>
  compile(input: CompileRustBrowserInput): Promise<CompileRustBrowserOutput>
  compile(input: CompileSwiftBrowserInput): Promise<CompileSwiftBrowserOutput>
  compile(input: CompileWastBrowserInput): Promise<CompileWastBrowserOutput>

  convert(input: ConvertArchiveBrowserInput): Promise<ConvertArchiveBrowserOutput>
  convert(input: ConvertDataBrowserInput): Promise<ConvertDataBrowserOutput>
  convert(input: ConvertDocumentWithCalibreBrowserInput): Promise<ConvertDocumentWithCalibreBrowserOutput>
  convert(input: ConvertDocumentWithEnscriptBrowserInput): Promise<ConvertDocumentWithEnscriptBrowserOutput>
  convert(input: ConvertDocumentWithJupyterBrowserInput): Promise<ConvertDocumentWithJupyterBrowserOutput>
  convert(input: ConvertDocumentWithLibreOfficeBrowserInput): Promise<ConvertDocumentWithLibreOfficeBrowserOutput>
  convert(input: ConvertDocumentWithPandocBrowserInput): Promise<ConvertDocumentWithPandocBrowserOutput>
  convert(input: ConvertFontWithFontForgeBrowserInput): Promise<ConvertFontWithFontForgeBrowserOutput>
  convert(input: ConvertHtmlWithPuppeteerBrowserInput): Promise<ConvertHtmlWithPuppeteerBrowserOutput>
  convert(input: ConvertImageWithImageMagickBrowserInput): Promise<ConvertImageWithImageMagickBrowserOutput>
  convert(input: ConvertImageWithInkscapeBrowserInput): Promise<ConvertImageWithInkscapeBrowserOutput>
  convert(input: ConvertLatexToPngBrowserInput): Promise<ConvertLatexToPngBrowserOutput>
  convert(input: ConvertLatexWithPdfLatexBrowserInput): Promise<ConvertLatexWithPdfLatexBrowserOutput>
  convert(input: ConvertMarkdownWithPuppeteerBrowserInput): Promise<ConvertMarkdownWithPuppeteerBrowserOutput>
  convert(input: ConvertParquetBrowserInput): Promise<ConvertParquetBrowserOutput>
  convert(input: ConvertTxtWithPuppeteerBrowserInput): Promise<ConvertTxtWithPuppeteerBrowserOutput>
  convert(input: ConvertVideoWithFfmpegBrowserInput): Promise<ConvertVideoWithFfmpegBrowserOutput>

  decrypt(input: DecryptFileBrowserInput): Promise<DecryptFileBrowserOutput>

  disassemble(input: DisassembleDotnetBrowserInput): Promise<DisassembleDotnetBrowserOutput>
  disassemble(input: DisassembleGhidraBrowserInput): Promise<DisassembleGhidraBrowserOutput>
  disassemble(input: DisassembleJvmBrowserInput): Promise<DisassembleJvmBrowserOutput>
  disassemble(input: DisassembleRadareBrowserInput): Promise<DisassembleRadareBrowserOutput>
  disassemble(input: DisassembleWasmBrowserInput): Promise<DisassembleWasmBrowserOutput>

  encrypt(input: EncryptFileBrowserInput): Promise<EncryptFileBrowserOutput>

  format(input: FormatAssemblyBrowserInput): Promise<FormatAssemblyBrowserOutput>
  format(input: FormatCodeWithClangFormatBrowserInput): Promise<FormatCodeWithClangFormatBrowserOutput>
  format(input: FormatKotlinBrowserInput): Promise<FormatKotlinBrowserOutput>
  format(input: FormatPythonBrowserInput): Promise<FormatPythonBrowserOutput>
  format(input: FormatRustBrowserInput): Promise<FormatRustBrowserOutput>
  format(input: FormatSwiftBrowserInput): Promise<FormatSwiftBrowserOutput>

  remove(input: RemoveExifBrowserInput): Promise<RemoveExifBrowserOutput>
  remove(input: RemovePasswordBrowserInput): Promise<RemovePasswordBrowserOutput>
  remove(input: RemoveProfileBrowserInput): Promise<RemoveProfileBrowserOutput>
  remove(input: RemoveSubtitlesBrowserInput): Promise<RemoveSubtitlesBrowserOutput>
  remove(input: RemoveTransparencyBrowserInput): Promise<RemoveTransparencyBrowserOutput>

  sanitize(input: SanitizeHtmlBrowserInput): Promise<SanitizeHtmlBrowserOutput>
}

export type CompileBrowserInput =
  | CompileCBrowserInput
  | CompileCppBrowserInput
  | CompileRustBrowserInput
  | CompileSwiftBrowserInput
  | CompileWastBrowserInput
export type CompileBrowserOutput =
  | CompileCBrowserOutput
  | CompileCppBrowserOutput
  | CompileRustBrowserOutput
  | CompileSwiftBrowserOutput
  | CompileWastBrowserOutput

export type ConvertBrowserInput =
  | ConvertArchiveBrowserInput
  | ConvertDataBrowserInput
  | ConvertDocumentWithCalibreBrowserInput
  | ConvertDocumentWithEnscriptBrowserInput
  | ConvertDocumentWithJupyterBrowserInput
  | ConvertDocumentWithLibreOfficeBrowserInput
  | ConvertDocumentWithPandocBrowserInput
  | ConvertFontWithFontForgeBrowserInput
  | ConvertHtmlWithPuppeteerBrowserInput
  | ConvertImageWithImageMagickBrowserInput
  | ConvertImageWithInkscapeBrowserInput
  | ConvertLatexToPngBrowserInput
  | ConvertLatexWithPdfLatexBrowserInput
  | ConvertMarkdownWithPuppeteerBrowserInput
  | ConvertParquetBrowserInput
  | ConvertTxtWithPuppeteerBrowserInput
  | ConvertVideoWithFfmpegBrowserInput
export type ConvertBrowserOutput =
  | ConvertArchiveBrowserOutput
  | ConvertDataBrowserOutput
  | ConvertDocumentWithCalibreBrowserOutput
  | ConvertDocumentWithEnscriptBrowserOutput
  | ConvertDocumentWithJupyterBrowserOutput
  | ConvertDocumentWithLibreOfficeBrowserOutput
  | ConvertDocumentWithPandocBrowserOutput
  | ConvertFontWithFontForgeBrowserOutput
  | ConvertHtmlWithPuppeteerBrowserOutput
  | ConvertImageWithImageMagickBrowserOutput
  | ConvertImageWithInkscapeBrowserOutput
  | ConvertLatexToPngBrowserOutput
  | ConvertLatexWithPdfLatexBrowserOutput
  | ConvertMarkdownWithPuppeteerBrowserOutput
  | ConvertParquetBrowserOutput
  | ConvertTxtWithPuppeteerBrowserOutput
  | ConvertVideoWithFfmpegBrowserOutput

export type DecryptBrowserInput =
  | DecryptFileBrowserInput
export type DecryptBrowserOutput =
  | DecryptFileBrowserOutput

export type DisassembleBrowserInput =
  | DisassembleDotnetBrowserInput
  | DisassembleGhidraBrowserInput
  | DisassembleJvmBrowserInput
  | DisassembleRadareBrowserInput
  | DisassembleWasmBrowserInput
export type DisassembleBrowserOutput =
  | DisassembleDotnetBrowserOutput
  | DisassembleGhidraBrowserOutput
  | DisassembleJvmBrowserOutput
  | DisassembleRadareBrowserOutput
  | DisassembleWasmBrowserOutput

export type EncryptBrowserInput =
  | EncryptFileBrowserInput
export type EncryptBrowserOutput =
  | EncryptFileBrowserOutput

export type FormatBrowserInput =
  | FormatAssemblyBrowserInput
  | FormatCodeWithClangFormatBrowserInput
  | FormatKotlinBrowserInput
  | FormatPythonBrowserInput
  | FormatRustBrowserInput
  | FormatSwiftBrowserInput
export type FormatBrowserOutput =
  | FormatAssemblyBrowserOutput
  | FormatCodeWithClangFormatBrowserOutput
  | FormatKotlinBrowserOutput
  | FormatPythonBrowserOutput
  | FormatRustBrowserOutput
  | FormatSwiftBrowserOutput

export type RemoveBrowserInput =
  | RemoveExifBrowserInput
  | RemovePasswordBrowserInput
  | RemoveProfileBrowserInput
  | RemoveSubtitlesBrowserInput
  | RemoveTransparencyBrowserInput
export type RemoveBrowserOutput =
  | RemoveExifBrowserOutput
  | RemovePasswordBrowserOutput
  | RemoveProfileBrowserOutput
  | RemoveSubtitlesBrowserOutput
  | RemoveTransparencyBrowserOutput

export type SanitizeBrowserInput =
  | SanitizeHtmlBrowserInput
export type SanitizeBrowserOutput =
  | SanitizeHtmlBrowserOutput
