// AUTO-GENERATED by pnpm make:type. Do not edit.

import type {
  CompileCBrowserInput,
  CompileCBrowserOutput,
} from '~/code/form/action/compile/code/c/browser'
import type {
  CompileCppBrowserInput,
  CompileCppBrowserOutput,
} from '~/code/form/action/compile/code/cpp/browser'
import type {
  CompileRustBrowserInput,
  CompileRustBrowserOutput,
} from '~/code/form/action/compile/code/rust/browser'
import type {
  CompileSwiftBrowserInput,
  CompileSwiftBrowserOutput,
} from '~/code/form/action/compile/code/swift/browser'
import type {
  CompileWastBrowserInput,
  CompileWastBrowserOutput,
} from '~/code/form/action/compile/code/wast/browser'
import type {
  CompressAudioBrowserInput,
  CompressAudioBrowserOutput,
} from '~/code/form/action/compress/audio/browser'
import type {
  CompressFontBrowserInput,
  CompressFontBrowserOutput,
} from '~/code/form/action/compress/font/browser'
import type {
  CompressImageBrowserInput,
  CompressImageBrowserOutput,
} from '~/code/form/action/compress/image/browser'
import type {
  CompressVideoBrowserInput,
  CompressVideoBrowserOutput,
} from '~/code/form/action/compress/video/browser'
import type {
  ConvertArchiveBrowserInput,
  ConvertArchiveBrowserOutput,
} from '~/code/form/action/convert/archive/browser'
import type {
  ConvertDataBrowserInput,
  ConvertDataBrowserOutput,
} from '~/code/form/action/convert/data/browser'
import type {
  ConvertDocumentWithCalibreBrowserInput,
  ConvertDocumentWithCalibreBrowserOutput,
} from '~/code/form/action/convert/calibre/browser'
import type {
  ConvertDocumentWithEnscriptBrowserInput,
  ConvertDocumentWithEnscriptBrowserOutput,
} from '~/code/form/action/convert/enscript/browser'
import type {
  ConvertDocumentWithJupyterBrowserInput,
  ConvertDocumentWithJupyterBrowserOutput,
} from '~/code/form/action/convert/jupyter/browser'
import type {
  ConvertDocumentWithLibreOfficeBrowserInput,
  ConvertDocumentWithLibreOfficeBrowserOutput,
} from '~/code/form/action/convert/libre-office/browser'
import type {
  ConvertDocumentWithPandocBrowserInput,
  ConvertDocumentWithPandocBrowserOutput,
} from '~/code/form/action/convert/pandoc/browser'
import type {
  ConvertFontWithFontForgeBrowserInput,
  ConvertFontWithFontForgeBrowserOutput,
} from '~/code/form/action/convert/font-forge/browser'
import type {
  ConvertHtmlWithPuppeteerBrowserInput,
  ConvertHtmlWithPuppeteerBrowserOutput,
  ConvertMarkdownWithPuppeteerBrowserInput,
  ConvertMarkdownWithPuppeteerBrowserOutput,
  ConvertTxtWithPuppeteerBrowserInput,
  ConvertTxtWithPuppeteerBrowserOutput,
} from '~/code/form/action/convert/puppeteer/browser'
import type {
  ConvertImageWithApngasmBrowserInput,
  ConvertImageWithApngasmBrowserOutput,
} from '~/code/form/action/convert/image/apngasm/browser'
import type {
  ConvertImageWithAutotraceBrowserInput,
  ConvertImageWithAutotraceBrowserOutput,
} from '~/code/form/action/convert/image/autotrace/browser'
import type {
  ConvertImageWithDarktableBrowserInput,
  ConvertImageWithDarktableBrowserOutput,
} from '~/code/form/action/convert/image/darktable/browser'
import type {
  ConvertImageWithDcrawBrowserInput,
  ConvertImageWithDcrawBrowserOutput,
} from '~/code/form/action/convert/image/dcraw/browser'
import type {
  ConvertImageWithFfmpegBrowserInput,
  ConvertImageWithFfmpegBrowserOutput,
} from '~/code/form/action/convert/image/ffmpeg/browser'
import type {
  ConvertImageWithGifsicleBrowserInput,
  ConvertImageWithGifsicleBrowserOutput,
} from '~/code/form/action/convert/image/gifsicle/browser'
import type {
  ConvertImageWithImageMagickBrowserInput,
  ConvertImageWithImageMagickBrowserOutput,
} from '~/code/form/action/convert/imagemagick/browser'
import type {
  ConvertImageWithImg2WebpBrowserInput,
  ConvertImageWithImg2WebpBrowserOutput,
} from '~/code/form/action/convert/image/img2webp/browser'
import type {
  ConvertImageWithInkscapeBrowserInput,
  ConvertImageWithInkscapeBrowserOutput,
} from '~/code/form/action/convert/inkscape/browser'
import type {
  ConvertImageWithPotraceBrowserInput,
  ConvertImageWithPotraceBrowserOutput,
} from '~/code/form/action/convert/image/potrace/browser'
import type {
  ConvertImageWithRadianceBrowserInput,
  ConvertImageWithRadianceBrowserOutput,
} from '~/code/form/action/convert/image/radiance/browser'
import type {
  ConvertImageWithRawtherapeeBrowserInput,
  ConvertImageWithRawtherapeeBrowserOutput,
} from '~/code/form/action/convert/image/rawtherapee/browser'
import type {
  ConvertImageWithRsvgBrowserInput,
  ConvertImageWithRsvgBrowserOutput,
} from '~/code/form/action/convert/image/rsvg/browser'
import type {
  ConvertLatexToPngBrowserInput,
  ConvertLatexToPngBrowserOutput,
} from '~/code/form/action/convert/latex-to-png/browser'
import type {
  ConvertLatexWithPdfLatexBrowserInput,
  ConvertLatexWithPdfLatexBrowserOutput,
} from '~/code/form/action/convert/pdf-latex/browser'
import type {
  ConvertParquetBrowserInput,
  ConvertParquetBrowserOutput,
} from '~/code/form/action/convert/parquet/browser'
import type {
  ConvertVideoWithFfmpegBrowserInput,
  ConvertVideoWithFfmpegBrowserOutput,
} from '~/code/form/action/convert/ffmpeg/browser'
import type {
  DecryptFileBrowserInput,
  DecryptFileBrowserOutput,
} from '~/code/form/action/decrypt/file/browser'
import type {
  DisassembleDotnetBrowserInput,
  DisassembleDotnetBrowserOutput,
} from '~/code/form/action/disassemble/dotnet/browser'
import type {
  DisassembleGhidraBrowserInput,
  DisassembleGhidraBrowserOutput,
} from '~/code/form/action/disassemble/ghidra/browser'
import type {
  DisassembleJvmBrowserInput,
  DisassembleJvmBrowserOutput,
} from '~/code/form/action/disassemble/jvm/browser'
import type {
  DisassembleRadareBrowserInput,
  DisassembleRadareBrowserOutput,
} from '~/code/form/action/disassemble/radare/browser'
import type {
  DisassembleWasmBrowserInput,
  DisassembleWasmBrowserOutput,
} from '~/code/form/action/disassemble/wasm/browser'
import type {
  DumpFontBrowserInput,
  DumpFontBrowserOutput,
} from '~/code/form/action/dump/font/browser'
import type {
  EncryptFileBrowserInput,
  EncryptFileBrowserOutput,
} from '~/code/form/action/encrypt/file/browser'
import type {
  FlipImageBrowserInput,
  FlipImageBrowserOutput,
} from '~/code/form/action/flip/image/browser'
import type {
  FormatAssemblyBrowserInput,
  FormatAssemblyBrowserOutput,
  FormatCodeWithClangFormatBrowserInput,
  FormatCodeWithClangFormatBrowserOutput,
  FormatKotlinBrowserInput,
  FormatKotlinBrowserOutput,
  FormatPythonBrowserInput,
  FormatPythonBrowserOutput,
  FormatRustBrowserInput,
  FormatRustBrowserOutput,
  FormatSwiftBrowserInput,
  FormatSwiftBrowserOutput,
} from '~/code/form/action/format/code/browser'
import type {
  GetDurationBrowserInput,
  GetDurationBrowserOutput,
} from '~/code/form/action/get/duration/browser'
import type {
  InspectFileBrowserInput,
  InspectFileBrowserOutput,
} from '~/code/form/action/inspect/file/browser'
import type {
  InspectMetadataBrowserInput,
  InspectMetadataBrowserOutput,
} from '~/code/form/action/inspect/metadata/browser'
import type {
  ModifyPdfBrowserInput,
  ModifyPdfBrowserOutput,
} from '~/code/form/action/modify/pdf/browser'
import type {
  NormalizeAudioBrowserInput,
  NormalizeAudioBrowserOutput,
} from '~/code/form/action/normalize/audio/browser'
import type {
  PadBrowserInput,
  PadBrowserOutput,
} from '~/code/form/action/pad/browser'
import type {
  RemoveAudioBrowserInput,
  RemoveAudioBrowserOutput,
} from '~/code/form/action/remove/audio/browser'
import type {
  RemoveExifBrowserInput,
  RemoveExifBrowserOutput,
} from '~/code/form/action/remove/exif/browser'
import type {
  RemoveInvisibleBrowserInput,
  RemoveInvisibleBrowserOutput,
} from '~/code/form/action/remove/invisible/browser'
import type {
  RemoveMetadataBrowserInput,
  RemoveMetadataBrowserOutput,
} from '~/code/form/action/remove/metadata/browser'
import type {
  RemovePasswordBrowserInput,
  RemovePasswordBrowserOutput,
} from '~/code/form/action/remove/password/browser'
import type {
  RemoveProfileBrowserInput,
  RemoveProfileBrowserOutput,
} from '~/code/form/action/remove/profile/browser'
import type {
  RemoveSubtitlesBrowserInput,
  RemoveSubtitlesBrowserOutput,
} from '~/code/form/action/remove/subtitles/browser'
import type {
  RemoveTransparencyBrowserInput,
  RemoveTransparencyBrowserOutput,
} from '~/code/form/action/remove/transparency/browser'
import type {
  RenderFontBrowserInput,
  RenderFontBrowserOutput,
} from '~/code/form/action/render/font/browser'
import type {
  RotateImageBrowserInput,
  RotateImageBrowserOutput,
} from '~/code/form/action/rotate/image/browser'
import type {
  RotateVideoBrowserInput,
  RotateVideoBrowserOutput,
} from '~/code/form/action/rotate/video/browser'
import type {
  SanitizeHtmlBrowserInput,
  SanitizeHtmlBrowserOutput,
} from '~/code/form/action/sanitize/code/browser'
import type {
  ShapeFontBrowserInput,
  ShapeFontBrowserOutput,
} from '~/code/form/action/shape/font/browser'
import type {
  SplitAudioBrowserInput,
  SplitAudioBrowserOutput,
} from '~/code/form/action/split/audio/browser'
import type {
  SubsetFontBrowserInput,
  SubsetFontBrowserOutput,
} from '~/code/form/action/subset/font/browser'
import type {
  TrimAudioBrowserInput,
  TrimAudioBrowserOutput,
} from '~/code/form/action/trim/audio/browser'
import type {
  TrimImageBrowserInput,
  TrimImageBrowserOutput,
} from '~/code/form/action/trim/image/browser'
import type {
  TrimVideoBrowserInput,
  TrimVideoBrowserOutput,
} from '~/code/form/action/trim/video/browser'
import type {
  UpdateFontBrowserInput,
  UpdateFontBrowserOutput,
} from '~/code/form/action/update/font/browser'
import type {
  UpdateImageBrowserInput,
  UpdateImageBrowserOutput,
} from '~/code/form/action/update/image/browser'
import type {
  UpdateVideoBrowserInput,
  UpdateVideoBrowserOutput,
} from '~/code/form/action/update/video/browser'

export interface TaskSurface {
  compile(input: CompileCBrowserInput): Promise<CompileCBrowserOutput>
  compile(input: CompileCppBrowserInput): Promise<CompileCppBrowserOutput>
  compile(input: CompileRustBrowserInput): Promise<CompileRustBrowserOutput>
  compile(input: CompileSwiftBrowserInput): Promise<CompileSwiftBrowserOutput>
  compile(input: CompileWastBrowserInput): Promise<CompileWastBrowserOutput>

  compress(input: CompressAudioBrowserInput): Promise<CompressAudioBrowserOutput>
  compress(input: CompressFontBrowserInput): Promise<CompressFontBrowserOutput>
  compress(input: CompressImageBrowserInput): Promise<CompressImageBrowserOutput>
  compress(input: CompressVideoBrowserInput): Promise<CompressVideoBrowserOutput>

  convert(input: ConvertArchiveBrowserInput): Promise<ConvertArchiveBrowserOutput>
  convert(input: ConvertDataBrowserInput): Promise<ConvertDataBrowserOutput>
  convert(input: ConvertDocumentWithCalibreBrowserInput): Promise<ConvertDocumentWithCalibreBrowserOutput>
  convert(input: ConvertDocumentWithEnscriptBrowserInput): Promise<ConvertDocumentWithEnscriptBrowserOutput>
  convert(input: ConvertDocumentWithJupyterBrowserInput): Promise<ConvertDocumentWithJupyterBrowserOutput>
  convert(input: ConvertDocumentWithLibreOfficeBrowserInput): Promise<ConvertDocumentWithLibreOfficeBrowserOutput>
  convert(input: ConvertDocumentWithPandocBrowserInput): Promise<ConvertDocumentWithPandocBrowserOutput>
  convert(input: ConvertFontWithFontForgeBrowserInput): Promise<ConvertFontWithFontForgeBrowserOutput>
  convert(input: ConvertHtmlWithPuppeteerBrowserInput): Promise<ConvertHtmlWithPuppeteerBrowserOutput>
  convert(input: ConvertImageWithApngasmBrowserInput): Promise<ConvertImageWithApngasmBrowserOutput>
  convert(input: ConvertImageWithAutotraceBrowserInput): Promise<ConvertImageWithAutotraceBrowserOutput>
  convert(input: ConvertImageWithDarktableBrowserInput): Promise<ConvertImageWithDarktableBrowserOutput>
  convert(input: ConvertImageWithDcrawBrowserInput): Promise<ConvertImageWithDcrawBrowserOutput>
  convert(input: ConvertImageWithFfmpegBrowserInput): Promise<ConvertImageWithFfmpegBrowserOutput>
  convert(input: ConvertImageWithGifsicleBrowserInput): Promise<ConvertImageWithGifsicleBrowserOutput>
  convert(input: ConvertImageWithImageMagickBrowserInput): Promise<ConvertImageWithImageMagickBrowserOutput>
  convert(input: ConvertImageWithImg2WebpBrowserInput): Promise<ConvertImageWithImg2WebpBrowserOutput>
  convert(input: ConvertImageWithInkscapeBrowserInput): Promise<ConvertImageWithInkscapeBrowserOutput>
  convert(input: ConvertImageWithPotraceBrowserInput): Promise<ConvertImageWithPotraceBrowserOutput>
  convert(input: ConvertImageWithRadianceBrowserInput): Promise<ConvertImageWithRadianceBrowserOutput>
  convert(input: ConvertImageWithRawtherapeeBrowserInput): Promise<ConvertImageWithRawtherapeeBrowserOutput>
  convert(input: ConvertImageWithRsvgBrowserInput): Promise<ConvertImageWithRsvgBrowserOutput>
  convert(input: ConvertLatexToPngBrowserInput): Promise<ConvertLatexToPngBrowserOutput>
  convert(input: ConvertLatexWithPdfLatexBrowserInput): Promise<ConvertLatexWithPdfLatexBrowserOutput>
  convert(input: ConvertMarkdownWithPuppeteerBrowserInput): Promise<ConvertMarkdownWithPuppeteerBrowserOutput>
  convert(input: ConvertParquetBrowserInput): Promise<ConvertParquetBrowserOutput>
  convert(input: ConvertTxtWithPuppeteerBrowserInput): Promise<ConvertTxtWithPuppeteerBrowserOutput>
  convert(input: ConvertVideoWithFfmpegBrowserInput): Promise<ConvertVideoWithFfmpegBrowserOutput>

  decrypt(input: DecryptFileBrowserInput): Promise<DecryptFileBrowserOutput>

  disassemble(input: DisassembleDotnetBrowserInput): Promise<DisassembleDotnetBrowserOutput>
  disassemble(input: DisassembleGhidraBrowserInput): Promise<DisassembleGhidraBrowserOutput>
  disassemble(input: DisassembleJvmBrowserInput): Promise<DisassembleJvmBrowserOutput>
  disassemble(input: DisassembleRadareBrowserInput): Promise<DisassembleRadareBrowserOutput>
  disassemble(input: DisassembleWasmBrowserInput): Promise<DisassembleWasmBrowserOutput>

  dump(input: DumpFontBrowserInput): Promise<DumpFontBrowserOutput>

  encrypt(input: EncryptFileBrowserInput): Promise<EncryptFileBrowserOutput>

  flip(input: FlipImageBrowserInput): Promise<FlipImageBrowserOutput>

  format(input: FormatAssemblyBrowserInput): Promise<FormatAssemblyBrowserOutput>
  format(input: FormatCodeWithClangFormatBrowserInput): Promise<FormatCodeWithClangFormatBrowserOutput>
  format(input: FormatKotlinBrowserInput): Promise<FormatKotlinBrowserOutput>
  format(input: FormatPythonBrowserInput): Promise<FormatPythonBrowserOutput>
  format(input: FormatRustBrowserInput): Promise<FormatRustBrowserOutput>
  format(input: FormatSwiftBrowserInput): Promise<FormatSwiftBrowserOutput>

  get(input: GetDurationBrowserInput): Promise<GetDurationBrowserOutput>

  inspect(input: InspectFileBrowserInput): Promise<InspectFileBrowserOutput>
  inspect(input: InspectMetadataBrowserInput): Promise<InspectMetadataBrowserOutput>

  modify(input: ModifyPdfBrowserInput): Promise<ModifyPdfBrowserOutput>

  normalize(input: NormalizeAudioBrowserInput): Promise<NormalizeAudioBrowserOutput>

  pad(input: PadBrowserInput): Promise<PadBrowserOutput>

  remove(input: RemoveAudioBrowserInput): Promise<RemoveAudioBrowserOutput>
  remove(input: RemoveExifBrowserInput): Promise<RemoveExifBrowserOutput>
  remove(input: RemoveInvisibleBrowserInput): Promise<RemoveInvisibleBrowserOutput>
  remove(input: RemoveMetadataBrowserInput): Promise<RemoveMetadataBrowserOutput>
  remove(input: RemovePasswordBrowserInput): Promise<RemovePasswordBrowserOutput>
  remove(input: RemoveProfileBrowserInput): Promise<RemoveProfileBrowserOutput>
  remove(input: RemoveSubtitlesBrowserInput): Promise<RemoveSubtitlesBrowserOutput>
  remove(input: RemoveTransparencyBrowserInput): Promise<RemoveTransparencyBrowserOutput>

  render(input: RenderFontBrowserInput): Promise<RenderFontBrowserOutput>

  rotate(input: RotateImageBrowserInput): Promise<RotateImageBrowserOutput>
  rotate(input: RotateVideoBrowserInput): Promise<RotateVideoBrowserOutput>

  sanitize(input: SanitizeHtmlBrowserInput): Promise<SanitizeHtmlBrowserOutput>

  shape(input: ShapeFontBrowserInput): Promise<ShapeFontBrowserOutput>

  split(input: SplitAudioBrowserInput): Promise<SplitAudioBrowserOutput>

  subset(input: SubsetFontBrowserInput): Promise<SubsetFontBrowserOutput>

  trim(input: TrimAudioBrowserInput): Promise<TrimAudioBrowserOutput>
  trim(input: TrimImageBrowserInput): Promise<TrimImageBrowserOutput>
  trim(input: TrimVideoBrowserInput): Promise<TrimVideoBrowserOutput>

  update(input: UpdateFontBrowserInput): Promise<UpdateFontBrowserOutput>
  update(input: UpdateImageBrowserInput): Promise<UpdateImageBrowserOutput>
  update(input: UpdateVideoBrowserInput): Promise<UpdateVideoBrowserOutput>
}

export type CompileBrowserInput =
  | CompileCBrowserInput
  | CompileCppBrowserInput
  | CompileRustBrowserInput
  | CompileSwiftBrowserInput
  | CompileWastBrowserInput
export type CompileBrowserOutput =
  | CompileCBrowserOutput
  | CompileCppBrowserOutput
  | CompileRustBrowserOutput
  | CompileSwiftBrowserOutput
  | CompileWastBrowserOutput

export type CompressBrowserInput =
  | CompressAudioBrowserInput
  | CompressFontBrowserInput
  | CompressImageBrowserInput
  | CompressVideoBrowserInput
export type CompressBrowserOutput =
  | CompressAudioBrowserOutput
  | CompressFontBrowserOutput
  | CompressImageBrowserOutput
  | CompressVideoBrowserOutput

export type ConvertBrowserInput =
  | ConvertArchiveBrowserInput
  | ConvertDataBrowserInput
  | ConvertDocumentWithCalibreBrowserInput
  | ConvertDocumentWithEnscriptBrowserInput
  | ConvertDocumentWithJupyterBrowserInput
  | ConvertDocumentWithLibreOfficeBrowserInput
  | ConvertDocumentWithPandocBrowserInput
  | ConvertFontWithFontForgeBrowserInput
  | ConvertHtmlWithPuppeteerBrowserInput
  | ConvertImageWithApngasmBrowserInput
  | ConvertImageWithAutotraceBrowserInput
  | ConvertImageWithDarktableBrowserInput
  | ConvertImageWithDcrawBrowserInput
  | ConvertImageWithFfmpegBrowserInput
  | ConvertImageWithGifsicleBrowserInput
  | ConvertImageWithImageMagickBrowserInput
  | ConvertImageWithImg2WebpBrowserInput
  | ConvertImageWithInkscapeBrowserInput
  | ConvertImageWithPotraceBrowserInput
  | ConvertImageWithRadianceBrowserInput
  | ConvertImageWithRawtherapeeBrowserInput
  | ConvertImageWithRsvgBrowserInput
  | ConvertLatexToPngBrowserInput
  | ConvertLatexWithPdfLatexBrowserInput
  | ConvertMarkdownWithPuppeteerBrowserInput
  | ConvertParquetBrowserInput
  | ConvertTxtWithPuppeteerBrowserInput
  | ConvertVideoWithFfmpegBrowserInput
export type ConvertBrowserOutput =
  | ConvertArchiveBrowserOutput
  | ConvertDataBrowserOutput
  | ConvertDocumentWithCalibreBrowserOutput
  | ConvertDocumentWithEnscriptBrowserOutput
  | ConvertDocumentWithJupyterBrowserOutput
  | ConvertDocumentWithLibreOfficeBrowserOutput
  | ConvertDocumentWithPandocBrowserOutput
  | ConvertFontWithFontForgeBrowserOutput
  | ConvertHtmlWithPuppeteerBrowserOutput
  | ConvertImageWithApngasmBrowserOutput
  | ConvertImageWithAutotraceBrowserOutput
  | ConvertImageWithDarktableBrowserOutput
  | ConvertImageWithDcrawBrowserOutput
  | ConvertImageWithFfmpegBrowserOutput
  | ConvertImageWithGifsicleBrowserOutput
  | ConvertImageWithImageMagickBrowserOutput
  | ConvertImageWithImg2WebpBrowserOutput
  | ConvertImageWithInkscapeBrowserOutput
  | ConvertImageWithPotraceBrowserOutput
  | ConvertImageWithRadianceBrowserOutput
  | ConvertImageWithRawtherapeeBrowserOutput
  | ConvertImageWithRsvgBrowserOutput
  | ConvertLatexToPngBrowserOutput
  | ConvertLatexWithPdfLatexBrowserOutput
  | ConvertMarkdownWithPuppeteerBrowserOutput
  | ConvertParquetBrowserOutput
  | ConvertTxtWithPuppeteerBrowserOutput
  | ConvertVideoWithFfmpegBrowserOutput

export type DecryptBrowserInput =
  | DecryptFileBrowserInput
export type DecryptBrowserOutput =
  | DecryptFileBrowserOutput

export type DisassembleBrowserInput =
  | DisassembleDotnetBrowserInput
  | DisassembleGhidraBrowserInput
  | DisassembleJvmBrowserInput
  | DisassembleRadareBrowserInput
  | DisassembleWasmBrowserInput
export type DisassembleBrowserOutput =
  | DisassembleDotnetBrowserOutput
  | DisassembleGhidraBrowserOutput
  | DisassembleJvmBrowserOutput
  | DisassembleRadareBrowserOutput
  | DisassembleWasmBrowserOutput

export type DumpBrowserInput =
  | DumpFontBrowserInput
export type DumpBrowserOutput =
  | DumpFontBrowserOutput

export type EncryptBrowserInput =
  | EncryptFileBrowserInput
export type EncryptBrowserOutput =
  | EncryptFileBrowserOutput

export type FlipBrowserInput =
  | FlipImageBrowserInput
export type FlipBrowserOutput =
  | FlipImageBrowserOutput

export type FormatBrowserInput =
  | FormatAssemblyBrowserInput
  | FormatCodeWithClangFormatBrowserInput
  | FormatKotlinBrowserInput
  | FormatPythonBrowserInput
  | FormatRustBrowserInput
  | FormatSwiftBrowserInput
export type FormatBrowserOutput =
  | FormatAssemblyBrowserOutput
  | FormatCodeWithClangFormatBrowserOutput
  | FormatKotlinBrowserOutput
  | FormatPythonBrowserOutput
  | FormatRustBrowserOutput
  | FormatSwiftBrowserOutput

export type GetBrowserInput =
  | GetDurationBrowserInput
export type GetBrowserOutput =
  | GetDurationBrowserOutput

export type InspectBrowserInput =
  | InspectFileBrowserInput
  | InspectMetadataBrowserInput
export type InspectBrowserOutput =
  | InspectFileBrowserOutput
  | InspectMetadataBrowserOutput

export type ModifyBrowserInput =
  | ModifyPdfBrowserInput
export type ModifyBrowserOutput =
  | ModifyPdfBrowserOutput

export type NormalizeBrowserInput =
  | NormalizeAudioBrowserInput
export type NormalizeBrowserOutput =
  | NormalizeAudioBrowserOutput

export type PadBrowserInput =
  | PadBrowserInput
export type PadBrowserOutput =
  | PadBrowserOutput

export type RemoveBrowserInput =
  | RemoveAudioBrowserInput
  | RemoveExifBrowserInput
  | RemoveInvisibleBrowserInput
  | RemoveMetadataBrowserInput
  | RemovePasswordBrowserInput
  | RemoveProfileBrowserInput
  | RemoveSubtitlesBrowserInput
  | RemoveTransparencyBrowserInput
export type RemoveBrowserOutput =
  | RemoveAudioBrowserOutput
  | RemoveExifBrowserOutput
  | RemoveInvisibleBrowserOutput
  | RemoveMetadataBrowserOutput
  | RemovePasswordBrowserOutput
  | RemoveProfileBrowserOutput
  | RemoveSubtitlesBrowserOutput
  | RemoveTransparencyBrowserOutput

export type RenderBrowserInput =
  | RenderFontBrowserInput
export type RenderBrowserOutput =
  | RenderFontBrowserOutput

export type RotateBrowserInput =
  | RotateImageBrowserInput
  | RotateVideoBrowserInput
export type RotateBrowserOutput =
  | RotateImageBrowserOutput
  | RotateVideoBrowserOutput

export type SanitizeBrowserInput =
  | SanitizeHtmlBrowserInput
export type SanitizeBrowserOutput =
  | SanitizeHtmlBrowserOutput

export type ShapeBrowserInput =
  | ShapeFontBrowserInput
export type ShapeBrowserOutput =
  | ShapeFontBrowserOutput

export type SplitBrowserInput =
  | SplitAudioBrowserInput
export type SplitBrowserOutput =
  | SplitAudioBrowserOutput

export type SubsetBrowserInput =
  | SubsetFontBrowserInput
export type SubsetBrowserOutput =
  | SubsetFontBrowserOutput

export type TrimBrowserInput =
  | TrimAudioBrowserInput
  | TrimImageBrowserInput
  | TrimVideoBrowserInput
export type TrimBrowserOutput =
  | TrimAudioBrowserOutput
  | TrimImageBrowserOutput
  | TrimVideoBrowserOutput

export type UpdateBrowserInput =
  | UpdateFontBrowserInput
  | UpdateImageBrowserInput
  | UpdateVideoBrowserInput
export type UpdateBrowserOutput =
  | UpdateFontBrowserOutput
  | UpdateImageBrowserOutput
  | UpdateVideoBrowserOutput
