// AUTO-GENERATED by pnpm make:type. Do not edit.

import type {
  CompileCNodeInput,
  CompileCNodeOutput,
} from '~/code/form/action/compile/code/c/node'
import type {
  CompileCppNodeInput,
  CompileCppNodeOutput,
} from '~/code/form/action/compile/code/cpp/node'
import type {
  CompileRustNodeInput,
  CompileRustNodeOutput,
} from '~/code/form/action/compile/code/rust/node'
import type {
  CompileSwiftNodeInput,
  CompileSwiftNodeOutput,
} from '~/code/form/action/compile/code/swift/node'
import type {
  CompileWastNodeInput,
  CompileWastNodeOutput,
} from '~/code/form/action/compile/code/wast/node'
import type {
  CompressAudioNodeInput,
  CompressAudioNodeOutput,
} from '~/code/form/action/compress/audio/node'
import type {
  CompressFontNodeInput,
  CompressFontNodeOutput,
} from '~/code/form/action/compress/font/node'
import type {
  CompressImageNodeInput,
  CompressImageNodeOutput,
} from '~/code/form/action/compress/image/node'
import type {
  CompressVideoNodeInput,
  CompressVideoNodeOutput,
} from '~/code/form/action/compress/video/node'
import type {
  ConvertArchiveNodeInput,
  ConvertArchiveNodeOutput,
} from '~/code/form/action/convert/archive/node'
import type {
  ConvertDataNodeInput,
  ConvertDataNodeOutput,
} from '~/code/form/action/convert/data/node'
import type {
  ConvertDocumentWithCalibreNodeInput,
  ConvertDocumentWithCalibreNodeOutput,
} from '~/code/form/action/convert/calibre/node'
import type {
  ConvertDocumentWithEnscriptNodeInput,
  ConvertDocumentWithEnscriptNodeOutput,
} from '~/code/form/action/convert/enscript/node'
import type {
  ConvertDocumentWithJupyterNodeInput,
  ConvertDocumentWithJupyterNodeOutput,
} from '~/code/form/action/convert/jupyter/node'
import type {
  ConvertDocumentWithLibreOfficeNodeInput,
  ConvertDocumentWithLibreOfficeNodeOutput,
} from '~/code/form/action/convert/libre-office/node'
import type {
  ConvertDocumentWithPandocNodeInput,
  ConvertDocumentWithPandocNodeOutput,
} from '~/code/form/action/convert/pandoc/node'
import type {
  ConvertFontWithFontForgeNodeInput,
  ConvertFontWithFontForgeNodeOutput,
} from '~/code/form/action/convert/font-forge/node'
import type {
  ConvertHtmlWithPuppeteerNodeInput,
  ConvertHtmlWithPuppeteerNodeOutput,
  ConvertMarkdownWithPuppeteerNodeInput,
  ConvertMarkdownWithPuppeteerNodeOutput,
  ConvertTxtWithPuppeteerNodeInput,
  ConvertTxtWithPuppeteerNodeOutput,
} from '~/code/form/action/convert/puppeteer/node'
import type {
  ConvertImageWithApngasmNodeInput,
  ConvertImageWithApngasmNodeOutput,
} from '~/code/form/action/convert/image/apngasm/node'
import type {
  ConvertImageWithAutotraceNodeInput,
  ConvertImageWithAutotraceNodeOutput,
} from '~/code/form/action/convert/image/autotrace/node'
import type {
  ConvertImageWithDarktableNodeInput,
  ConvertImageWithDarktableNodeOutput,
} from '~/code/form/action/convert/image/darktable/node'
import type {
  ConvertImageWithDcrawNodeInput,
  ConvertImageWithDcrawNodeOutput,
} from '~/code/form/action/convert/image/dcraw/node'
import type {
  ConvertImageWithFfmpegNodeInput,
  ConvertImageWithFfmpegNodeOutput,
} from '~/code/form/action/convert/image/ffmpeg/node'
import type {
  ConvertImageWithGifsicleNodeInput,
  ConvertImageWithGifsicleNodeOutput,
} from '~/code/form/action/convert/image/gifsicle/node'
import type {
  ConvertImageWithImageMagickNodeInput,
  ConvertImageWithImageMagickNodeOutput,
} from '~/code/form/action/convert/imagemagick/node'
import type {
  ConvertImageWithImg2WebpNodeInput,
  ConvertImageWithImg2WebpNodeOutput,
} from '~/code/form/action/convert/image/img2webp/node'
import type {
  ConvertImageWithInkscapeNodeInput,
  ConvertImageWithInkscapeNodeOutput,
} from '~/code/form/action/convert/inkscape/node'
import type {
  ConvertImageWithPotraceNodeInput,
  ConvertImageWithPotraceNodeOutput,
} from '~/code/form/action/convert/image/potrace/node'
import type {
  ConvertImageWithRadianceNodeInput,
  ConvertImageWithRadianceNodeOutput,
} from '~/code/form/action/convert/image/radiance/node'
import type {
  ConvertImageWithRawtherapeeNodeInput,
  ConvertImageWithRawtherapeeNodeOutput,
} from '~/code/form/action/convert/image/rawtherapee/node'
import type {
  ConvertImageWithRsvgNodeInput,
  ConvertImageWithRsvgNodeOutput,
} from '~/code/form/action/convert/image/rsvg/node'
import type {
  ConvertLatexToPngNodeInput,
  ConvertLatexToPngNodeOutput,
} from '~/code/form/action/convert/latex-to-png/node'
import type {
  ConvertLatexWithPdfLatexNodeInput,
  ConvertLatexWithPdfLatexNodeOutput,
} from '~/code/form/action/convert/pdf-latex/node'
import type {
  ConvertParquetNodeInput,
  ConvertParquetNodeOutput,
} from '~/code/form/action/convert/parquet/node'
import type {
  ConvertVideoWithFfmpegNodeInput,
  ConvertVideoWithFfmpegNodeOutput,
} from '~/code/form/action/convert/ffmpeg/node'
import type {
  DecryptFileNodeInput,
  DecryptFileNodeOutput,
} from '~/code/form/action/decrypt/file/node'
import type {
  DisassembleDotnetNodeInput,
  DisassembleDotnetNodeOutput,
} from '~/code/form/action/disassemble/dotnet/node'
import type {
  DisassembleGhidraNodeInput,
  DisassembleGhidraNodeOutput,
} from '~/code/form/action/disassemble/ghidra/node'
import type {
  DisassembleJvmNodeInput,
  DisassembleJvmNodeOutput,
} from '~/code/form/action/disassemble/jvm/node'
import type {
  DisassembleRadareNodeInput,
  DisassembleRadareNodeOutput,
} from '~/code/form/action/disassemble/radare/node'
import type {
  DisassembleWasmNodeInput,
  DisassembleWasmNodeOutput,
} from '~/code/form/action/disassemble/wasm/node'
import type {
  DownloadHuggingFaceNodeInput,
  DownloadHuggingFaceNodeOutput,
} from '~/code/form/action/download/hugging-face/node'
import type {
  DumpFontNodeInput,
  DumpFontNodeOutput,
} from '~/code/form/action/dump/font/node'
import type {
  EncryptFileNodeInput,
  EncryptFileNodeOutput,
} from '~/code/form/action/encrypt/file/node'
import type {
  FlipImageNodeInput,
  FlipImageNodeOutput,
} from '~/code/form/action/flip/image/node'
import type {
  FormatAssemblyNodeInput,
  FormatAssemblyNodeOutput,
  FormatCodeWithClangFormatNodeInput,
  FormatCodeWithClangFormatNodeOutput,
  FormatKotlinNodeInput,
  FormatKotlinNodeOutput,
  FormatPythonNodeInput,
  FormatPythonNodeOutput,
  FormatRustNodeInput,
  FormatRustNodeOutput,
  FormatSwiftNodeInput,
  FormatSwiftNodeOutput,
} from '~/code/form/action/format/code/node'
import type {
  GetDurationNodeInput,
  GetDurationNodeOutput,
} from '~/code/form/action/get/duration/node'
import type {
  InspectFileNodeInput,
  InspectFileNodeOutput,
} from '~/code/form/action/inspect/file/node'
import type {
  InspectMetadataNodeInput,
  InspectMetadataNodeOutput,
} from '~/code/form/action/inspect/metadata/node'
import type {
  ModifyPdfNodeInput,
  ModifyPdfNodeOutput,
} from '~/code/form/action/modify/pdf/node'
import type {
  NormalizeAudioNodeInput,
  NormalizeAudioNodeOutput,
} from '~/code/form/action/normalize/audio/node'
import type {
  PadAudioNodeInput,
  PadAudioNodeOutput,
} from '~/code/form/action/pad/audio/node'
import type {
  RemoveAudioNodeInput,
  RemoveAudioNodeOutput,
} from '~/code/form/action/remove/audio/node'
import type {
  RemoveExifNodeInput,
  RemoveExifNodeOutput,
} from '~/code/form/action/remove/exif/node'
import type {
  RemoveInvisibleNodeInput,
  RemoveInvisibleNodeOutput,
} from '~/code/form/action/remove/invisible/node'
import type {
  RemoveMetadataNodeInput,
  RemoveMetadataNodeOutput,
} from '~/code/form/action/remove/metadata/node'
import type {
  RemovePasswordNodeInput,
  RemovePasswordNodeOutput,
} from '~/code/form/action/remove/password/node'
import type {
  RemoveProfileNodeInput,
  RemoveProfileNodeOutput,
} from '~/code/form/action/remove/profile/node'
import type {
  RemoveSubtitlesNodeInput,
  RemoveSubtitlesNodeOutput,
} from '~/code/form/action/remove/subtitles/node'
import type {
  RemoveTransparencyNodeInput,
  RemoveTransparencyNodeOutput,
} from '~/code/form/action/remove/transparency/node'
import type {
  RenderFontNodeInput,
  RenderFontNodeOutput,
} from '~/code/form/action/render/font/node'
import type {
  RotateImageNodeInput,
  RotateImageNodeOutput,
} from '~/code/form/action/rotate/image/node'
import type {
  RotateVideoNodeInput,
  RotateVideoNodeOutput,
} from '~/code/form/action/rotate/video/node'
import type {
  SanitizeHtmlNodeInput,
  SanitizeHtmlNodeOutput,
} from '~/code/form/action/sanitize/code/node'
import type {
  ShapeFontNodeInput,
  ShapeFontNodeOutput,
} from '~/code/form/action/shape/font/node'
import type {
  SplitAudioNodeInput,
  SplitAudioNodeOutput,
} from '~/code/form/action/split/audio/node'
import type {
  SubsetFontNodeInput,
  SubsetFontNodeOutput,
} from '~/code/form/action/subset/font/node'
import type {
  TrimAudioNodeInput,
  TrimAudioNodeOutput,
} from '~/code/form/action/trim/audio/node'
import type {
  TrimImageNodeInput,
  TrimImageNodeOutput,
} from '~/code/form/action/trim/image/node'
import type {
  TrimVideoNodeInput,
  TrimVideoNodeOutput,
} from '~/code/form/action/trim/video/node'
import type {
  UpdateFontNodeInput,
  UpdateFontNodeOutput,
} from '~/code/form/action/update/font/node'
import type {
  UpdateImageNodeInput,
  UpdateImageNodeOutput,
} from '~/code/form/action/update/image/node'
import type {
  UpdateVideoNodeInput,
  UpdateVideoNodeOutput,
} from '~/code/form/action/update/video/node'

export interface TaskSurface {
  compile(input: CompileCNodeInput): Promise<CompileCNodeOutput>
  compile(input: CompileCppNodeInput): Promise<CompileCppNodeOutput>
  compile(input: CompileRustNodeInput): Promise<CompileRustNodeOutput>
  compile(input: CompileSwiftNodeInput): Promise<CompileSwiftNodeOutput>
  compile(input: CompileWastNodeInput): Promise<CompileWastNodeOutput>

  compress(input: CompressAudioNodeInput): Promise<CompressAudioNodeOutput>
  compress(input: CompressFontNodeInput): Promise<CompressFontNodeOutput>
  compress(input: CompressImageNodeInput): Promise<CompressImageNodeOutput>
  compress(input: CompressVideoNodeInput): Promise<CompressVideoNodeOutput>

  convert(input: ConvertArchiveNodeInput): Promise<ConvertArchiveNodeOutput>
  convert(input: ConvertDataNodeInput): Promise<ConvertDataNodeOutput>
  convert(input: ConvertDocumentWithCalibreNodeInput): Promise<ConvertDocumentWithCalibreNodeOutput>
  convert(input: ConvertDocumentWithEnscriptNodeInput): Promise<ConvertDocumentWithEnscriptNodeOutput>
  convert(input: ConvertDocumentWithJupyterNodeInput): Promise<ConvertDocumentWithJupyterNodeOutput>
  convert(input: ConvertDocumentWithLibreOfficeNodeInput): Promise<ConvertDocumentWithLibreOfficeNodeOutput>
  convert(input: ConvertDocumentWithPandocNodeInput): Promise<ConvertDocumentWithPandocNodeOutput>
  convert(input: ConvertFontWithFontForgeNodeInput): Promise<ConvertFontWithFontForgeNodeOutput>
  convert(input: ConvertHtmlWithPuppeteerNodeInput): Promise<ConvertHtmlWithPuppeteerNodeOutput>
  convert(input: ConvertImageWithApngasmNodeInput): Promise<ConvertImageWithApngasmNodeOutput>
  convert(input: ConvertImageWithAutotraceNodeInput): Promise<ConvertImageWithAutotraceNodeOutput>
  convert(input: ConvertImageWithDarktableNodeInput): Promise<ConvertImageWithDarktableNodeOutput>
  convert(input: ConvertImageWithDcrawNodeInput): Promise<ConvertImageWithDcrawNodeOutput>
  convert(input: ConvertImageWithFfmpegNodeInput): Promise<ConvertImageWithFfmpegNodeOutput>
  convert(input: ConvertImageWithGifsicleNodeInput): Promise<ConvertImageWithGifsicleNodeOutput>
  convert(input: ConvertImageWithImageMagickNodeInput): Promise<ConvertImageWithImageMagickNodeOutput>
  convert(input: ConvertImageWithImg2WebpNodeInput): Promise<ConvertImageWithImg2WebpNodeOutput>
  convert(input: ConvertImageWithInkscapeNodeInput): Promise<ConvertImageWithInkscapeNodeOutput>
  convert(input: ConvertImageWithPotraceNodeInput): Promise<ConvertImageWithPotraceNodeOutput>
  convert(input: ConvertImageWithRadianceNodeInput): Promise<ConvertImageWithRadianceNodeOutput>
  convert(input: ConvertImageWithRawtherapeeNodeInput): Promise<ConvertImageWithRawtherapeeNodeOutput>
  convert(input: ConvertImageWithRsvgNodeInput): Promise<ConvertImageWithRsvgNodeOutput>
  convert(input: ConvertLatexToPngNodeInput): Promise<ConvertLatexToPngNodeOutput>
  convert(input: ConvertLatexWithPdfLatexNodeInput): Promise<ConvertLatexWithPdfLatexNodeOutput>
  convert(input: ConvertMarkdownWithPuppeteerNodeInput): Promise<ConvertMarkdownWithPuppeteerNodeOutput>
  convert(input: ConvertParquetNodeInput): Promise<ConvertParquetNodeOutput>
  convert(input: ConvertTxtWithPuppeteerNodeInput): Promise<ConvertTxtWithPuppeteerNodeOutput>
  convert(input: ConvertVideoWithFfmpegNodeInput): Promise<ConvertVideoWithFfmpegNodeOutput>

  decrypt(input: DecryptFileNodeInput): Promise<DecryptFileNodeOutput>

  disassemble(input: DisassembleDotnetNodeInput): Promise<DisassembleDotnetNodeOutput>
  disassemble(input: DisassembleGhidraNodeInput): Promise<DisassembleGhidraNodeOutput>
  disassemble(input: DisassembleJvmNodeInput): Promise<DisassembleJvmNodeOutput>
  disassemble(input: DisassembleRadareNodeInput): Promise<DisassembleRadareNodeOutput>
  disassemble(input: DisassembleWasmNodeInput): Promise<DisassembleWasmNodeOutput>

  download(input: DownloadHuggingFaceNodeInput): Promise<DownloadHuggingFaceNodeOutput>

  dump(input: DumpFontNodeInput): Promise<DumpFontNodeOutput>

  encrypt(input: EncryptFileNodeInput): Promise<EncryptFileNodeOutput>

  flip(input: FlipImageNodeInput): Promise<FlipImageNodeOutput>

  format(input: FormatAssemblyNodeInput): Promise<FormatAssemblyNodeOutput>
  format(input: FormatCodeWithClangFormatNodeInput): Promise<FormatCodeWithClangFormatNodeOutput>
  format(input: FormatKotlinNodeInput): Promise<FormatKotlinNodeOutput>
  format(input: FormatPythonNodeInput): Promise<FormatPythonNodeOutput>
  format(input: FormatRustNodeInput): Promise<FormatRustNodeOutput>
  format(input: FormatSwiftNodeInput): Promise<FormatSwiftNodeOutput>

  get(input: GetDurationNodeInput): Promise<GetDurationNodeOutput>

  inspect(input: InspectFileNodeInput): Promise<InspectFileNodeOutput>
  inspect(input: InspectMetadataNodeInput): Promise<InspectMetadataNodeOutput>

  modify(input: ModifyPdfNodeInput): Promise<ModifyPdfNodeOutput>

  normalize(input: NormalizeAudioNodeInput): Promise<NormalizeAudioNodeOutput>

  pad(input: PadAudioNodeInput): Promise<PadAudioNodeOutput>

  remove(input: RemoveAudioNodeInput): Promise<RemoveAudioNodeOutput>
  remove(input: RemoveExifNodeInput): Promise<RemoveExifNodeOutput>
  remove(input: RemoveInvisibleNodeInput): Promise<RemoveInvisibleNodeOutput>
  remove(input: RemoveMetadataNodeInput): Promise<RemoveMetadataNodeOutput>
  remove(input: RemovePasswordNodeInput): Promise<RemovePasswordNodeOutput>
  remove(input: RemoveProfileNodeInput): Promise<RemoveProfileNodeOutput>
  remove(input: RemoveSubtitlesNodeInput): Promise<RemoveSubtitlesNodeOutput>
  remove(input: RemoveTransparencyNodeInput): Promise<RemoveTransparencyNodeOutput>

  render(input: RenderFontNodeInput): Promise<RenderFontNodeOutput>

  rotate(input: RotateImageNodeInput): Promise<RotateImageNodeOutput>
  rotate(input: RotateVideoNodeInput): Promise<RotateVideoNodeOutput>

  sanitize(input: SanitizeHtmlNodeInput): Promise<SanitizeHtmlNodeOutput>

  shape(input: ShapeFontNodeInput): Promise<ShapeFontNodeOutput>

  split(input: SplitAudioNodeInput): Promise<SplitAudioNodeOutput>

  subset(input: SubsetFontNodeInput): Promise<SubsetFontNodeOutput>

  trim(input: TrimAudioNodeInput): Promise<TrimAudioNodeOutput>
  trim(input: TrimImageNodeInput): Promise<TrimImageNodeOutput>
  trim(input: TrimVideoNodeInput): Promise<TrimVideoNodeOutput>

  update(input: UpdateFontNodeInput): Promise<UpdateFontNodeOutput>
  update(input: UpdateImageNodeInput): Promise<UpdateImageNodeOutput>
  update(input: UpdateVideoNodeInput): Promise<UpdateVideoNodeOutput>
}

export type CompileNodeInput =
  | CompileCNodeInput
  | CompileCppNodeInput
  | CompileRustNodeInput
  | CompileSwiftNodeInput
  | CompileWastNodeInput
export type CompileNodeOutput =
  | CompileCNodeOutput
  | CompileCppNodeOutput
  | CompileRustNodeOutput
  | CompileSwiftNodeOutput
  | CompileWastNodeOutput

export type CompressNodeInput =
  | CompressAudioNodeInput
  | CompressFontNodeInput
  | CompressImageNodeInput
  | CompressVideoNodeInput
export type CompressNodeOutput =
  | CompressAudioNodeOutput
  | CompressFontNodeOutput
  | CompressImageNodeOutput
  | CompressVideoNodeOutput

export type ConvertNodeInput =
  | ConvertArchiveNodeInput
  | ConvertDataNodeInput
  | ConvertDocumentWithCalibreNodeInput
  | ConvertDocumentWithEnscriptNodeInput
  | ConvertDocumentWithJupyterNodeInput
  | ConvertDocumentWithLibreOfficeNodeInput
  | ConvertDocumentWithPandocNodeInput
  | ConvertFontWithFontForgeNodeInput
  | ConvertHtmlWithPuppeteerNodeInput
  | ConvertImageWithApngasmNodeInput
  | ConvertImageWithAutotraceNodeInput
  | ConvertImageWithDarktableNodeInput
  | ConvertImageWithDcrawNodeInput
  | ConvertImageWithFfmpegNodeInput
  | ConvertImageWithGifsicleNodeInput
  | ConvertImageWithImageMagickNodeInput
  | ConvertImageWithImg2WebpNodeInput
  | ConvertImageWithInkscapeNodeInput
  | ConvertImageWithPotraceNodeInput
  | ConvertImageWithRadianceNodeInput
  | ConvertImageWithRawtherapeeNodeInput
  | ConvertImageWithRsvgNodeInput
  | ConvertLatexToPngNodeInput
  | ConvertLatexWithPdfLatexNodeInput
  | ConvertMarkdownWithPuppeteerNodeInput
  | ConvertParquetNodeInput
  | ConvertTxtWithPuppeteerNodeInput
  | ConvertVideoWithFfmpegNodeInput
export type ConvertNodeOutput =
  | ConvertArchiveNodeOutput
  | ConvertDataNodeOutput
  | ConvertDocumentWithCalibreNodeOutput
  | ConvertDocumentWithEnscriptNodeOutput
  | ConvertDocumentWithJupyterNodeOutput
  | ConvertDocumentWithLibreOfficeNodeOutput
  | ConvertDocumentWithPandocNodeOutput
  | ConvertFontWithFontForgeNodeOutput
  | ConvertHtmlWithPuppeteerNodeOutput
  | ConvertImageWithApngasmNodeOutput
  | ConvertImageWithAutotraceNodeOutput
  | ConvertImageWithDarktableNodeOutput
  | ConvertImageWithDcrawNodeOutput
  | ConvertImageWithFfmpegNodeOutput
  | ConvertImageWithGifsicleNodeOutput
  | ConvertImageWithImageMagickNodeOutput
  | ConvertImageWithImg2WebpNodeOutput
  | ConvertImageWithInkscapeNodeOutput
  | ConvertImageWithPotraceNodeOutput
  | ConvertImageWithRadianceNodeOutput
  | ConvertImageWithRawtherapeeNodeOutput
  | ConvertImageWithRsvgNodeOutput
  | ConvertLatexToPngNodeOutput
  | ConvertLatexWithPdfLatexNodeOutput
  | ConvertMarkdownWithPuppeteerNodeOutput
  | ConvertParquetNodeOutput
  | ConvertTxtWithPuppeteerNodeOutput
  | ConvertVideoWithFfmpegNodeOutput

export type DecryptNodeInput =
  | DecryptFileNodeInput
export type DecryptNodeOutput =
  | DecryptFileNodeOutput

export type DisassembleNodeInput =
  | DisassembleDotnetNodeInput
  | DisassembleGhidraNodeInput
  | DisassembleJvmNodeInput
  | DisassembleRadareNodeInput
  | DisassembleWasmNodeInput
export type DisassembleNodeOutput =
  | DisassembleDotnetNodeOutput
  | DisassembleGhidraNodeOutput
  | DisassembleJvmNodeOutput
  | DisassembleRadareNodeOutput
  | DisassembleWasmNodeOutput

export type DownloadNodeInput =
  | DownloadHuggingFaceNodeInput
export type DownloadNodeOutput =
  | DownloadHuggingFaceNodeOutput

export type DumpNodeInput =
  | DumpFontNodeInput
export type DumpNodeOutput =
  | DumpFontNodeOutput

export type EncryptNodeInput =
  | EncryptFileNodeInput
export type EncryptNodeOutput =
  | EncryptFileNodeOutput

export type FlipNodeInput =
  | FlipImageNodeInput
export type FlipNodeOutput =
  | FlipImageNodeOutput

export type FormatNodeInput =
  | FormatAssemblyNodeInput
  | FormatCodeWithClangFormatNodeInput
  | FormatKotlinNodeInput
  | FormatPythonNodeInput
  | FormatRustNodeInput
  | FormatSwiftNodeInput
export type FormatNodeOutput =
  | FormatAssemblyNodeOutput
  | FormatCodeWithClangFormatNodeOutput
  | FormatKotlinNodeOutput
  | FormatPythonNodeOutput
  | FormatRustNodeOutput
  | FormatSwiftNodeOutput

export type GetNodeInput =
  | GetDurationNodeInput
export type GetNodeOutput =
  | GetDurationNodeOutput

export type InspectNodeInput =
  | InspectFileNodeInput
  | InspectMetadataNodeInput
export type InspectNodeOutput =
  | InspectFileNodeOutput
  | InspectMetadataNodeOutput

export type ModifyNodeInput =
  | ModifyPdfNodeInput
export type ModifyNodeOutput =
  | ModifyPdfNodeOutput

export type NormalizeNodeInput =
  | NormalizeAudioNodeInput
export type NormalizeNodeOutput =
  | NormalizeAudioNodeOutput

export type PadNodeInput =
  | PadAudioNodeInput
export type PadNodeOutput =
  | PadAudioNodeOutput

export type RemoveNodeInput =
  | RemoveAudioNodeInput
  | RemoveExifNodeInput
  | RemoveInvisibleNodeInput
  | RemoveMetadataNodeInput
  | RemovePasswordNodeInput
  | RemoveProfileNodeInput
  | RemoveSubtitlesNodeInput
  | RemoveTransparencyNodeInput
export type RemoveNodeOutput =
  | RemoveAudioNodeOutput
  | RemoveExifNodeOutput
  | RemoveInvisibleNodeOutput
  | RemoveMetadataNodeOutput
  | RemovePasswordNodeOutput
  | RemoveProfileNodeOutput
  | RemoveSubtitlesNodeOutput
  | RemoveTransparencyNodeOutput

export type RenderNodeInput =
  | RenderFontNodeInput
export type RenderNodeOutput =
  | RenderFontNodeOutput

export type RotateNodeInput =
  | RotateImageNodeInput
  | RotateVideoNodeInput
export type RotateNodeOutput =
  | RotateImageNodeOutput
  | RotateVideoNodeOutput

export type SanitizeNodeInput =
  | SanitizeHtmlNodeInput
export type SanitizeNodeOutput =
  | SanitizeHtmlNodeOutput

export type ShapeNodeInput =
  | ShapeFontNodeInput
export type ShapeNodeOutput =
  | ShapeFontNodeOutput

export type SplitNodeInput =
  | SplitAudioNodeInput
export type SplitNodeOutput =
  | SplitAudioNodeOutput

export type SubsetNodeInput =
  | SubsetFontNodeInput
export type SubsetNodeOutput =
  | SubsetFontNodeOutput

export type TrimNodeInput =
  | TrimAudioNodeInput
  | TrimImageNodeInput
  | TrimVideoNodeInput
export type TrimNodeOutput =
  | TrimAudioNodeOutput
  | TrimImageNodeOutput
  | TrimVideoNodeOutput

export type UpdateNodeInput =
  | UpdateFontNodeInput
  | UpdateImageNodeInput
  | UpdateVideoNodeInput
export type UpdateNodeOutput =
  | UpdateFontNodeOutput
  | UpdateImageNodeOutput
  | UpdateVideoNodeOutput
