// AUTO-GENERATED by pnpm make:type. Do not edit.

import type { CliOption } from '~/code/tool/shared/console'

export const options: CliOption[] = [
  {
    "path": [
      "input",
      "file",
      "path"
    ],
    "long": "input-file-path",
    "short": "i",
    "like": "string",
    "list": false,
    "need": true
  },
  {
    "path": [
      "output",
      "file",
      "path"
    ],
    "long": "output-file-path",
    "short": "o",
    "like": "string",
    "list": false,
    "need": false
  },
  {
    "path": [
      "grayscale"
    ],
    "long": "grayscale",
    "like": "boolean",
    "list": false,
    "need": false,
    "note": "Convert to grayscale"
  },
  {
    "path": [
      "brightness"
    ],
    "long": "brightness",
    "like": "string",
    "list": false,
    "need": false,
    "note": "Brightness adjust (e.g. +10, -20)"
  },
  {
    "path": [
      "contrast"
    ],
    "long": "contrast",
    "like": "string",
    "list": false,
    "need": false,
    "note": "Contrast adjust (e.g. +10, -20)"
  },
  {
    "path": [
      "saturation"
    ],
    "long": "saturation",
    "like": "string",
    "list": false,
    "need": false,
    "note": "Saturation adjust (e.g. +20)"
  }
]
