// AUTO-GENERATED by pnpm make:type. Do not edit.

import type { CliOption } from '~/code/tool/shared/console'

export const options: CliOption[] = [
  {
    "path": [
      "format"
    ],
    "long": "format",
    "short": "I",
    "like": "string",
    "list": false,
    "need": true
  },
  {
    "path": [
      "input",
      "file",
      "path"
    ],
    "long": "input-file-path",
    "like": "string",
    "list": false,
    "need": true
  },
  {
    "path": [
      "output",
      "file",
      "path"
    ],
    "long": "output-file-path",
    "like": "string",
    "list": false,
    "need": true
  }
]
