import {
  ConversionUnitAcre,
  ConversionUnitAmpere,
  ConversionUnitArcminute,
  ConversionUnitArcsecond,
  ConversionUnitBar,
  ConversionUnitBit,
  ConversionUnitByte,
  ConversionUnitCelsius,
  ConversionUnitCentilitre,
  ConversionUnitCentilitrePerSecond,
  ConversionUnitCentimeter,
  ConversionUnitCubicCentimeter,
  ConversionUnitCubicCentimeterPerSecond,
  ConversionUnitCubicFoot,
  ConversionUnitCubicFootPerHour,
  ConversionUnitCubicFootPerMinute,
  ConversionUnitCubicFootPerSecond,
  ConversionUnitCubicInch,
  ConversionUnitCubicInchPerHour,
  ConversionUnitCubicInchPerMinute,
  ConversionUnitCubicInchPerSecond,
  ConversionUnitCubicKilometer,
  ConversionUnitCubicKilometerPerSecond,
  ConversionUnitCubicMeter,
  ConversionUnitCubicMeterPerHour,
  ConversionUnitCubicMeterPerMinute,
  ConversionUnitCubicMeterPerSecond,
  ConversionUnitCubicMillimeter,
  ConversionUnitCubicMillimeterPerSecond,
  ConversionUnitCubicYard,
  ConversionUnitCubicYardPerHour,
  ConversionUnitCubicYardPerMinute,
  ConversionUnitCubicYardPerSecond,
  ConversionUnitCup,
  ConversionUnitCupPerSecond,
  ConversionUnitDay,
  ConversionUnitDecilitre,
  ConversionUnitDecilitrePerSecond,
  ConversionUnitDegree,
  ConversionUnitDegreePerSecond,
  ConversionUnitDozen,
  ConversionUnitEach,
  ConversionUnitFahrenheit,
  ConversionUnitFluidOunce,
  ConversionUnitFluidOuncePerHour,
  ConversionUnitFluidOuncePerMinute,
  ConversionUnitFluidOuncePerSecond,
  ConversionUnitFoot,
  ConversionUnitFootCandle,
  ConversionUnitFootPerSecond,
  ConversionUnitGallon,
  ConversionUnitGallonPerHour,
  ConversionUnitGallonPerMinute,
  ConversionUnitGallonPerSecond,
  ConversionUnitGigabit,
  ConversionUnitGigabyte,
  ConversionUnitGigahertz,
  ConversionUnitGigavoltAmpere,
  ConversionUnitGigavoltAmpereReactive,
  ConversionUnitGigavoltAmpereReactiveHour,
  ConversionUnitGigawatt,
  ConversionUnitGigawattHour,
  ConversionUnitGlas,
  ConversionUnitGradian,
  ConversionUnitGram,
  ConversionUnitHectare,
  ConversionUnitHectopascal,
  ConversionUnitHertz,
  ConversionUnitHour,
  ConversionUnitInch,
  ConversionUnitJoule,
  ConversionUnitKaffekopp,
  ConversionUnitKanna,
  ConversionUnitKelvin,
  ConversionUnitKiloampere,
  ConversionUnitKilobit,
  ConversionUnitKilobyte,
  ConversionUnitKilogram,
  ConversionUnitKilohertz,
  ConversionUnitKilojoule,
  ConversionUnitKilolitre,
  ConversionUnitKilolitrePerHour,
  ConversionUnitKilolitrePerMinute,
  ConversionUnitKilolitrePerSecond,
  ConversionUnitKilometer,
  ConversionUnitKilometrePerHour,
  ConversionUnitKilopascal,
  ConversionUnitKilopoundPerSquareInch,
  ConversionUnitKilovolt,
  ConversionUnitKilovoltAmpere,
  ConversionUnitKilovoltAmpereReactive,
  ConversionUnitKilovoltAmpereReactiveHour,
  ConversionUnitKilowatt,
  ConversionUnitKilowattHour,
  ConversionUnitKnot,
  ConversionUnitLitre,
  ConversionUnitLitrePerHour,
  ConversionUnitLitrePerMinute,
  ConversionUnitLitrePerSecond,
  ConversionUnitLux,
  ConversionUnitMatsked,
  ConversionUnitMegabit,
  ConversionUnitMegabyte,
  ConversionUnitMegahertz,
  ConversionUnitMegapascal,
  ConversionUnitMegavoltAmpere,
  ConversionUnitMegavoltAmpereReactive,
  ConversionUnitMegavoltAmpereReactiveHour,
  ConversionUnitMegawatt,
  ConversionUnitMegawattHour,
  ConversionUnitMeter,
  ConversionUnitMetrePerSecond,
  ConversionUnitMetricTonne,
  ConversionUnitMicrogram,
  ConversionUnitMicrosecond,
  ConversionUnitMile,
  ConversionUnitMilePerHour,
  ConversionUnitMilliampere,
  ConversionUnitMilligram,
  ConversionUnitMillihertz,
  ConversionUnitMillilitre,
  ConversionUnitMillilitrePerSecond,
  ConversionUnitMillimeter,
  ConversionUnitMillisecond,
  ConversionUnitMillivolt,
  ConversionUnitMillivoltAmpere,
  ConversionUnitMillivoltAmpereReactive,
  ConversionUnitMillivoltAmpereReactiveHour,
  ConversionUnitMilliwatt,
  ConversionUnitMilliwattHour,
  ConversionUnitMinute,
  ConversionUnitMinutePerKilometre,
  ConversionUnitMinutePerMile,
  ConversionUnitMonth,
  ConversionUnitNanosecond,
  ConversionUnitOunce,
  ConversionUnitPartPerBillion,
  ConversionUnitPartPerMillion,
  ConversionUnitPartPerQuadrillion,
  ConversionUnitPartPerTrillion,
  ConversionUnitPascal,
  ConversionUnitPint,
  ConversionUnitPintPerHour,
  ConversionUnitPintPerMinute,
  ConversionUnitPintPerSecond,
  ConversionUnitPound,
  ConversionUnitPoundPerSquareInch,
  ConversionUnitQuart,
  ConversionUnitQuartPerSecond,
  ConversionUnitRadian,
  ConversionUnitRadianPerSecond,
  ConversionUnitRankine,
  ConversionUnitRotationPerMinute,
  ConversionUnitSecond,
  ConversionUnitSecondPerFoot,
  ConversionUnitSecondPerMetre,
  ConversionUnitSquareCentimeter,
  ConversionUnitSquareFoot,
  ConversionUnitSquareInch,
  ConversionUnitSquareKilometer,
  ConversionUnitSquareMeter,
  ConversionUnitSquareMile,
  ConversionUnitSquareMillimeter,
  ConversionUnitSquareYard,
  ConversionUnitTablespoon,
  ConversionUnitTablespoonPerSecond,
  ConversionUnitTeaspoon,
  ConversionUnitTeaspoonPerSecond,
  ConversionUnitTerabit,
  ConversionUnitTerabyte,
  ConversionUnitTerahertz,
  ConversionUnitTesked,
  ConversionUnitTon,
  ConversionUnitTorr,
  ConversionUnitUsSurveyFoot,
  ConversionUnitVolt,
  ConversionUnitVoltAmpere,
  ConversionUnitVoltAmpereReactive,
  ConversionUnitVoltAmpereReactiveHour,
  ConversionUnitWatt,
  ConversionUnitWattHour,
  ConversionUnitWeek,
  ConversionUnitYard,
  ConversionUnitYear,
  Unit,
  UnitKeyHash,
} from '~/code/form/action/convert/unit/index'

export const CONVERSION_UNIT_ACRE: ReadonlyArray<ConversionUnitAcre> = [
  'square-millimeter',
  'square-centimeter',
  'square-meter',
  'hectare',
  'square-kilometer',
  'square-inch',
  'square-yard',
  'square-foot',
  'acre',
  'square-mile',
]
export const CONVERSION_UNIT_AMPERE: ReadonlyArray<ConversionUnitAmpere> =
  ['ampere', 'milliampere', 'kiloampere']
export const CONVERSION_UNIT_ARCMINUTE: ReadonlyArray<ConversionUnitArcminute> =
  ['radian', 'degree', 'gradian', 'arcminute', 'arcsecond']
export const CONVERSION_UNIT_ARCSECOND: ReadonlyArray<ConversionUnitArcsecond> =
  ['radian', 'degree', 'gradian', 'arcminute', 'arcsecond']
export const CONVERSION_UNIT_BAR: ReadonlyArray<ConversionUnitBar> = [
  'pascal',
  'kilopascal',
  'megapascal',
  'hectopascal',
  'bar',
  'torr',
  'pound-per-square-inch',
  'kilopound-per-square-inch',
]
export const CONVERSION_UNIT_BIT: ReadonlyArray<ConversionUnitBit> = [
  'bit',
  'kilobit',
  'megabit',
  'gigabit',
  'terabit',
  'byte',
  'kilobyte',
  'megabyte',
  'gigabyte',
  'terabyte',
]
export const CONVERSION_UNIT_BYTE: ReadonlyArray<ConversionUnitByte> = [
  'bit',
  'kilobit',
  'megabit',
  'gigabit',
  'terabit',
  'byte',
  'kilobyte',
  'megabyte',
  'gigabyte',
  'terabyte',
]
export const CONVERSION_UNIT_CELSIUS: ReadonlyArray<ConversionUnitCelsius> =
  ['celsius', 'kelvin', 'fahrenheit', 'rankine']
export const CONVERSION_UNIT_CENTILITRE: ReadonlyArray<ConversionUnitCentilitre> =
  [
    'cubic-millimeter',
    'cubic-centimeter',
    'millilitre',
    'centilitre',
    'decilitre',
    'litre',
    'kilolitre',
    'cubic-meter',
    'cubic-kilometer',
    'tesked',
    'matsked',
    'kaffekopp',
    'glas',
    'kanna',
    'teaspoon',
    'tablespoon',
    'cubic-inch',
    'fluid-ounce',
    'cup',
    'pint',
    'quart',
    'gallon',
    'cubic-foot',
    'cubic-yard',
  ]
export const CONVERSION_UNIT_CENTILITRE_PER_SECOND: ReadonlyArray<ConversionUnitCentilitrePerSecond> =
  [
    'cubic-millimeter-per-second',
    'cubic-centimeter-per-second',
    'millilitre-per-second',
    'centilitre-per-second',
    'decilitre-per-second',
    'litre-per-second',
    'litre-per-minute',
    'litre-per-hour',
    'kilolitre-per-second',
    'kilolitre-per-minute',
    'kilolitre-per-hour',
    'cubic-meter-per-second',
    'cubic-meter-per-minute',
    'cubic-meter-per-hour',
    'cubic-kilometer-per-second',
    'teaspoon-per-second',
    'tablespoon-per-second',
    'cubic-inch-per-second',
    'cubic-inch-per-minute',
    'cubic-inch-per-hour',
    'fluid-ounce-per-second',
    'fluid-ounce-per-minute',
    'fluid-ounce-per-hour',
    'cup-per-second',
    'pint-per-second',
    'pint-per-minute',
    'pint-per-hour',
    'quart-per-second',
    'gallon-per-second',
    'gallon-per-minute',
    'gallon-per-hour',
    'cubic-foot-per-second',
    'cubic-foot-per-minute',
    'cubic-foot-per-hour',
    'cubic-yard-per-second',
    'cubic-yard-per-minute',
    'cubic-yard-per-hour',
  ]
export const CONVERSION_UNIT_CENTIMETER: ReadonlyArray<ConversionUnitCentimeter> =
  [
    'millimeter',
    'centimeter',
    'meter',
    'kilometer',
    'inch',
    'yard',
    'us-survey-foot',
    'foot',
    'mile',
  ]
export const CONVERSION_UNIT_CUBIC_CENTIMETER: ReadonlyArray<ConversionUnitCubicCentimeter> =
  [
    'cubic-millimeter',
    'cubic-centimeter',
    'millilitre',
    'centilitre',
    'decilitre',
    'litre',
    'kilolitre',
    'cubic-meter',
    'cubic-kilometer',
    'tesked',
    'matsked',
    'kaffekopp',
    'glas',
    'kanna',
    'teaspoon',
    'tablespoon',
    'cubic-inch',
    'fluid-ounce',
    'cup',
    'pint',
    'quart',
    'gallon',
    'cubic-foot',
    'cubic-yard',
  ]
export const CONVERSION_UNIT_CUBIC_CENTIMETER_PER_SECOND: ReadonlyArray<ConversionUnitCubicCentimeterPerSecond> =
  [
    'cubic-millimeter-per-second',
    'cubic-centimeter-per-second',
    'millilitre-per-second',
    'centilitre-per-second',
    'decilitre-per-second',
    'litre-per-second',
    'litre-per-minute',
    'litre-per-hour',
    'kilolitre-per-second',
    'kilolitre-per-minute',
    'kilolitre-per-hour',
    'cubic-meter-per-second',
    'cubic-meter-per-minute',
    'cubic-meter-per-hour',
    'cubic-kilometer-per-second',
    'teaspoon-per-second',
    'tablespoon-per-second',
    'cubic-inch-per-second',
    'cubic-inch-per-minute',
    'cubic-inch-per-hour',
    'fluid-ounce-per-second',
    'fluid-ounce-per-minute',
    'fluid-ounce-per-hour',
    'cup-per-second',
    'pint-per-second',
    'pint-per-minute',
    'pint-per-hour',
    'quart-per-second',
    'gallon-per-second',
    'gallon-per-minute',
    'gallon-per-hour',
    'cubic-foot-per-second',
    'cubic-foot-per-minute',
    'cubic-foot-per-hour',
    'cubic-yard-per-second',
    'cubic-yard-per-minute',
    'cubic-yard-per-hour',
  ]
export const CONVERSION_UNIT_CUBIC_FOOT: ReadonlyArray<ConversionUnitCubicFoot> =
  [
    'cubic-millimeter',
    'cubic-centimeter',
    'millilitre',
    'centilitre',
    'decilitre',
    'litre',
    'kilolitre',
    'cubic-meter',
    'cubic-kilometer',
    'tesked',
    'matsked',
    'kaffekopp',
    'glas',
    'kanna',
    'teaspoon',
    'tablespoon',
    'cubic-inch',
    'fluid-ounce',
    'cup',
    'pint',
    'quart',
    'gallon',
    'cubic-foot',
    'cubic-yard',
  ]
export const CONVERSION_UNIT_CUBIC_FOOT_PER_HOUR: ReadonlyArray<ConversionUnitCubicFootPerHour> =
  [
    'cubic-millimeter-per-second',
    'cubic-centimeter-per-second',
    'millilitre-per-second',
    'centilitre-per-second',
    'decilitre-per-second',
    'litre-per-second',
    'litre-per-minute',
    'litre-per-hour',
    'kilolitre-per-second',
    'kilolitre-per-minute',
    'kilolitre-per-hour',
    'cubic-meter-per-second',
    'cubic-meter-per-minute',
    'cubic-meter-per-hour',
    'cubic-kilometer-per-second',
    'teaspoon-per-second',
    'tablespoon-per-second',
    'cubic-inch-per-second',
    'cubic-inch-per-minute',
    'cubic-inch-per-hour',
    'fluid-ounce-per-second',
    'fluid-ounce-per-minute',
    'fluid-ounce-per-hour',
    'cup-per-second',
    'pint-per-second',
    'pint-per-minute',
    'pint-per-hour',
    'quart-per-second',
    'gallon-per-second',
    'gallon-per-minute',
    'gallon-per-hour',
    'cubic-foot-per-second',
    'cubic-foot-per-minute',
    'cubic-foot-per-hour',
    'cubic-yard-per-second',
    'cubic-yard-per-minute',
    'cubic-yard-per-hour',
  ]
export const CONVERSION_UNIT_CUBIC_FOOT_PER_MINUTE: ReadonlyArray<ConversionUnitCubicFootPerMinute> =
  [
    'cubic-millimeter-per-second',
    'cubic-centimeter-per-second',
    'millilitre-per-second',
    'centilitre-per-second',
    'decilitre-per-second',
    'litre-per-second',
    'litre-per-minute',
    'litre-per-hour',
    'kilolitre-per-second',
    'kilolitre-per-minute',
    'kilolitre-per-hour',
    'cubic-meter-per-second',
    'cubic-meter-per-minute',
    'cubic-meter-per-hour',
    'cubic-kilometer-per-second',
    'teaspoon-per-second',
    'tablespoon-per-second',
    'cubic-inch-per-second',
    'cubic-inch-per-minute',
    'cubic-inch-per-hour',
    'fluid-ounce-per-second',
    'fluid-ounce-per-minute',
    'fluid-ounce-per-hour',
    'cup-per-second',
    'pint-per-second',
    'pint-per-minute',
    'pint-per-hour',
    'quart-per-second',
    'gallon-per-second',
    'gallon-per-minute',
    'gallon-per-hour',
    'cubic-foot-per-second',
    'cubic-foot-per-minute',
    'cubic-foot-per-hour',
    'cubic-yard-per-second',
    'cubic-yard-per-minute',
    'cubic-yard-per-hour',
  ]
export const CONVERSION_UNIT_CUBIC_FOOT_PER_SECOND: ReadonlyArray<ConversionUnitCubicFootPerSecond> =
  [
    'cubic-millimeter-per-second',
    'cubic-centimeter-per-second',
    'millilitre-per-second',
    'centilitre-per-second',
    'decilitre-per-second',
    'litre-per-second',
    'litre-per-minute',
    'litre-per-hour',
    'kilolitre-per-second',
    'kilolitre-per-minute',
    'kilolitre-per-hour',
    'cubic-meter-per-second',
    'cubic-meter-per-minute',
    'cubic-meter-per-hour',
    'cubic-kilometer-per-second',
    'teaspoon-per-second',
    'tablespoon-per-second',
    'cubic-inch-per-second',
    'cubic-inch-per-minute',
    'cubic-inch-per-hour',
    'fluid-ounce-per-second',
    'fluid-ounce-per-minute',
    'fluid-ounce-per-hour',
    'cup-per-second',
    'pint-per-second',
    'pint-per-minute',
    'pint-per-hour',
    'quart-per-second',
    'gallon-per-second',
    'gallon-per-minute',
    'gallon-per-hour',
    'cubic-foot-per-second',
    'cubic-foot-per-minute',
    'cubic-foot-per-hour',
    'cubic-yard-per-second',
    'cubic-yard-per-minute',
    'cubic-yard-per-hour',
  ]
export const CONVERSION_UNIT_CUBIC_INCH: ReadonlyArray<ConversionUnitCubicInch> =
  [
    'cubic-millimeter',
    'cubic-centimeter',
    'millilitre',
    'centilitre',
    'decilitre',
    'litre',
    'kilolitre',
    'cubic-meter',
    'cubic-kilometer',
    'tesked',
    'matsked',
    'kaffekopp',
    'glas',
    'kanna',
    'teaspoon',
    'tablespoon',
    'cubic-inch',
    'fluid-ounce',
    'cup',
    'pint',
    'quart',
    'gallon',
    'cubic-foot',
    'cubic-yard',
  ]
export const CONVERSION_UNIT_CUBIC_INCH_PER_HOUR: ReadonlyArray<ConversionUnitCubicInchPerHour> =
  [
    'cubic-millimeter-per-second',
    'cubic-centimeter-per-second',
    'millilitre-per-second',
    'centilitre-per-second',
    'decilitre-per-second',
    'litre-per-second',
    'litre-per-minute',
    'litre-per-hour',
    'kilolitre-per-second',
    'kilolitre-per-minute',
    'kilolitre-per-hour',
    'cubic-meter-per-second',
    'cubic-meter-per-minute',
    'cubic-meter-per-hour',
    'cubic-kilometer-per-second',
    'teaspoon-per-second',
    'tablespoon-per-second',
    'cubic-inch-per-second',
    'cubic-inch-per-minute',
    'cubic-inch-per-hour',
    'fluid-ounce-per-second',
    'fluid-ounce-per-minute',
    'fluid-ounce-per-hour',
    'cup-per-second',
    'pint-per-second',
    'pint-per-minute',
    'pint-per-hour',
    'quart-per-second',
    'gallon-per-second',
    'gallon-per-minute',
    'gallon-per-hour',
    'cubic-foot-per-second',
    'cubic-foot-per-minute',
    'cubic-foot-per-hour',
    'cubic-yard-per-second',
    'cubic-yard-per-minute',
    'cubic-yard-per-hour',
  ]
export const CONVERSION_UNIT_CUBIC_INCH_PER_MINUTE: ReadonlyArray<ConversionUnitCubicInchPerMinute> =
  [
    'cubic-millimeter-per-second',
    'cubic-centimeter-per-second',
    'millilitre-per-second',
    'centilitre-per-second',
    'decilitre-per-second',
    'litre-per-second',
    'litre-per-minute',
    'litre-per-hour',
    'kilolitre-per-second',
    'kilolitre-per-minute',
    'kilolitre-per-hour',
    'cubic-meter-per-second',
    'cubic-meter-per-minute',
    'cubic-meter-per-hour',
    'cubic-kilometer-per-second',
    'teaspoon-per-second',
    'tablespoon-per-second',
    'cubic-inch-per-second',
    'cubic-inch-per-minute',
    'cubic-inch-per-hour',
    'fluid-ounce-per-second',
    'fluid-ounce-per-minute',
    'fluid-ounce-per-hour',
    'cup-per-second',
    'pint-per-second',
    'pint-per-minute',
    'pint-per-hour',
    'quart-per-second',
    'gallon-per-second',
    'gallon-per-minute',
    'gallon-per-hour',
    'cubic-foot-per-second',
    'cubic-foot-per-minute',
    'cubic-foot-per-hour',
    'cubic-yard-per-second',
    'cubic-yard-per-minute',
    'cubic-yard-per-hour',
  ]
export const CONVERSION_UNIT_CUBIC_INCH_PER_SECOND: ReadonlyArray<ConversionUnitCubicInchPerSecond> =
  [
    'cubic-millimeter-per-second',
    'cubic-centimeter-per-second',
    'millilitre-per-second',
    'centilitre-per-second',
    'decilitre-per-second',
    'litre-per-second',
    'litre-per-minute',
    'litre-per-hour',
    'kilolitre-per-second',
    'kilolitre-per-minute',
    'kilolitre-per-hour',
    'cubic-meter-per-second',
    'cubic-meter-per-minute',
    'cubic-meter-per-hour',
    'cubic-kilometer-per-second',
    'teaspoon-per-second',
    'tablespoon-per-second',
    'cubic-inch-per-second',
    'cubic-inch-per-minute',
    'cubic-inch-per-hour',
    'fluid-ounce-per-second',
    'fluid-ounce-per-minute',
    'fluid-ounce-per-hour',
    'cup-per-second',
    'pint-per-second',
    'pint-per-minute',
    'pint-per-hour',
    'quart-per-second',
    'gallon-per-second',
    'gallon-per-minute',
    'gallon-per-hour',
    'cubic-foot-per-second',
    'cubic-foot-per-minute',
    'cubic-foot-per-hour',
    'cubic-yard-per-second',
    'cubic-yard-per-minute',
    'cubic-yard-per-hour',
  ]
export const CONVERSION_UNIT_CUBIC_KILOMETER: ReadonlyArray<ConversionUnitCubicKilometer> =
  [
    'cubic-millimeter',
    'cubic-centimeter',
    'millilitre',
    'centilitre',
    'decilitre',
    'litre',
    'kilolitre',
    'cubic-meter',
    'cubic-kilometer',
    'tesked',
    'matsked',
    'kaffekopp',
    'glas',
    'kanna',
    'teaspoon',
    'tablespoon',
    'cubic-inch',
    'fluid-ounce',
    'cup',
    'pint',
    'quart',
    'gallon',
    'cubic-foot',
    'cubic-yard',
  ]
export const CONVERSION_UNIT_CUBIC_KILOMETER_PER_SECOND: ReadonlyArray<ConversionUnitCubicKilometerPerSecond> =
  [
    'cubic-millimeter-per-second',
    'cubic-centimeter-per-second',
    'millilitre-per-second',
    'centilitre-per-second',
    'decilitre-per-second',
    'litre-per-second',
    'litre-per-minute',
    'litre-per-hour',
    'kilolitre-per-second',
    'kilolitre-per-minute',
    'kilolitre-per-hour',
    'cubic-meter-per-second',
    'cubic-meter-per-minute',
    'cubic-meter-per-hour',
    'cubic-kilometer-per-second',
    'teaspoon-per-second',
    'tablespoon-per-second',
    'cubic-inch-per-second',
    'cubic-inch-per-minute',
    'cubic-inch-per-hour',
    'fluid-ounce-per-second',
    'fluid-ounce-per-minute',
    'fluid-ounce-per-hour',
    'cup-per-second',
    'pint-per-second',
    'pint-per-minute',
    'pint-per-hour',
    'quart-per-second',
    'gallon-per-second',
    'gallon-per-minute',
    'gallon-per-hour',
    'cubic-foot-per-second',
    'cubic-foot-per-minute',
    'cubic-foot-per-hour',
    'cubic-yard-per-second',
    'cubic-yard-per-minute',
    'cubic-yard-per-hour',
  ]
export const CONVERSION_UNIT_CUBIC_METER: ReadonlyArray<ConversionUnitCubicMeter> =
  [
    'cubic-millimeter',
    'cubic-centimeter',
    'millilitre',
    'centilitre',
    'decilitre',
    'litre',
    'kilolitre',
    'cubic-meter',
    'cubic-kilometer',
    'tesked',
    'matsked',
    'kaffekopp',
    'glas',
    'kanna',
    'teaspoon',
    'tablespoon',
    'cubic-inch',
    'fluid-ounce',
    'cup',
    'pint',
    'quart',
    'gallon',
    'cubic-foot',
    'cubic-yard',
  ]
export const CONVERSION_UNIT_CUBIC_METER_PER_HOUR: ReadonlyArray<ConversionUnitCubicMeterPerHour> =
  [
    'cubic-millimeter-per-second',
    'cubic-centimeter-per-second',
    'millilitre-per-second',
    'centilitre-per-second',
    'decilitre-per-second',
    'litre-per-second',
    'litre-per-minute',
    'litre-per-hour',
    'kilolitre-per-second',
    'kilolitre-per-minute',
    'kilolitre-per-hour',
    'cubic-meter-per-second',
    'cubic-meter-per-minute',
    'cubic-meter-per-hour',
    'cubic-kilometer-per-second',
    'teaspoon-per-second',
    'tablespoon-per-second',
    'cubic-inch-per-second',
    'cubic-inch-per-minute',
    'cubic-inch-per-hour',
    'fluid-ounce-per-second',
    'fluid-ounce-per-minute',
    'fluid-ounce-per-hour',
    'cup-per-second',
    'pint-per-second',
    'pint-per-minute',
    'pint-per-hour',
    'quart-per-second',
    'gallon-per-second',
    'gallon-per-minute',
    'gallon-per-hour',
    'cubic-foot-per-second',
    'cubic-foot-per-minute',
    'cubic-foot-per-hour',
    'cubic-yard-per-second',
    'cubic-yard-per-minute',
    'cubic-yard-per-hour',
  ]
export const CONVERSION_UNIT_CUBIC_METER_PER_MINUTE: ReadonlyArray<ConversionUnitCubicMeterPerMinute> =
  [
    'cubic-millimeter-per-second',
    'cubic-centimeter-per-second',
    'millilitre-per-second',
    'centilitre-per-second',
    'decilitre-per-second',
    'litre-per-second',
    'litre-per-minute',
    'litre-per-hour',
    'kilolitre-per-second',
    'kilolitre-per-minute',
    'kilolitre-per-hour',
    'cubic-meter-per-second',
    'cubic-meter-per-minute',
    'cubic-meter-per-hour',
    'cubic-kilometer-per-second',
    'teaspoon-per-second',
    'tablespoon-per-second',
    'cubic-inch-per-second',
    'cubic-inch-per-minute',
    'cubic-inch-per-hour',
    'fluid-ounce-per-second',
    'fluid-ounce-per-minute',
    'fluid-ounce-per-hour',
    'cup-per-second',
    'pint-per-second',
    'pint-per-minute',
    'pint-per-hour',
    'quart-per-second',
    'gallon-per-second',
    'gallon-per-minute',
    'gallon-per-hour',
    'cubic-foot-per-second',
    'cubic-foot-per-minute',
    'cubic-foot-per-hour',
    'cubic-yard-per-second',
    'cubic-yard-per-minute',
    'cubic-yard-per-hour',
  ]
export const CONVERSION_UNIT_CUBIC_METER_PER_SECOND: ReadonlyArray<ConversionUnitCubicMeterPerSecond> =
  [
    'cubic-millimeter-per-second',
    'cubic-centimeter-per-second',
    'millilitre-per-second',
    'centilitre-per-second',
    'decilitre-per-second',
    'litre-per-second',
    'litre-per-minute',
    'litre-per-hour',
    'kilolitre-per-second',
    'kilolitre-per-minute',
    'kilolitre-per-hour',
    'cubic-meter-per-second',
    'cubic-meter-per-minute',
    'cubic-meter-per-hour',
    'cubic-kilometer-per-second',
    'teaspoon-per-second',
    'tablespoon-per-second',
    'cubic-inch-per-second',
    'cubic-inch-per-minute',
    'cubic-inch-per-hour',
    'fluid-ounce-per-second',
    'fluid-ounce-per-minute',
    'fluid-ounce-per-hour',
    'cup-per-second',
    'pint-per-second',
    'pint-per-minute',
    'pint-per-hour',
    'quart-per-second',
    'gallon-per-second',
    'gallon-per-minute',
    'gallon-per-hour',
    'cubic-foot-per-second',
    'cubic-foot-per-minute',
    'cubic-foot-per-hour',
    'cubic-yard-per-second',
    'cubic-yard-per-minute',
    'cubic-yard-per-hour',
  ]
export const CONVERSION_UNIT_CUBIC_MILLIMETER: ReadonlyArray<ConversionUnitCubicMillimeter> =
  [
    'cubic-millimeter',
    'cubic-centimeter',
    'millilitre',
    'centilitre',
    'decilitre',
    'litre',
    'kilolitre',
    'cubic-meter',
    'cubic-kilometer',
    'tesked',
    'matsked',
    'kaffekopp',
    'glas',
    'kanna',
    'teaspoon',
    'tablespoon',
    'cubic-inch',
    'fluid-ounce',
    'cup',
    'pint',
    'quart',
    'gallon',
    'cubic-foot',
    'cubic-yard',
  ]
export const CONVERSION_UNIT_CUBIC_MILLIMETER_PER_SECOND: ReadonlyArray<ConversionUnitCubicMillimeterPerSecond> =
  [
    'cubic-millimeter-per-second',
    'cubic-centimeter-per-second',
    'millilitre-per-second',
    'centilitre-per-second',
    'decilitre-per-second',
    'litre-per-second',
    'litre-per-minute',
    'litre-per-hour',
    'kilolitre-per-second',
    'kilolitre-per-minute',
    'kilolitre-per-hour',
    'cubic-meter-per-second',
    'cubic-meter-per-minute',
    'cubic-meter-per-hour',
    'cubic-kilometer-per-second',
    'teaspoon-per-second',
    'tablespoon-per-second',
    'cubic-inch-per-second',
    'cubic-inch-per-minute',
    'cubic-inch-per-hour',
    'fluid-ounce-per-second',
    'fluid-ounce-per-minute',
    'fluid-ounce-per-hour',
    'cup-per-second',
    'pint-per-second',
    'pint-per-minute',
    'pint-per-hour',
    'quart-per-second',
    'gallon-per-second',
    'gallon-per-minute',
    'gallon-per-hour',
    'cubic-foot-per-second',
    'cubic-foot-per-minute',
    'cubic-foot-per-hour',
    'cubic-yard-per-second',
    'cubic-yard-per-minute',
    'cubic-yard-per-hour',
  ]
export const CONVERSION_UNIT_CUBIC_YARD: ReadonlyArray<ConversionUnitCubicYard> =
  [
    'cubic-millimeter',
    'cubic-centimeter',
    'millilitre',
    'centilitre',
    'decilitre',
    'litre',
    'kilolitre',
    'cubic-meter',
    'cubic-kilometer',
    'tesked',
    'matsked',
    'kaffekopp',
    'glas',
    'kanna',
    'teaspoon',
    'tablespoon',
    'cubic-inch',
    'fluid-ounce',
    'cup',
    'pint',
    'quart',
    'gallon',
    'cubic-foot',
    'cubic-yard',
  ]
export const CONVERSION_UNIT_CUBIC_YARD_PER_HOUR: ReadonlyArray<ConversionUnitCubicYardPerHour> =
  [
    'cubic-millimeter-per-second',
    'cubic-centimeter-per-second',
    'millilitre-per-second',
    'centilitre-per-second',
    'decilitre-per-second',
    'litre-per-second',
    'litre-per-minute',
    'litre-per-hour',
    'kilolitre-per-second',
    'kilolitre-per-minute',
    'kilolitre-per-hour',
    'cubic-meter-per-second',
    'cubic-meter-per-minute',
    'cubic-meter-per-hour',
    'cubic-kilometer-per-second',
    'teaspoon-per-second',
    'tablespoon-per-second',
    'cubic-inch-per-second',
    'cubic-inch-per-minute',
    'cubic-inch-per-hour',
    'fluid-ounce-per-second',
    'fluid-ounce-per-minute',
    'fluid-ounce-per-hour',
    'cup-per-second',
    'pint-per-second',
    'pint-per-minute',
    'pint-per-hour',
    'quart-per-second',
    'gallon-per-second',
    'gallon-per-minute',
    'gallon-per-hour',
    'cubic-foot-per-second',
    'cubic-foot-per-minute',
    'cubic-foot-per-hour',
    'cubic-yard-per-second',
    'cubic-yard-per-minute',
    'cubic-yard-per-hour',
  ]
export const CONVERSION_UNIT_CUBIC_YARD_PER_MINUTE: ReadonlyArray<ConversionUnitCubicYardPerMinute> =
  [
    'cubic-millimeter-per-second',
    'cubic-centimeter-per-second',
    'millilitre-per-second',
    'centilitre-per-second',
    'decilitre-per-second',
    'litre-per-second',
    'litre-per-minute',
    'litre-per-hour',
    'kilolitre-per-second',
    'kilolitre-per-minute',
    'kilolitre-per-hour',
    'cubic-meter-per-second',
    'cubic-meter-per-minute',
    'cubic-meter-per-hour',
    'cubic-kilometer-per-second',
    'teaspoon-per-second',
    'tablespoon-per-second',
    'cubic-inch-per-second',
    'cubic-inch-per-minute',
    'cubic-inch-per-hour',
    'fluid-ounce-per-second',
    'fluid-ounce-per-minute',
    'fluid-ounce-per-hour',
    'cup-per-second',
    'pint-per-second',
    'pint-per-minute',
    'pint-per-hour',
    'quart-per-second',
    'gallon-per-second',
    'gallon-per-minute',
    'gallon-per-hour',
    'cubic-foot-per-second',
    'cubic-foot-per-minute',
    'cubic-foot-per-hour',
    'cubic-yard-per-second',
    'cubic-yard-per-minute',
    'cubic-yard-per-hour',
  ]
export const CONVERSION_UNIT_CUBIC_YARD_PER_SECOND: ReadonlyArray<ConversionUnitCubicYardPerSecond> =
  [
    'cubic-millimeter-per-second',
    'cubic-centimeter-per-second',
    'millilitre-per-second',
    'centilitre-per-second',
    'decilitre-per-second',
    'litre-per-second',
    'litre-per-minute',
    'litre-per-hour',
    'kilolitre-per-second',
    'kilolitre-per-minute',
    'kilolitre-per-hour',
    'cubic-meter-per-second',
    'cubic-meter-per-minute',
    'cubic-meter-per-hour',
    'cubic-kilometer-per-second',
    'teaspoon-per-second',
    'tablespoon-per-second',
    'cubic-inch-per-second',
    'cubic-inch-per-minute',
    'cubic-inch-per-hour',
    'fluid-ounce-per-second',
    'fluid-ounce-per-minute',
    'fluid-ounce-per-hour',
    'cup-per-second',
    'pint-per-second',
    'pint-per-minute',
    'pint-per-hour',
    'quart-per-second',
    'gallon-per-second',
    'gallon-per-minute',
    'gallon-per-hour',
    'cubic-foot-per-second',
    'cubic-foot-per-minute',
    'cubic-foot-per-hour',
    'cubic-yard-per-second',
    'cubic-yard-per-minute',
    'cubic-yard-per-hour',
  ]
export const CONVERSION_UNIT_CUP: ReadonlyArray<ConversionUnitCup> = [
  'cubic-millimeter',
  'cubic-centimeter',
  'millilitre',
  'centilitre',
  'decilitre',
  'litre',
  'kilolitre',
  'cubic-meter',
  'cubic-kilometer',
  'tesked',
  'matsked',
  'kaffekopp',
  'glas',
  'kanna',
  'teaspoon',
  'tablespoon',
  'cubic-inch',
  'fluid-ounce',
  'cup',
  'pint',
  'quart',
  'gallon',
  'cubic-foot',
  'cubic-yard',
]
export const CONVERSION_UNIT_CUP_PER_SECOND: ReadonlyArray<ConversionUnitCupPerSecond> =
  [
    'cubic-millimeter-per-second',
    'cubic-centimeter-per-second',
    'millilitre-per-second',
    'centilitre-per-second',
    'decilitre-per-second',
    'litre-per-second',
    'litre-per-minute',
    'litre-per-hour',
    'kilolitre-per-second',
    'kilolitre-per-minute',
    'kilolitre-per-hour',
    'cubic-meter-per-second',
    'cubic-meter-per-minute',
    'cubic-meter-per-hour',
    'cubic-kilometer-per-second',
    'teaspoon-per-second',
    'tablespoon-per-second',
    'cubic-inch-per-second',
    'cubic-inch-per-minute',
    'cubic-inch-per-hour',
    'fluid-ounce-per-second',
    'fluid-ounce-per-minute',
    'fluid-ounce-per-hour',
    'cup-per-second',
    'pint-per-second',
    'pint-per-minute',
    'pint-per-hour',
    'quart-per-second',
    'gallon-per-second',
    'gallon-per-minute',
    'gallon-per-hour',
    'cubic-foot-per-second',
    'cubic-foot-per-minute',
    'cubic-foot-per-hour',
    'cubic-yard-per-second',
    'cubic-yard-per-minute',
    'cubic-yard-per-hour',
  ]
export const CONVERSION_UNIT_DAY: ReadonlyArray<ConversionUnitDay> = [
  'nanosecond',
  'microsecond',
  'millisecond',
  'second',
  'minute',
  'hour',
  'day',
  'week',
  'month',
  'year',
]
export const CONVERSION_UNIT_DECILITRE: ReadonlyArray<ConversionUnitDecilitre> =
  [
    'cubic-millimeter',
    'cubic-centimeter',
    'millilitre',
    'centilitre',
    'decilitre',
    'litre',
    'kilolitre',
    'cubic-meter',
    'cubic-kilometer',
    'tesked',
    'matsked',
    'kaffekopp',
    'glas',
    'kanna',
    'teaspoon',
    'tablespoon',
    'cubic-inch',
    'fluid-ounce',
    'cup',
    'pint',
    'quart',
    'gallon',
    'cubic-foot',
    'cubic-yard',
  ]
export const CONVERSION_UNIT_DECILITRE_PER_SECOND: ReadonlyArray<ConversionUnitDecilitrePerSecond> =
  [
    'cubic-millimeter-per-second',
    'cubic-centimeter-per-second',
    'millilitre-per-second',
    'centilitre-per-second',
    'decilitre-per-second',
    'litre-per-second',
    'litre-per-minute',
    'litre-per-hour',
    'kilolitre-per-second',
    'kilolitre-per-minute',
    'kilolitre-per-hour',
    'cubic-meter-per-second',
    'cubic-meter-per-minute',
    'cubic-meter-per-hour',
    'cubic-kilometer-per-second',
    'teaspoon-per-second',
    'tablespoon-per-second',
    'cubic-inch-per-second',
    'cubic-inch-per-minute',
    'cubic-inch-per-hour',
    'fluid-ounce-per-second',
    'fluid-ounce-per-minute',
    'fluid-ounce-per-hour',
    'cup-per-second',
    'pint-per-second',
    'pint-per-minute',
    'pint-per-hour',
    'quart-per-second',
    'gallon-per-second',
    'gallon-per-minute',
    'gallon-per-hour',
    'cubic-foot-per-second',
    'cubic-foot-per-minute',
    'cubic-foot-per-hour',
    'cubic-yard-per-second',
    'cubic-yard-per-minute',
    'cubic-yard-per-hour',
  ]
export const CONVERSION_UNIT_DEGREE: ReadonlyArray<ConversionUnitDegree> =
  ['radian', 'degree', 'gradian', 'arcminute', 'arcsecond']
export const CONVERSION_UNIT_DEGREE_PER_SECOND: ReadonlyArray<ConversionUnitDegreePerSecond> =
  [
    'millihertz',
    'hertz',
    'kilohertz',
    'megahertz',
    'gigahertz',
    'terahertz',
    'rotation-per-minute',
    'degree-per-second',
    'radian-per-second',
  ]
export const CONVERSION_UNIT_DOZEN: ReadonlyArray<ConversionUnitDozen> =
  ['each', 'dozen']
export const CONVERSION_UNIT_EACH: ReadonlyArray<ConversionUnitEach> = [
  'each',
  'dozen',
]
export const CONVERSION_UNIT_FAHRENHEIT: ReadonlyArray<ConversionUnitFahrenheit> =
  ['celsius', 'kelvin', 'fahrenheit', 'rankine']
export const CONVERSION_UNIT_FLUID_OUNCE: ReadonlyArray<ConversionUnitFluidOunce> =
  [
    'cubic-millimeter',
    'cubic-centimeter',
    'millilitre',
    'centilitre',
    'decilitre',
    'litre',
    'kilolitre',
    'cubic-meter',
    'cubic-kilometer',
    'tesked',
    'matsked',
    'kaffekopp',
    'glas',
    'kanna',
    'teaspoon',
    'tablespoon',
    'cubic-inch',
    'fluid-ounce',
    'cup',
    'pint',
    'quart',
    'gallon',
    'cubic-foot',
    'cubic-yard',
  ]
export const CONVERSION_UNIT_FLUID_OUNCE_PER_HOUR: ReadonlyArray<ConversionUnitFluidOuncePerHour> =
  [
    'cubic-millimeter-per-second',
    'cubic-centimeter-per-second',
    'millilitre-per-second',
    'centilitre-per-second',
    'decilitre-per-second',
    'litre-per-second',
    'litre-per-minute',
    'litre-per-hour',
    'kilolitre-per-second',
    'kilolitre-per-minute',
    'kilolitre-per-hour',
    'cubic-meter-per-second',
    'cubic-meter-per-minute',
    'cubic-meter-per-hour',
    'cubic-kilometer-per-second',
    'teaspoon-per-second',
    'tablespoon-per-second',
    'cubic-inch-per-second',
    'cubic-inch-per-minute',
    'cubic-inch-per-hour',
    'fluid-ounce-per-second',
    'fluid-ounce-per-minute',
    'fluid-ounce-per-hour',
    'cup-per-second',
    'pint-per-second',
    'pint-per-minute',
    'pint-per-hour',
    'quart-per-second',
    'gallon-per-second',
    'gallon-per-minute',
    'gallon-per-hour',
    'cubic-foot-per-second',
    'cubic-foot-per-minute',
    'cubic-foot-per-hour',
    'cubic-yard-per-second',
    'cubic-yard-per-minute',
    'cubic-yard-per-hour',
  ]
export const CONVERSION_UNIT_FLUID_OUNCE_PER_MINUTE: ReadonlyArray<ConversionUnitFluidOuncePerMinute> =
  [
    'cubic-millimeter-per-second',
    'cubic-centimeter-per-second',
    'millilitre-per-second',
    'centilitre-per-second',
    'decilitre-per-second',
    'litre-per-second',
    'litre-per-minute',
    'litre-per-hour',
    'kilolitre-per-second',
    'kilolitre-per-minute',
    'kilolitre-per-hour',
    'cubic-meter-per-second',
    'cubic-meter-per-minute',
    'cubic-meter-per-hour',
    'cubic-kilometer-per-second',
    'teaspoon-per-second',
    'tablespoon-per-second',
    'cubic-inch-per-second',
    'cubic-inch-per-minute',
    'cubic-inch-per-hour',
    'fluid-ounce-per-second',
    'fluid-ounce-per-minute',
    'fluid-ounce-per-hour',
    'cup-per-second',
    'pint-per-second',
    'pint-per-minute',
    'pint-per-hour',
    'quart-per-second',
    'gallon-per-second',
    'gallon-per-minute',
    'gallon-per-hour',
    'cubic-foot-per-second',
    'cubic-foot-per-minute',
    'cubic-foot-per-hour',
    'cubic-yard-per-second',
    'cubic-yard-per-minute',
    'cubic-yard-per-hour',
  ]
export const CONVERSION_UNIT_FLUID_OUNCE_PER_SECOND: ReadonlyArray<ConversionUnitFluidOuncePerSecond> =
  [
    'cubic-millimeter-per-second',
    'cubic-centimeter-per-second',
    'millilitre-per-second',
    'centilitre-per-second',
    'decilitre-per-second',
    'litre-per-second',
    'litre-per-minute',
    'litre-per-hour',
    'kilolitre-per-second',
    'kilolitre-per-minute',
    'kilolitre-per-hour',
    'cubic-meter-per-second',
    'cubic-meter-per-minute',
    'cubic-meter-per-hour',
    'cubic-kilometer-per-second',
    'teaspoon-per-second',
    'tablespoon-per-second',
    'cubic-inch-per-second',
    'cubic-inch-per-minute',
    'cubic-inch-per-hour',
    'fluid-ounce-per-second',
    'fluid-ounce-per-minute',
    'fluid-ounce-per-hour',
    'cup-per-second',
    'pint-per-second',
    'pint-per-minute',
    'pint-per-hour',
    'quart-per-second',
    'gallon-per-second',
    'gallon-per-minute',
    'gallon-per-hour',
    'cubic-foot-per-second',
    'cubic-foot-per-minute',
    'cubic-foot-per-hour',
    'cubic-yard-per-second',
    'cubic-yard-per-minute',
    'cubic-yard-per-hour',
  ]
export const CONVERSION_UNIT_FOOT: ReadonlyArray<ConversionUnitFoot> = [
  'millimeter',
  'centimeter',
  'meter',
  'kilometer',
  'inch',
  'yard',
  'us-survey-foot',
  'foot',
  'mile',
]
export const CONVERSION_UNIT_FOOT_CANDLE: ReadonlyArray<ConversionUnitFootCandle> =
  ['lux', 'foot-candle']
export const CONVERSION_UNIT_FOOT_PER_SECOND: ReadonlyArray<ConversionUnitFootPerSecond> =
  [
    'metre-per-second',
    'kilometre-per-hour',
    'mile-per-hour',
    'knot',
    'foot-per-second',
  ]
export const CONVERSION_UNIT_GALLON: ReadonlyArray<ConversionUnitGallon> =
  [
    'cubic-millimeter',
    'cubic-centimeter',
    'millilitre',
    'centilitre',
    'decilitre',
    'litre',
    'kilolitre',
    'cubic-meter',
    'cubic-kilometer',
    'tesked',
    'matsked',
    'kaffekopp',
    'glas',
    'kanna',
    'teaspoon',
    'tablespoon',
    'cubic-inch',
    'fluid-ounce',
    'cup',
    'pint',
    'quart',
    'gallon',
    'cubic-foot',
    'cubic-yard',
  ]
export const CONVERSION_UNIT_GALLON_PER_HOUR: ReadonlyArray<ConversionUnitGallonPerHour> =
  [
    'cubic-millimeter-per-second',
    'cubic-centimeter-per-second',
    'millilitre-per-second',
    'centilitre-per-second',
    'decilitre-per-second',
    'litre-per-second',
    'litre-per-minute',
    'litre-per-hour',
    'kilolitre-per-second',
    'kilolitre-per-minute',
    'kilolitre-per-hour',
    'cubic-meter-per-second',
    'cubic-meter-per-minute',
    'cubic-meter-per-hour',
    'cubic-kilometer-per-second',
    'teaspoon-per-second',
    'tablespoon-per-second',
    'cubic-inch-per-second',
    'cubic-inch-per-minute',
    'cubic-inch-per-hour',
    'fluid-ounce-per-second',
    'fluid-ounce-per-minute',
    'fluid-ounce-per-hour',
    'cup-per-second',
    'pint-per-second',
    'pint-per-minute',
    'pint-per-hour',
    'quart-per-second',
    'gallon-per-second',
    'gallon-per-minute',
    'gallon-per-hour',
    'cubic-foot-per-second',
    'cubic-foot-per-minute',
    'cubic-foot-per-hour',
    'cubic-yard-per-second',
    'cubic-yard-per-minute',
    'cubic-yard-per-hour',
  ]
export const CONVERSION_UNIT_GALLON_PER_MINUTE: ReadonlyArray<ConversionUnitGallonPerMinute> =
  [
    'cubic-millimeter-per-second',
    'cubic-centimeter-per-second',
    'millilitre-per-second',
    'centilitre-per-second',
    'decilitre-per-second',
    'litre-per-second',
    'litre-per-minute',
    'litre-per-hour',
    'kilolitre-per-second',
    'kilolitre-per-minute',
    'kilolitre-per-hour',
    'cubic-meter-per-second',
    'cubic-meter-per-minute',
    'cubic-meter-per-hour',
    'cubic-kilometer-per-second',
    'teaspoon-per-second',
    'tablespoon-per-second',
    'cubic-inch-per-second',
    'cubic-inch-per-minute',
    'cubic-inch-per-hour',
    'fluid-ounce-per-second',
    'fluid-ounce-per-minute',
    'fluid-ounce-per-hour',
    'cup-per-second',
    'pint-per-second',
    'pint-per-minute',
    'pint-per-hour',
    'quart-per-second',
    'gallon-per-second',
    'gallon-per-minute',
    'gallon-per-hour',
    'cubic-foot-per-second',
    'cubic-foot-per-minute',
    'cubic-foot-per-hour',
    'cubic-yard-per-second',
    'cubic-yard-per-minute',
    'cubic-yard-per-hour',
  ]
export const CONVERSION_UNIT_GALLON_PER_SECOND: ReadonlyArray<ConversionUnitGallonPerSecond> =
  [
    'cubic-millimeter-per-second',
    'cubic-centimeter-per-second',
    'millilitre-per-second',
    'centilitre-per-second',
    'decilitre-per-second',
    'litre-per-second',
    'litre-per-minute',
    'litre-per-hour',
    'kilolitre-per-second',
    'kilolitre-per-minute',
    'kilolitre-per-hour',
    'cubic-meter-per-second',
    'cubic-meter-per-minute',
    'cubic-meter-per-hour',
    'cubic-kilometer-per-second',
    'teaspoon-per-second',
    'tablespoon-per-second',
    'cubic-inch-per-second',
    'cubic-inch-per-minute',
    'cubic-inch-per-hour',
    'fluid-ounce-per-second',
    'fluid-ounce-per-minute',
    'fluid-ounce-per-hour',
    'cup-per-second',
    'pint-per-second',
    'pint-per-minute',
    'pint-per-hour',
    'quart-per-second',
    'gallon-per-second',
    'gallon-per-minute',
    'gallon-per-hour',
    'cubic-foot-per-second',
    'cubic-foot-per-minute',
    'cubic-foot-per-hour',
    'cubic-yard-per-second',
    'cubic-yard-per-minute',
    'cubic-yard-per-hour',
  ]
export const CONVERSION_UNIT_GIGABIT: ReadonlyArray<ConversionUnitGigabit> =
  [
    'bit',
    'kilobit',
    'megabit',
    'gigabit',
    'terabit',
    'byte',
    'kilobyte',
    'megabyte',
    'gigabyte',
    'terabyte',
  ]
export const CONVERSION_UNIT_GIGABYTE: ReadonlyArray<ConversionUnitGigabyte> =
  [
    'bit',
    'kilobit',
    'megabit',
    'gigabit',
    'terabit',
    'byte',
    'kilobyte',
    'megabyte',
    'gigabyte',
    'terabyte',
  ]
export const CONVERSION_UNIT_GIGAHERTZ: ReadonlyArray<ConversionUnitGigahertz> =
  [
    'millihertz',
    'hertz',
    'kilohertz',
    'megahertz',
    'gigahertz',
    'terahertz',
    'rotation-per-minute',
    'degree-per-second',
    'radian-per-second',
  ]
export const CONVERSION_UNIT_GIGAVOLT_AMPERE: ReadonlyArray<ConversionUnitGigavoltAmpere> =
  [
    'volt-ampere',
    'millivolt-ampere',
    'kilovolt-ampere',
    'megavolt-ampere',
    'gigavolt-ampere',
  ]
export const CONVERSION_UNIT_GIGAVOLT_AMPERE_REACTIVE: ReadonlyArray<ConversionUnitGigavoltAmpereReactive> =
  [
    'volt-ampere-reactive',
    'millivolt-ampere-reactive',
    'kilovolt-ampere-reactive',
    'megavolt-ampere-reactive',
    'gigavolt-ampere-reactive',
  ]
export const CONVERSION_UNIT_GIGAVOLT_AMPERE_REACTIVE_HOUR: ReadonlyArray<ConversionUnitGigavoltAmpereReactiveHour> =
  [
    'volt-ampere-reactive-hour',
    'millivolt-ampere-reactive-hour',
    'kilovolt-ampere-reactive-hour',
    'megavolt-ampere-reactive-hour',
    'gigavolt-ampere-reactive-hour',
  ]
export const CONVERSION_UNIT_GIGAWATT: ReadonlyArray<ConversionUnitGigawatt> =
  ['watt', 'milliwatt', 'kilowatt', 'megawatt', 'gigawatt']
export const CONVERSION_UNIT_GIGAWATT_HOUR: ReadonlyArray<ConversionUnitGigawattHour> =
  [
    'watt-hour',
    'milliwatt-hour',
    'kilowatt-hour',
    'megawatt-hour',
    'gigawatt-hour',
    'joule',
    'kilojoule',
  ]
export const CONVERSION_UNIT_GLAS: ReadonlyArray<ConversionUnitGlas> = [
  'cubic-millimeter',
  'cubic-centimeter',
  'millilitre',
  'centilitre',
  'decilitre',
  'litre',
  'kilolitre',
  'cubic-meter',
  'cubic-kilometer',
  'tesked',
  'matsked',
  'kaffekopp',
  'glas',
  'kanna',
  'teaspoon',
  'tablespoon',
  'cubic-inch',
  'fluid-ounce',
  'cup',
  'pint',
  'quart',
  'gallon',
  'cubic-foot',
  'cubic-yard',
]
export const CONVERSION_UNIT_GRADIAN: ReadonlyArray<ConversionUnitGradian> =
  ['radian', 'degree', 'gradian', 'arcminute', 'arcsecond']
export const CONVERSION_UNIT_GRAM: ReadonlyArray<ConversionUnitGram> = [
  'microgram',
  'milligram',
  'gram',
  'kilogram',
  'metric-tonne',
  'ounce',
  'pound',
  'ton',
]
export const CONVERSION_UNIT_HECTARE: ReadonlyArray<ConversionUnitHectare> =
  [
    'square-millimeter',
    'square-centimeter',
    'square-meter',
    'hectare',
    'square-kilometer',
    'square-inch',
    'square-yard',
    'square-foot',
    'acre',
    'square-mile',
  ]
export const CONVERSION_UNIT_HECTOPASCAL: ReadonlyArray<ConversionUnitHectopascal> =
  [
    'pascal',
    'kilopascal',
    'megapascal',
    'hectopascal',
    'bar',
    'torr',
    'pound-per-square-inch',
    'kilopound-per-square-inch',
  ]
export const CONVERSION_UNIT_HERTZ: ReadonlyArray<ConversionUnitHertz> =
  [
    'millihertz',
    'hertz',
    'kilohertz',
    'megahertz',
    'gigahertz',
    'terahertz',
    'rotation-per-minute',
    'degree-per-second',
    'radian-per-second',
  ]
export const CONVERSION_UNIT_HOUR: ReadonlyArray<ConversionUnitHour> = [
  'nanosecond',
  'microsecond',
  'millisecond',
  'second',
  'minute',
  'hour',
  'day',
  'week',
  'month',
  'year',
]
export const CONVERSION_UNIT_INCH: ReadonlyArray<ConversionUnitInch> = [
  'millimeter',
  'centimeter',
  'meter',
  'kilometer',
  'inch',
  'yard',
  'us-survey-foot',
  'foot',
  'mile',
]
export const CONVERSION_UNIT_JOULE: ReadonlyArray<ConversionUnitJoule> =
  [
    'watt-hour',
    'milliwatt-hour',
    'kilowatt-hour',
    'megawatt-hour',
    'gigawatt-hour',
    'joule',
    'kilojoule',
  ]
export const CONVERSION_UNIT_KAFFEKOPP: ReadonlyArray<ConversionUnitKaffekopp> =
  [
    'cubic-millimeter',
    'cubic-centimeter',
    'millilitre',
    'centilitre',
    'decilitre',
    'litre',
    'kilolitre',
    'cubic-meter',
    'cubic-kilometer',
    'tesked',
    'matsked',
    'kaffekopp',
    'glas',
    'kanna',
    'teaspoon',
    'tablespoon',
    'cubic-inch',
    'fluid-ounce',
    'cup',
    'pint',
    'quart',
    'gallon',
    'cubic-foot',
    'cubic-yard',
  ]
export const CONVERSION_UNIT_KANNA: ReadonlyArray<ConversionUnitKanna> =
  [
    'cubic-millimeter',
    'cubic-centimeter',
    'millilitre',
    'centilitre',
    'decilitre',
    'litre',
    'kilolitre',
    'cubic-meter',
    'cubic-kilometer',
    'tesked',
    'matsked',
    'kaffekopp',
    'glas',
    'kanna',
    'teaspoon',
    'tablespoon',
    'cubic-inch',
    'fluid-ounce',
    'cup',
    'pint',
    'quart',
    'gallon',
    'cubic-foot',
    'cubic-yard',
  ]
export const CONVERSION_UNIT_KELVIN: ReadonlyArray<ConversionUnitKelvin> =
  ['celsius', 'kelvin', 'fahrenheit', 'rankine']
export const CONVERSION_UNIT_KILOAMPERE: ReadonlyArray<ConversionUnitKiloampere> =
  ['ampere', 'milliampere', 'kiloampere']
export const CONVERSION_UNIT_KILOBIT: ReadonlyArray<ConversionUnitKilobit> =
  [
    'bit',
    'kilobit',
    'megabit',
    'gigabit',
    'terabit',
    'byte',
    'kilobyte',
    'megabyte',
    'gigabyte',
    'terabyte',
  ]
export const CONVERSION_UNIT_KILOBYTE: ReadonlyArray<ConversionUnitKilobyte> =
  [
    'bit',
    'kilobit',
    'megabit',
    'gigabit',
    'terabit',
    'byte',
    'kilobyte',
    'megabyte',
    'gigabyte',
    'terabyte',
  ]
export const CONVERSION_UNIT_KILOGRAM: ReadonlyArray<ConversionUnitKilogram> =
  [
    'microgram',
    'milligram',
    'gram',
    'kilogram',
    'metric-tonne',
    'ounce',
    'pound',
    'ton',
  ]
export const CONVERSION_UNIT_KILOHERTZ: ReadonlyArray<ConversionUnitKilohertz> =
  [
    'millihertz',
    'hertz',
    'kilohertz',
    'megahertz',
    'gigahertz',
    'terahertz',
    'rotation-per-minute',
    'degree-per-second',
    'radian-per-second',
  ]
export const CONVERSION_UNIT_KILOJOULE: ReadonlyArray<ConversionUnitKilojoule> =
  [
    'watt-hour',
    'milliwatt-hour',
    'kilowatt-hour',
    'megawatt-hour',
    'gigawatt-hour',
    'joule',
    'kilojoule',
  ]
export const CONVERSION_UNIT_KILOLITRE: ReadonlyArray<ConversionUnitKilolitre> =
  [
    'cubic-millimeter',
    'cubic-centimeter',
    'millilitre',
    'centilitre',
    'decilitre',
    'litre',
    'kilolitre',
    'cubic-meter',
    'cubic-kilometer',
    'tesked',
    'matsked',
    'kaffekopp',
    'glas',
    'kanna',
    'teaspoon',
    'tablespoon',
    'cubic-inch',
    'fluid-ounce',
    'cup',
    'pint',
    'quart',
    'gallon',
    'cubic-foot',
    'cubic-yard',
  ]
export const CONVERSION_UNIT_KILOLITRE_PER_HOUR: ReadonlyArray<ConversionUnitKilolitrePerHour> =
  [
    'cubic-millimeter-per-second',
    'cubic-centimeter-per-second',
    'millilitre-per-second',
    'centilitre-per-second',
    'decilitre-per-second',
    'litre-per-second',
    'litre-per-minute',
    'litre-per-hour',
    'kilolitre-per-second',
    'kilolitre-per-minute',
    'kilolitre-per-hour',
    'cubic-meter-per-second',
    'cubic-meter-per-minute',
    'cubic-meter-per-hour',
    'cubic-kilometer-per-second',
    'teaspoon-per-second',
    'tablespoon-per-second',
    'cubic-inch-per-second',
    'cubic-inch-per-minute',
    'cubic-inch-per-hour',
    'fluid-ounce-per-second',
    'fluid-ounce-per-minute',
    'fluid-ounce-per-hour',
    'cup-per-second',
    'pint-per-second',
    'pint-per-minute',
    'pint-per-hour',
    'quart-per-second',
    'gallon-per-second',
    'gallon-per-minute',
    'gallon-per-hour',
    'cubic-foot-per-second',
    'cubic-foot-per-minute',
    'cubic-foot-per-hour',
    'cubic-yard-per-second',
    'cubic-yard-per-minute',
    'cubic-yard-per-hour',
  ]
export const CONVERSION_UNIT_KILOLITRE_PER_MINUTE: ReadonlyArray<ConversionUnitKilolitrePerMinute> =
  [
    'cubic-millimeter-per-second',
    'cubic-centimeter-per-second',
    'millilitre-per-second',
    'centilitre-per-second',
    'decilitre-per-second',
    'litre-per-second',
    'litre-per-minute',
    'litre-per-hour',
    'kilolitre-per-second',
    'kilolitre-per-minute',
    'kilolitre-per-hour',
    'cubic-meter-per-second',
    'cubic-meter-per-minute',
    'cubic-meter-per-hour',
    'cubic-kilometer-per-second',
    'teaspoon-per-second',
    'tablespoon-per-second',
    'cubic-inch-per-second',
    'cubic-inch-per-minute',
    'cubic-inch-per-hour',
    'fluid-ounce-per-second',
    'fluid-ounce-per-minute',
    'fluid-ounce-per-hour',
    'cup-per-second',
    'pint-per-second',
    'pint-per-minute',
    'pint-per-hour',
    'quart-per-second',
    'gallon-per-second',
    'gallon-per-minute',
    'gallon-per-hour',
    'cubic-foot-per-second',
    'cubic-foot-per-minute',
    'cubic-foot-per-hour',
    'cubic-yard-per-second',
    'cubic-yard-per-minute',
    'cubic-yard-per-hour',
  ]
export const CONVERSION_UNIT_KILOLITRE_PER_SECOND: ReadonlyArray<ConversionUnitKilolitrePerSecond> =
  [
    'cubic-millimeter-per-second',
    'cubic-centimeter-per-second',
    'millilitre-per-second',
    'centilitre-per-second',
    'decilitre-per-second',
    'litre-per-second',
    'litre-per-minute',
    'litre-per-hour',
    'kilolitre-per-second',
    'kilolitre-per-minute',
    'kilolitre-per-hour',
    'cubic-meter-per-second',
    'cubic-meter-per-minute',
    'cubic-meter-per-hour',
    'cubic-kilometer-per-second',
    'teaspoon-per-second',
    'tablespoon-per-second',
    'cubic-inch-per-second',
    'cubic-inch-per-minute',
    'cubic-inch-per-hour',
    'fluid-ounce-per-second',
    'fluid-ounce-per-minute',
    'fluid-ounce-per-hour',
    'cup-per-second',
    'pint-per-second',
    'pint-per-minute',
    'pint-per-hour',
    'quart-per-second',
    'gallon-per-second',
    'gallon-per-minute',
    'gallon-per-hour',
    'cubic-foot-per-second',
    'cubic-foot-per-minute',
    'cubic-foot-per-hour',
    'cubic-yard-per-second',
    'cubic-yard-per-minute',
    'cubic-yard-per-hour',
  ]
export const CONVERSION_UNIT_KILOMETER: ReadonlyArray<ConversionUnitKilometer> =
  [
    'millimeter',
    'centimeter',
    'meter',
    'kilometer',
    'inch',
    'yard',
    'us-survey-foot',
    'foot',
    'mile',
  ]
export const CONVERSION_UNIT_KILOMETRE_PER_HOUR: ReadonlyArray<ConversionUnitKilometrePerHour> =
  [
    'metre-per-second',
    'kilometre-per-hour',
    'mile-per-hour',
    'knot',
    'foot-per-second',
  ]
export const CONVERSION_UNIT_KILOPASCAL: ReadonlyArray<ConversionUnitKilopascal> =
  [
    'pascal',
    'kilopascal',
    'megapascal',
    'hectopascal',
    'bar',
    'torr',
    'pound-per-square-inch',
    'kilopound-per-square-inch',
  ]
export const CONVERSION_UNIT_KILOPOUND_PER_SQUARE_INCH: ReadonlyArray<ConversionUnitKilopoundPerSquareInch> =
  [
    'pascal',
    'kilopascal',
    'megapascal',
    'hectopascal',
    'bar',
    'torr',
    'pound-per-square-inch',
    'kilopound-per-square-inch',
  ]
export const CONVERSION_UNIT_KILOVOLT: ReadonlyArray<ConversionUnitKilovolt> =
  ['volt', 'millivolt', 'kilovolt']
export const CONVERSION_UNIT_KILOVOLT_AMPERE: ReadonlyArray<ConversionUnitKilovoltAmpere> =
  [
    'volt-ampere',
    'millivolt-ampere',
    'kilovolt-ampere',
    'megavolt-ampere',
    'gigavolt-ampere',
  ]
export const CONVERSION_UNIT_KILOVOLT_AMPERE_REACTIVE: ReadonlyArray<ConversionUnitKilovoltAmpereReactive> =
  [
    'volt-ampere-reactive',
    'millivolt-ampere-reactive',
    'kilovolt-ampere-reactive',
    'megavolt-ampere-reactive',
    'gigavolt-ampere-reactive',
  ]
export const CONVERSION_UNIT_KILOVOLT_AMPERE_REACTIVE_HOUR: ReadonlyArray<ConversionUnitKilovoltAmpereReactiveHour> =
  [
    'volt-ampere-reactive-hour',
    'millivolt-ampere-reactive-hour',
    'kilovolt-ampere-reactive-hour',
    'megavolt-ampere-reactive-hour',
    'gigavolt-ampere-reactive-hour',
  ]
export const CONVERSION_UNIT_KILOWATT: ReadonlyArray<ConversionUnitKilowatt> =
  ['watt', 'milliwatt', 'kilowatt', 'megawatt', 'gigawatt']
export const CONVERSION_UNIT_KILOWATT_HOUR: ReadonlyArray<ConversionUnitKilowattHour> =
  [
    'watt-hour',
    'milliwatt-hour',
    'kilowatt-hour',
    'megawatt-hour',
    'gigawatt-hour',
    'joule',
    'kilojoule',
  ]
export const CONVERSION_UNIT_KNOT: ReadonlyArray<ConversionUnitKnot> = [
  'metre-per-second',
  'kilometre-per-hour',
  'mile-per-hour',
  'knot',
  'foot-per-second',
]
export const CONVERSION_UNIT_LITRE: ReadonlyArray<ConversionUnitLitre> =
  [
    'cubic-millimeter',
    'cubic-centimeter',
    'millilitre',
    'centilitre',
    'decilitre',
    'litre',
    'kilolitre',
    'cubic-meter',
    'cubic-kilometer',
    'tesked',
    'matsked',
    'kaffekopp',
    'glas',
    'kanna',
    'teaspoon',
    'tablespoon',
    'cubic-inch',
    'fluid-ounce',
    'cup',
    'pint',
    'quart',
    'gallon',
    'cubic-foot',
    'cubic-yard',
  ]
export const CONVERSION_UNIT_LITRE_PER_HOUR: ReadonlyArray<ConversionUnitLitrePerHour> =
  [
    'cubic-millimeter-per-second',
    'cubic-centimeter-per-second',
    'millilitre-per-second',
    'centilitre-per-second',
    'decilitre-per-second',
    'litre-per-second',
    'litre-per-minute',
    'litre-per-hour',
    'kilolitre-per-second',
    'kilolitre-per-minute',
    'kilolitre-per-hour',
    'cubic-meter-per-second',
    'cubic-meter-per-minute',
    'cubic-meter-per-hour',
    'cubic-kilometer-per-second',
    'teaspoon-per-second',
    'tablespoon-per-second',
    'cubic-inch-per-second',
    'cubic-inch-per-minute',
    'cubic-inch-per-hour',
    'fluid-ounce-per-second',
    'fluid-ounce-per-minute',
    'fluid-ounce-per-hour',
    'cup-per-second',
    'pint-per-second',
    'pint-per-minute',
    'pint-per-hour',
    'quart-per-second',
    'gallon-per-second',
    'gallon-per-minute',
    'gallon-per-hour',
    'cubic-foot-per-second',
    'cubic-foot-per-minute',
    'cubic-foot-per-hour',
    'cubic-yard-per-second',
    'cubic-yard-per-minute',
    'cubic-yard-per-hour',
  ]
export const CONVERSION_UNIT_LITRE_PER_MINUTE: ReadonlyArray<ConversionUnitLitrePerMinute> =
  [
    'cubic-millimeter-per-second',
    'cubic-centimeter-per-second',
    'millilitre-per-second',
    'centilitre-per-second',
    'decilitre-per-second',
    'litre-per-second',
    'litre-per-minute',
    'litre-per-hour',
    'kilolitre-per-second',
    'kilolitre-per-minute',
    'kilolitre-per-hour',
    'cubic-meter-per-second',
    'cubic-meter-per-minute',
    'cubic-meter-per-hour',
    'cubic-kilometer-per-second',
    'teaspoon-per-second',
    'tablespoon-per-second',
    'cubic-inch-per-second',
    'cubic-inch-per-minute',
    'cubic-inch-per-hour',
    'fluid-ounce-per-second',
    'fluid-ounce-per-minute',
    'fluid-ounce-per-hour',
    'cup-per-second',
    'pint-per-second',
    'pint-per-minute',
    'pint-per-hour',
    'quart-per-second',
    'gallon-per-second',
    'gallon-per-minute',
    'gallon-per-hour',
    'cubic-foot-per-second',
    'cubic-foot-per-minute',
    'cubic-foot-per-hour',
    'cubic-yard-per-second',
    'cubic-yard-per-minute',
    'cubic-yard-per-hour',
  ]
export const CONVERSION_UNIT_LITRE_PER_SECOND: ReadonlyArray<ConversionUnitLitrePerSecond> =
  [
    'cubic-millimeter-per-second',
    'cubic-centimeter-per-second',
    'millilitre-per-second',
    'centilitre-per-second',
    'decilitre-per-second',
    'litre-per-second',
    'litre-per-minute',
    'litre-per-hour',
    'kilolitre-per-second',
    'kilolitre-per-minute',
    'kilolitre-per-hour',
    'cubic-meter-per-second',
    'cubic-meter-per-minute',
    'cubic-meter-per-hour',
    'cubic-kilometer-per-second',
    'teaspoon-per-second',
    'tablespoon-per-second',
    'cubic-inch-per-second',
    'cubic-inch-per-minute',
    'cubic-inch-per-hour',
    'fluid-ounce-per-second',
    'fluid-ounce-per-minute',
    'fluid-ounce-per-hour',
    'cup-per-second',
    'pint-per-second',
    'pint-per-minute',
    'pint-per-hour',
    'quart-per-second',
    'gallon-per-second',
    'gallon-per-minute',
    'gallon-per-hour',
    'cubic-foot-per-second',
    'cubic-foot-per-minute',
    'cubic-foot-per-hour',
    'cubic-yard-per-second',
    'cubic-yard-per-minute',
    'cubic-yard-per-hour',
  ]
export const CONVERSION_UNIT_LUX: ReadonlyArray<ConversionUnitLux> = [
  'lux',
  'foot-candle',
]
export const CONVERSION_UNIT_MATSKED: ReadonlyArray<ConversionUnitMatsked> =
  [
    'cubic-millimeter',
    'cubic-centimeter',
    'millilitre',
    'centilitre',
    'decilitre',
    'litre',
    'kilolitre',
    'cubic-meter',
    'cubic-kilometer',
    'tesked',
    'matsked',
    'kaffekopp',
    'glas',
    'kanna',
    'teaspoon',
    'tablespoon',
    'cubic-inch',
    'fluid-ounce',
    'cup',
    'pint',
    'quart',
    'gallon',
    'cubic-foot',
    'cubic-yard',
  ]
export const CONVERSION_UNIT_MEGABIT: ReadonlyArray<ConversionUnitMegabit> =
  [
    'bit',
    'kilobit',
    'megabit',
    'gigabit',
    'terabit',
    'byte',
    'kilobyte',
    'megabyte',
    'gigabyte',
    'terabyte',
  ]
export const CONVERSION_UNIT_MEGABYTE: ReadonlyArray<ConversionUnitMegabyte> =
  [
    'bit',
    'kilobit',
    'megabit',
    'gigabit',
    'terabit',
    'byte',
    'kilobyte',
    'megabyte',
    'gigabyte',
    'terabyte',
  ]
export const CONVERSION_UNIT_MEGAHERTZ: ReadonlyArray<ConversionUnitMegahertz> =
  [
    'millihertz',
    'hertz',
    'kilohertz',
    'megahertz',
    'gigahertz',
    'terahertz',
    'rotation-per-minute',
    'degree-per-second',
    'radian-per-second',
  ]
export const CONVERSION_UNIT_MEGAPASCAL: ReadonlyArray<ConversionUnitMegapascal> =
  [
    'pascal',
    'kilopascal',
    'megapascal',
    'hectopascal',
    'bar',
    'torr',
    'pound-per-square-inch',
    'kilopound-per-square-inch',
  ]
export const CONVERSION_UNIT_MEGAVOLT_AMPERE: ReadonlyArray<ConversionUnitMegavoltAmpere> =
  [
    'volt-ampere',
    'millivolt-ampere',
    'kilovolt-ampere',
    'megavolt-ampere',
    'gigavolt-ampere',
  ]
export const CONVERSION_UNIT_MEGAVOLT_AMPERE_REACTIVE: ReadonlyArray<ConversionUnitMegavoltAmpereReactive> =
  [
    'volt-ampere-reactive',
    'millivolt-ampere-reactive',
    'kilovolt-ampere-reactive',
    'megavolt-ampere-reactive',
    'gigavolt-ampere-reactive',
  ]
export const CONVERSION_UNIT_MEGAVOLT_AMPERE_REACTIVE_HOUR: ReadonlyArray<ConversionUnitMegavoltAmpereReactiveHour> =
  [
    'volt-ampere-reactive-hour',
    'millivolt-ampere-reactive-hour',
    'kilovolt-ampere-reactive-hour',
    'megavolt-ampere-reactive-hour',
    'gigavolt-ampere-reactive-hour',
  ]
export const CONVERSION_UNIT_MEGAWATT: ReadonlyArray<ConversionUnitMegawatt> =
  ['watt', 'milliwatt', 'kilowatt', 'megawatt', 'gigawatt']
export const CONVERSION_UNIT_MEGAWATT_HOUR: ReadonlyArray<ConversionUnitMegawattHour> =
  [
    'watt-hour',
    'milliwatt-hour',
    'kilowatt-hour',
    'megawatt-hour',
    'gigawatt-hour',
    'joule',
    'kilojoule',
  ]
export const CONVERSION_UNIT_METER: ReadonlyArray<ConversionUnitMeter> =
  [
    'millimeter',
    'centimeter',
    'meter',
    'kilometer',
    'inch',
    'yard',
    'us-survey-foot',
    'foot',
    'mile',
  ]
export const CONVERSION_UNIT_METRE_PER_SECOND: ReadonlyArray<ConversionUnitMetrePerSecond> =
  [
    'metre-per-second',
    'kilometre-per-hour',
    'mile-per-hour',
    'knot',
    'foot-per-second',
  ]
export const CONVERSION_UNIT_METRIC_TONNE: ReadonlyArray<ConversionUnitMetricTonne> =
  [
    'microgram',
    'milligram',
    'gram',
    'kilogram',
    'metric-tonne',
    'ounce',
    'pound',
    'ton',
  ]
export const CONVERSION_UNIT_MICROGRAM: ReadonlyArray<ConversionUnitMicrogram> =
  [
    'microgram',
    'milligram',
    'gram',
    'kilogram',
    'metric-tonne',
    'ounce',
    'pound',
    'ton',
  ]
export const CONVERSION_UNIT_MICROSECOND: ReadonlyArray<ConversionUnitMicrosecond> =
  [
    'nanosecond',
    'microsecond',
    'millisecond',
    'second',
    'minute',
    'hour',
    'day',
    'week',
    'month',
    'year',
  ]
export const CONVERSION_UNIT_MILE: ReadonlyArray<ConversionUnitMile> = [
  'millimeter',
  'centimeter',
  'meter',
  'kilometer',
  'inch',
  'yard',
  'us-survey-foot',
  'foot',
  'mile',
]
export const CONVERSION_UNIT_MILE_PER_HOUR: ReadonlyArray<ConversionUnitMilePerHour> =
  [
    'metre-per-second',
    'kilometre-per-hour',
    'mile-per-hour',
    'knot',
    'foot-per-second',
  ]
export const CONVERSION_UNIT_MILLIAMPERE: ReadonlyArray<ConversionUnitMilliampere> =
  ['ampere', 'milliampere', 'kiloampere']
export const CONVERSION_UNIT_MILLIGRAM: ReadonlyArray<ConversionUnitMilligram> =
  [
    'microgram',
    'milligram',
    'gram',
    'kilogram',
    'metric-tonne',
    'ounce',
    'pound',
    'ton',
  ]
export const CONVERSION_UNIT_MILLIHERTZ: ReadonlyArray<ConversionUnitMillihertz> =
  [
    'millihertz',
    'hertz',
    'kilohertz',
    'megahertz',
    'gigahertz',
    'terahertz',
    'rotation-per-minute',
    'degree-per-second',
    'radian-per-second',
  ]
export const CONVERSION_UNIT_MILLILITRE: ReadonlyArray<ConversionUnitMillilitre> =
  [
    'cubic-millimeter',
    'cubic-centimeter',
    'millilitre',
    'centilitre',
    'decilitre',
    'litre',
    'kilolitre',
    'cubic-meter',
    'cubic-kilometer',
    'tesked',
    'matsked',
    'kaffekopp',
    'glas',
    'kanna',
    'teaspoon',
    'tablespoon',
    'cubic-inch',
    'fluid-ounce',
    'cup',
    'pint',
    'quart',
    'gallon',
    'cubic-foot',
    'cubic-yard',
  ]
export const CONVERSION_UNIT_MILLILITRE_PER_SECOND: ReadonlyArray<ConversionUnitMillilitrePerSecond> =
  [
    'cubic-millimeter-per-second',
    'cubic-centimeter-per-second',
    'millilitre-per-second',
    'centilitre-per-second',
    'decilitre-per-second',
    'litre-per-second',
    'litre-per-minute',
    'litre-per-hour',
    'kilolitre-per-second',
    'kilolitre-per-minute',
    'kilolitre-per-hour',
    'cubic-meter-per-second',
    'cubic-meter-per-minute',
    'cubic-meter-per-hour',
    'cubic-kilometer-per-second',
    'teaspoon-per-second',
    'tablespoon-per-second',
    'cubic-inch-per-second',
    'cubic-inch-per-minute',
    'cubic-inch-per-hour',
    'fluid-ounce-per-second',
    'fluid-ounce-per-minute',
    'fluid-ounce-per-hour',
    'cup-per-second',
    'pint-per-second',
    'pint-per-minute',
    'pint-per-hour',
    'quart-per-second',
    'gallon-per-second',
    'gallon-per-minute',
    'gallon-per-hour',
    'cubic-foot-per-second',
    'cubic-foot-per-minute',
    'cubic-foot-per-hour',
    'cubic-yard-per-second',
    'cubic-yard-per-minute',
    'cubic-yard-per-hour',
  ]
export const CONVERSION_UNIT_MILLIMETER: ReadonlyArray<ConversionUnitMillimeter> =
  [
    'millimeter',
    'centimeter',
    'meter',
    'kilometer',
    'inch',
    'yard',
    'us-survey-foot',
    'foot',
    'mile',
  ]
export const CONVERSION_UNIT_MILLISECOND: ReadonlyArray<ConversionUnitMillisecond> =
  [
    'nanosecond',
    'microsecond',
    'millisecond',
    'second',
    'minute',
    'hour',
    'day',
    'week',
    'month',
    'year',
  ]
export const CONVERSION_UNIT_MILLIVOLT: ReadonlyArray<ConversionUnitMillivolt> =
  ['volt', 'millivolt', 'kilovolt']
export const CONVERSION_UNIT_MILLIVOLT_AMPERE: ReadonlyArray<ConversionUnitMillivoltAmpere> =
  [
    'volt-ampere',
    'millivolt-ampere',
    'kilovolt-ampere',
    'megavolt-ampere',
    'gigavolt-ampere',
  ]
export const CONVERSION_UNIT_MILLIVOLT_AMPERE_REACTIVE: ReadonlyArray<ConversionUnitMillivoltAmpereReactive> =
  [
    'volt-ampere-reactive',
    'millivolt-ampere-reactive',
    'kilovolt-ampere-reactive',
    'megavolt-ampere-reactive',
    'gigavolt-ampere-reactive',
  ]
export const CONVERSION_UNIT_MILLIVOLT_AMPERE_REACTIVE_HOUR: ReadonlyArray<ConversionUnitMillivoltAmpereReactiveHour> =
  [
    'volt-ampere-reactive-hour',
    'millivolt-ampere-reactive-hour',
    'kilovolt-ampere-reactive-hour',
    'megavolt-ampere-reactive-hour',
    'gigavolt-ampere-reactive-hour',
  ]
export const CONVERSION_UNIT_MILLIWATT: ReadonlyArray<ConversionUnitMilliwatt> =
  ['watt', 'milliwatt', 'kilowatt', 'megawatt', 'gigawatt']
export const CONVERSION_UNIT_MILLIWATT_HOUR: ReadonlyArray<ConversionUnitMilliwattHour> =
  [
    'watt-hour',
    'milliwatt-hour',
    'kilowatt-hour',
    'megawatt-hour',
    'gigawatt-hour',
    'joule',
    'kilojoule',
  ]
export const CONVERSION_UNIT_MINUTE: ReadonlyArray<ConversionUnitMinute> =
  [
    'nanosecond',
    'microsecond',
    'millisecond',
    'second',
    'minute',
    'hour',
    'day',
    'week',
    'month',
    'year',
  ]
export const CONVERSION_UNIT_MINUTE_PER_KILOMETRE: ReadonlyArray<ConversionUnitMinutePerKilometre> =
  [
    'minute-per-kilometre',
    'second-per-metre',
    'minute-per-mile',
    'second-per-foot',
  ]
export const CONVERSION_UNIT_MINUTE_PER_MILE: ReadonlyArray<ConversionUnitMinutePerMile> =
  [
    'minute-per-kilometre',
    'second-per-metre',
    'minute-per-mile',
    'second-per-foot',
  ]
export const CONVERSION_UNIT_MONTH: ReadonlyArray<ConversionUnitMonth> =
  [
    'nanosecond',
    'microsecond',
    'millisecond',
    'second',
    'minute',
    'hour',
    'day',
    'week',
    'month',
    'year',
  ]
export const CONVERSION_UNIT_NANOSECOND: ReadonlyArray<ConversionUnitNanosecond> =
  [
    'nanosecond',
    'microsecond',
    'millisecond',
    'second',
    'minute',
    'hour',
    'day',
    'week',
    'month',
    'year',
  ]
export const CONVERSION_UNIT_OUNCE: ReadonlyArray<ConversionUnitOunce> =
  [
    'microgram',
    'milligram',
    'gram',
    'kilogram',
    'metric-tonne',
    'ounce',
    'pound',
    'ton',
  ]
export const CONVERSION_UNIT_PART_PER_BILLION: ReadonlyArray<ConversionUnitPartPerBillion> =
  [
    'part-per-million',
    'part-per-billion',
    'part-per-trillion',
    'part-per-quadrillion',
  ]
export const CONVERSION_UNIT_PART_PER_MILLION: ReadonlyArray<ConversionUnitPartPerMillion> =
  [
    'part-per-million',
    'part-per-billion',
    'part-per-trillion',
    'part-per-quadrillion',
  ]
export const CONVERSION_UNIT_PART_PER_QUADRILLION: ReadonlyArray<ConversionUnitPartPerQuadrillion> =
  [
    'part-per-million',
    'part-per-billion',
    'part-per-trillion',
    'part-per-quadrillion',
  ]
export const CONVERSION_UNIT_PART_PER_TRILLION: ReadonlyArray<ConversionUnitPartPerTrillion> =
  [
    'part-per-million',
    'part-per-billion',
    'part-per-trillion',
    'part-per-quadrillion',
  ]
export const CONVERSION_UNIT_PASCAL: ReadonlyArray<ConversionUnitPascal> =
  [
    'pascal',
    'kilopascal',
    'megapascal',
    'hectopascal',
    'bar',
    'torr',
    'pound-per-square-inch',
    'kilopound-per-square-inch',
  ]
export const CONVERSION_UNIT_PINT: ReadonlyArray<ConversionUnitPint> = [
  'cubic-millimeter',
  'cubic-centimeter',
  'millilitre',
  'centilitre',
  'decilitre',
  'litre',
  'kilolitre',
  'cubic-meter',
  'cubic-kilometer',
  'tesked',
  'matsked',
  'kaffekopp',
  'glas',
  'kanna',
  'teaspoon',
  'tablespoon',
  'cubic-inch',
  'fluid-ounce',
  'cup',
  'pint',
  'quart',
  'gallon',
  'cubic-foot',
  'cubic-yard',
]
export const CONVERSION_UNIT_PINT_PER_HOUR: ReadonlyArray<ConversionUnitPintPerHour> =
  [
    'cubic-millimeter-per-second',
    'cubic-centimeter-per-second',
    'millilitre-per-second',
    'centilitre-per-second',
    'decilitre-per-second',
    'litre-per-second',
    'litre-per-minute',
    'litre-per-hour',
    'kilolitre-per-second',
    'kilolitre-per-minute',
    'kilolitre-per-hour',
    'cubic-meter-per-second',
    'cubic-meter-per-minute',
    'cubic-meter-per-hour',
    'cubic-kilometer-per-second',
    'teaspoon-per-second',
    'tablespoon-per-second',
    'cubic-inch-per-second',
    'cubic-inch-per-minute',
    'cubic-inch-per-hour',
    'fluid-ounce-per-second',
    'fluid-ounce-per-minute',
    'fluid-ounce-per-hour',
    'cup-per-second',
    'pint-per-second',
    'pint-per-minute',
    'pint-per-hour',
    'quart-per-second',
    'gallon-per-second',
    'gallon-per-minute',
    'gallon-per-hour',
    'cubic-foot-per-second',
    'cubic-foot-per-minute',
    'cubic-foot-per-hour',
    'cubic-yard-per-second',
    'cubic-yard-per-minute',
    'cubic-yard-per-hour',
  ]
export const CONVERSION_UNIT_PINT_PER_MINUTE: ReadonlyArray<ConversionUnitPintPerMinute> =
  [
    'cubic-millimeter-per-second',
    'cubic-centimeter-per-second',
    'millilitre-per-second',
    'centilitre-per-second',
    'decilitre-per-second',
    'litre-per-second',
    'litre-per-minute',
    'litre-per-hour',
    'kilolitre-per-second',
    'kilolitre-per-minute',
    'kilolitre-per-hour',
    'cubic-meter-per-second',
    'cubic-meter-per-minute',
    'cubic-meter-per-hour',
    'cubic-kilometer-per-second',
    'teaspoon-per-second',
    'tablespoon-per-second',
    'cubic-inch-per-second',
    'cubic-inch-per-minute',
    'cubic-inch-per-hour',
    'fluid-ounce-per-second',
    'fluid-ounce-per-minute',
    'fluid-ounce-per-hour',
    'cup-per-second',
    'pint-per-second',
    'pint-per-minute',
    'pint-per-hour',
    'quart-per-second',
    'gallon-per-second',
    'gallon-per-minute',
    'gallon-per-hour',
    'cubic-foot-per-second',
    'cubic-foot-per-minute',
    'cubic-foot-per-hour',
    'cubic-yard-per-second',
    'cubic-yard-per-minute',
    'cubic-yard-per-hour',
  ]
export const CONVERSION_UNIT_PINT_PER_SECOND: ReadonlyArray<ConversionUnitPintPerSecond> =
  [
    'cubic-millimeter-per-second',
    'cubic-centimeter-per-second',
    'millilitre-per-second',
    'centilitre-per-second',
    'decilitre-per-second',
    'litre-per-second',
    'litre-per-minute',
    'litre-per-hour',
    'kilolitre-per-second',
    'kilolitre-per-minute',
    'kilolitre-per-hour',
    'cubic-meter-per-second',
    'cubic-meter-per-minute',
    'cubic-meter-per-hour',
    'cubic-kilometer-per-second',
    'teaspoon-per-second',
    'tablespoon-per-second',
    'cubic-inch-per-second',
    'cubic-inch-per-minute',
    'cubic-inch-per-hour',
    'fluid-ounce-per-second',
    'fluid-ounce-per-minute',
    'fluid-ounce-per-hour',
    'cup-per-second',
    'pint-per-second',
    'pint-per-minute',
    'pint-per-hour',
    'quart-per-second',
    'gallon-per-second',
    'gallon-per-minute',
    'gallon-per-hour',
    'cubic-foot-per-second',
    'cubic-foot-per-minute',
    'cubic-foot-per-hour',
    'cubic-yard-per-second',
    'cubic-yard-per-minute',
    'cubic-yard-per-hour',
  ]
export const CONVERSION_UNIT_POUND: ReadonlyArray<ConversionUnitPound> =
  [
    'microgram',
    'milligram',
    'gram',
    'kilogram',
    'metric-tonne',
    'ounce',
    'pound',
    'ton',
  ]
export const CONVERSION_UNIT_POUND_PER_SQUARE_INCH: ReadonlyArray<ConversionUnitPoundPerSquareInch> =
  [
    'pascal',
    'kilopascal',
    'megapascal',
    'hectopascal',
    'bar',
    'torr',
    'pound-per-square-inch',
    'kilopound-per-square-inch',
  ]
export const CONVERSION_UNIT_QUART: ReadonlyArray<ConversionUnitQuart> =
  [
    'cubic-millimeter',
    'cubic-centimeter',
    'millilitre',
    'centilitre',
    'decilitre',
    'litre',
    'kilolitre',
    'cubic-meter',
    'cubic-kilometer',
    'tesked',
    'matsked',
    'kaffekopp',
    'glas',
    'kanna',
    'teaspoon',
    'tablespoon',
    'cubic-inch',
    'fluid-ounce',
    'cup',
    'pint',
    'quart',
    'gallon',
    'cubic-foot',
    'cubic-yard',
  ]
export const CONVERSION_UNIT_QUART_PER_SECOND: ReadonlyArray<ConversionUnitQuartPerSecond> =
  [
    'cubic-millimeter-per-second',
    'cubic-centimeter-per-second',
    'millilitre-per-second',
    'centilitre-per-second',
    'decilitre-per-second',
    'litre-per-second',
    'litre-per-minute',
    'litre-per-hour',
    'kilolitre-per-second',
    'kilolitre-per-minute',
    'kilolitre-per-hour',
    'cubic-meter-per-second',
    'cubic-meter-per-minute',
    'cubic-meter-per-hour',
    'cubic-kilometer-per-second',
    'teaspoon-per-second',
    'tablespoon-per-second',
    'cubic-inch-per-second',
    'cubic-inch-per-minute',
    'cubic-inch-per-hour',
    'fluid-ounce-per-second',
    'fluid-ounce-per-minute',
    'fluid-ounce-per-hour',
    'cup-per-second',
    'pint-per-second',
    'pint-per-minute',
    'pint-per-hour',
    'quart-per-second',
    'gallon-per-second',
    'gallon-per-minute',
    'gallon-per-hour',
    'cubic-foot-per-second',
    'cubic-foot-per-minute',
    'cubic-foot-per-hour',
    'cubic-yard-per-second',
    'cubic-yard-per-minute',
    'cubic-yard-per-hour',
  ]
export const CONVERSION_UNIT_RADIAN: ReadonlyArray<ConversionUnitRadian> =
  ['radian', 'degree', 'gradian', 'arcminute', 'arcsecond']
export const CONVERSION_UNIT_RADIAN_PER_SECOND: ReadonlyArray<ConversionUnitRadianPerSecond> =
  [
    'millihertz',
    'hertz',
    'kilohertz',
    'megahertz',
    'gigahertz',
    'terahertz',
    'rotation-per-minute',
    'degree-per-second',
    'radian-per-second',
  ]
export const CONVERSION_UNIT_RANKINE: ReadonlyArray<ConversionUnitRankine> =
  ['celsius', 'kelvin', 'fahrenheit', 'rankine']
export const CONVERSION_UNIT_ROTATION_PER_MINUTE: ReadonlyArray<ConversionUnitRotationPerMinute> =
  [
    'millihertz',
    'hertz',
    'kilohertz',
    'megahertz',
    'gigahertz',
    'terahertz',
    'rotation-per-minute',
    'degree-per-second',
    'radian-per-second',
  ]
export const CONVERSION_UNIT_SECOND: ReadonlyArray<ConversionUnitSecond> =
  [
    'nanosecond',
    'microsecond',
    'millisecond',
    'second',
    'minute',
    'hour',
    'day',
    'week',
    'month',
    'year',
  ]
export const CONVERSION_UNIT_SECOND_PER_FOOT: ReadonlyArray<ConversionUnitSecondPerFoot> =
  [
    'minute-per-kilometre',
    'second-per-metre',
    'minute-per-mile',
    'second-per-foot',
  ]
export const CONVERSION_UNIT_SECOND_PER_METRE: ReadonlyArray<ConversionUnitSecondPerMetre> =
  [
    'minute-per-kilometre',
    'second-per-metre',
    'minute-per-mile',
    'second-per-foot',
  ]
export const CONVERSION_UNIT_SQUARE_CENTIMETER: ReadonlyArray<ConversionUnitSquareCentimeter> =
  [
    'square-millimeter',
    'square-centimeter',
    'square-meter',
    'hectare',
    'square-kilometer',
    'square-inch',
    'square-yard',
    'square-foot',
    'acre',
    'square-mile',
  ]
export const CONVERSION_UNIT_SQUARE_FOOT: ReadonlyArray<ConversionUnitSquareFoot> =
  [
    'square-millimeter',
    'square-centimeter',
    'square-meter',
    'hectare',
    'square-kilometer',
    'square-inch',
    'square-yard',
    'square-foot',
    'acre',
    'square-mile',
  ]
export const CONVERSION_UNIT_SQUARE_INCH: ReadonlyArray<ConversionUnitSquareInch> =
  [
    'square-millimeter',
    'square-centimeter',
    'square-meter',
    'hectare',
    'square-kilometer',
    'square-inch',
    'square-yard',
    'square-foot',
    'acre',
    'square-mile',
  ]
export const CONVERSION_UNIT_SQUARE_KILOMETER: ReadonlyArray<ConversionUnitSquareKilometer> =
  [
    'square-millimeter',
    'square-centimeter',
    'square-meter',
    'hectare',
    'square-kilometer',
    'square-inch',
    'square-yard',
    'square-foot',
    'acre',
    'square-mile',
  ]
export const CONVERSION_UNIT_SQUARE_METER: ReadonlyArray<ConversionUnitSquareMeter> =
  [
    'square-millimeter',
    'square-centimeter',
    'square-meter',
    'hectare',
    'square-kilometer',
    'square-inch',
    'square-yard',
    'square-foot',
    'acre',
    'square-mile',
  ]
export const CONVERSION_UNIT_SQUARE_MILE: ReadonlyArray<ConversionUnitSquareMile> =
  [
    'square-millimeter',
    'square-centimeter',
    'square-meter',
    'hectare',
    'square-kilometer',
    'square-inch',
    'square-yard',
    'square-foot',
    'acre',
    'square-mile',
  ]
export const CONVERSION_UNIT_SQUARE_MILLIMETER: ReadonlyArray<ConversionUnitSquareMillimeter> =
  [
    'square-millimeter',
    'square-centimeter',
    'square-meter',
    'hectare',
    'square-kilometer',
    'square-inch',
    'square-yard',
    'square-foot',
    'acre',
    'square-mile',
  ]
export const CONVERSION_UNIT_SQUARE_YARD: ReadonlyArray<ConversionUnitSquareYard> =
  [
    'square-millimeter',
    'square-centimeter',
    'square-meter',
    'hectare',
    'square-kilometer',
    'square-inch',
    'square-yard',
    'square-foot',
    'acre',
    'square-mile',
  ]
export const CONVERSION_UNIT_TABLESPOON: ReadonlyArray<ConversionUnitTablespoon> =
  [
    'cubic-millimeter',
    'cubic-centimeter',
    'millilitre',
    'centilitre',
    'decilitre',
    'litre',
    'kilolitre',
    'cubic-meter',
    'cubic-kilometer',
    'tesked',
    'matsked',
    'kaffekopp',
    'glas',
    'kanna',
    'teaspoon',
    'tablespoon',
    'cubic-inch',
    'fluid-ounce',
    'cup',
    'pint',
    'quart',
    'gallon',
    'cubic-foot',
    'cubic-yard',
  ]
export const CONVERSION_UNIT_TABLESPOON_PER_SECOND: ReadonlyArray<ConversionUnitTablespoonPerSecond> =
  [
    'cubic-millimeter-per-second',
    'cubic-centimeter-per-second',
    'millilitre-per-second',
    'centilitre-per-second',
    'decilitre-per-second',
    'litre-per-second',
    'litre-per-minute',
    'litre-per-hour',
    'kilolitre-per-second',
    'kilolitre-per-minute',
    'kilolitre-per-hour',
    'cubic-meter-per-second',
    'cubic-meter-per-minute',
    'cubic-meter-per-hour',
    'cubic-kilometer-per-second',
    'teaspoon-per-second',
    'tablespoon-per-second',
    'cubic-inch-per-second',
    'cubic-inch-per-minute',
    'cubic-inch-per-hour',
    'fluid-ounce-per-second',
    'fluid-ounce-per-minute',
    'fluid-ounce-per-hour',
    'cup-per-second',
    'pint-per-second',
    'pint-per-minute',
    'pint-per-hour',
    'quart-per-second',
    'gallon-per-second',
    'gallon-per-minute',
    'gallon-per-hour',
    'cubic-foot-per-second',
    'cubic-foot-per-minute',
    'cubic-foot-per-hour',
    'cubic-yard-per-second',
    'cubic-yard-per-minute',
    'cubic-yard-per-hour',
  ]
export const CONVERSION_UNIT_TEASPOON: ReadonlyArray<ConversionUnitTeaspoon> =
  [
    'cubic-millimeter',
    'cubic-centimeter',
    'millilitre',
    'centilitre',
    'decilitre',
    'litre',
    'kilolitre',
    'cubic-meter',
    'cubic-kilometer',
    'tesked',
    'matsked',
    'kaffekopp',
    'glas',
    'kanna',
    'teaspoon',
    'tablespoon',
    'cubic-inch',
    'fluid-ounce',
    'cup',
    'pint',
    'quart',
    'gallon',
    'cubic-foot',
    'cubic-yard',
  ]
export const CONVERSION_UNIT_TEASPOON_PER_SECOND: ReadonlyArray<ConversionUnitTeaspoonPerSecond> =
  [
    'cubic-millimeter-per-second',
    'cubic-centimeter-per-second',
    'millilitre-per-second',
    'centilitre-per-second',
    'decilitre-per-second',
    'litre-per-second',
    'litre-per-minute',
    'litre-per-hour',
    'kilolitre-per-second',
    'kilolitre-per-minute',
    'kilolitre-per-hour',
    'cubic-meter-per-second',
    'cubic-meter-per-minute',
    'cubic-meter-per-hour',
    'cubic-kilometer-per-second',
    'teaspoon-per-second',
    'tablespoon-per-second',
    'cubic-inch-per-second',
    'cubic-inch-per-minute',
    'cubic-inch-per-hour',
    'fluid-ounce-per-second',
    'fluid-ounce-per-minute',
    'fluid-ounce-per-hour',
    'cup-per-second',
    'pint-per-second',
    'pint-per-minute',
    'pint-per-hour',
    'quart-per-second',
    'gallon-per-second',
    'gallon-per-minute',
    'gallon-per-hour',
    'cubic-foot-per-second',
    'cubic-foot-per-minute',
    'cubic-foot-per-hour',
    'cubic-yard-per-second',
    'cubic-yard-per-minute',
    'cubic-yard-per-hour',
  ]
export const CONVERSION_UNIT_TERABIT: ReadonlyArray<ConversionUnitTerabit> =
  [
    'bit',
    'kilobit',
    'megabit',
    'gigabit',
    'terabit',
    'byte',
    'kilobyte',
    'megabyte',
    'gigabyte',
    'terabyte',
  ]
export const CONVERSION_UNIT_TERABYTE: ReadonlyArray<ConversionUnitTerabyte> =
  [
    'bit',
    'kilobit',
    'megabit',
    'gigabit',
    'terabit',
    'byte',
    'kilobyte',
    'megabyte',
    'gigabyte',
    'terabyte',
  ]
export const CONVERSION_UNIT_TERAHERTZ: ReadonlyArray<ConversionUnitTerahertz> =
  [
    'millihertz',
    'hertz',
    'kilohertz',
    'megahertz',
    'gigahertz',
    'terahertz',
    'rotation-per-minute',
    'degree-per-second',
    'radian-per-second',
  ]
export const CONVERSION_UNIT_TESKED: ReadonlyArray<ConversionUnitTesked> =
  [
    'cubic-millimeter',
    'cubic-centimeter',
    'millilitre',
    'centilitre',
    'decilitre',
    'litre',
    'kilolitre',
    'cubic-meter',
    'cubic-kilometer',
    'tesked',
    'matsked',
    'kaffekopp',
    'glas',
    'kanna',
    'teaspoon',
    'tablespoon',
    'cubic-inch',
    'fluid-ounce',
    'cup',
    'pint',
    'quart',
    'gallon',
    'cubic-foot',
    'cubic-yard',
  ]
export const CONVERSION_UNIT_TON: ReadonlyArray<ConversionUnitTon> = [
  'microgram',
  'milligram',
  'gram',
  'kilogram',
  'metric-tonne',
  'ounce',
  'pound',
  'ton',
]
export const CONVERSION_UNIT_TORR: ReadonlyArray<ConversionUnitTorr> = [
  'pascal',
  'kilopascal',
  'megapascal',
  'hectopascal',
  'bar',
  'torr',
  'pound-per-square-inch',
  'kilopound-per-square-inch',
]
export const CONVERSION_UNIT_US_SURVEY_FOOT: ReadonlyArray<ConversionUnitUsSurveyFoot> =
  [
    'millimeter',
    'centimeter',
    'meter',
    'kilometer',
    'inch',
    'yard',
    'us-survey-foot',
    'foot',
    'mile',
  ]
export const CONVERSION_UNIT_VOLT: ReadonlyArray<ConversionUnitVolt> = [
  'volt',
  'millivolt',
  'kilovolt',
]
export const CONVERSION_UNIT_VOLT_AMPERE: ReadonlyArray<ConversionUnitVoltAmpere> =
  [
    'volt-ampere',
    'millivolt-ampere',
    'kilovolt-ampere',
    'megavolt-ampere',
    'gigavolt-ampere',
  ]
export const CONVERSION_UNIT_VOLT_AMPERE_REACTIVE: ReadonlyArray<ConversionUnitVoltAmpereReactive> =
  [
    'volt-ampere-reactive',
    'millivolt-ampere-reactive',
    'kilovolt-ampere-reactive',
    'megavolt-ampere-reactive',
    'gigavolt-ampere-reactive',
  ]
export const CONVERSION_UNIT_VOLT_AMPERE_REACTIVE_HOUR: ReadonlyArray<ConversionUnitVoltAmpereReactiveHour> =
  [
    'volt-ampere-reactive-hour',
    'millivolt-ampere-reactive-hour',
    'kilovolt-ampere-reactive-hour',
    'megavolt-ampere-reactive-hour',
    'gigavolt-ampere-reactive-hour',
  ]
export const CONVERSION_UNIT_WATT: ReadonlyArray<ConversionUnitWatt> = [
  'watt',
  'milliwatt',
  'kilowatt',
  'megawatt',
  'gigawatt',
]
export const CONVERSION_UNIT_WATT_HOUR: ReadonlyArray<ConversionUnitWattHour> =
  [
    'watt-hour',
    'milliwatt-hour',
    'kilowatt-hour',
    'megawatt-hour',
    'gigawatt-hour',
    'joule',
    'kilojoule',
  ]
export const CONVERSION_UNIT_WEEK: ReadonlyArray<ConversionUnitWeek> = [
  'nanosecond',
  'microsecond',
  'millisecond',
  'second',
  'minute',
  'hour',
  'day',
  'week',
  'month',
  'year',
]
export const CONVERSION_UNIT_YARD: ReadonlyArray<ConversionUnitYard> = [
  'millimeter',
  'centimeter',
  'meter',
  'kilometer',
  'inch',
  'yard',
  'us-survey-foot',
  'foot',
  'mile',
]
export const CONVERSION_UNIT_YEAR: ReadonlyArray<ConversionUnitYear> = [
  'nanosecond',
  'microsecond',
  'millisecond',
  'second',
  'minute',
  'hour',
  'day',
  'week',
  'month',
  'year',
]
export const UNIT: ReadonlyArray<Unit> = [
  'millimeter',
  'centimeter',
  'meter',
  'kilometer',
  'inch',
  'yard',
  'us-survey-foot',
  'foot',
  'mile',
  'square-millimeter',
  'square-centimeter',
  'square-meter',
  'hectare',
  'square-kilometer',
  'square-inch',
  'square-yard',
  'square-foot',
  'acre',
  'square-mile',
  'microgram',
  'milligram',
  'gram',
  'kilogram',
  'metric-tonne',
  'ounce',
  'pound',
  'ton',
  'cubic-millimeter',
  'cubic-centimeter',
  'millilitre',
  'centilitre',
  'decilitre',
  'litre',
  'kilolitre',
  'cubic-meter',
  'cubic-kilometer',
  'tesked',
  'matsked',
  'kaffekopp',
  'glas',
  'kanna',
  'teaspoon',
  'tablespoon',
  'cubic-inch',
  'fluid-ounce',
  'cup',
  'pint',
  'quart',
  'gallon',
  'cubic-foot',
  'cubic-yard',
  'each',
  'dozen',
  'celsius',
  'kelvin',
  'fahrenheit',
  'rankine',
  'nanosecond',
  'microsecond',
  'millisecond',
  'second',
  'minute',
  'hour',
  'day',
  'week',
  'month',
  'year',
  'bit',
  'kilobit',
  'megabit',
  'gigabit',
  'terabit',
  'byte',
  'kilobyte',
  'megabyte',
  'gigabyte',
  'terabyte',
  'part-per-million',
  'part-per-billion',
  'part-per-trillion',
  'part-per-quadrillion',
  'metre-per-second',
  'kilometre-per-hour',
  'mile-per-hour',
  'knot',
  'foot-per-second',
  'minute-per-kilometre',
  'second-per-metre',
  'minute-per-mile',
  'second-per-foot',
  'pascal',
  'kilopascal',
  'megapascal',
  'hectopascal',
  'bar',
  'torr',
  'pound-per-square-inch',
  'kilopound-per-square-inch',
  'ampere',
  'milliampere',
  'kiloampere',
  'volt',
  'millivolt',
  'kilovolt',
  'watt',
  'milliwatt',
  'kilowatt',
  'megawatt',
  'gigawatt',
  'volt-ampere-reactive',
  'millivolt-ampere-reactive',
  'kilovolt-ampere-reactive',
  'megavolt-ampere-reactive',
  'gigavolt-ampere-reactive',
  'volt-ampere',
  'millivolt-ampere',
  'kilovolt-ampere',
  'megavolt-ampere',
  'gigavolt-ampere',
  'watt-hour',
  'milliwatt-hour',
  'kilowatt-hour',
  'megawatt-hour',
  'gigawatt-hour',
  'joule',
  'kilojoule',
  'volt-ampere-reactive-hour',
  'millivolt-ampere-reactive-hour',
  'kilovolt-ampere-reactive-hour',
  'megavolt-ampere-reactive-hour',
  'gigavolt-ampere-reactive-hour',
  'cubic-millimeter-per-second',
  'cubic-centimeter-per-second',
  'millilitre-per-second',
  'centilitre-per-second',
  'decilitre-per-second',
  'litre-per-second',
  'litre-per-minute',
  'litre-per-hour',
  'kilolitre-per-second',
  'kilolitre-per-minute',
  'kilolitre-per-hour',
  'cubic-meter-per-second',
  'cubic-meter-per-minute',
  'cubic-meter-per-hour',
  'cubic-kilometer-per-second',
  'teaspoon-per-second',
  'tablespoon-per-second',
  'cubic-inch-per-second',
  'cubic-inch-per-minute',
  'cubic-inch-per-hour',
  'fluid-ounce-per-second',
  'fluid-ounce-per-minute',
  'fluid-ounce-per-hour',
  'cup-per-second',
  'pint-per-second',
  'pint-per-minute',
  'pint-per-hour',
  'quart-per-second',
  'gallon-per-second',
  'gallon-per-minute',
  'gallon-per-hour',
  'cubic-foot-per-second',
  'cubic-foot-per-minute',
  'cubic-foot-per-hour',
  'cubic-yard-per-second',
  'cubic-yard-per-minute',
  'cubic-yard-per-hour',
  'lux',
  'foot-candle',
  'millihertz',
  'hertz',
  'kilohertz',
  'megahertz',
  'gigahertz',
  'terahertz',
  'rotation-per-minute',
  'degree-per-second',
  'radian-per-second',
  'radian',
  'degree',
  'gradian',
  'arcminute',
  'arcsecond',
]

export const UNIT_KEY_HASH: UnitKeyHash = {
  millimeter: {
    key: 'mm',
  },
  centimeter: {
    key: 'cm',
  },
  meter: {
    key: 'm',
  },
  kilometer: {
    key: 'km',
  },
  inch: {
    key: 'in',
  },
  yard: {
    key: 'yd',
  },
  'us-survey-foot': {
    key: 'ft-us',
  },
  foot: {
    key: 'ft',
  },
  mile: {
    key: 'mi',
  },
  'square-millimeter': {
    key: 'mm2',
  },
  'square-centimeter': {
    key: 'cm2',
  },
  'square-meter': {
    key: 'm2',
  },
  hectare: {
    key: 'ha',
  },
  'square-kilometer': {
    key: 'km2',
  },
  'square-inch': {
    key: 'in2',
  },
  'square-yard': {
    key: 'yd2',
  },
  'square-foot': {
    key: 'ft2',
  },
  acre: {
    key: 'ac',
  },
  'square-mile': {
    key: 'mi2',
  },
  microgram: {
    key: 'mcg',
  },
  milligram: {
    key: 'mg',
  },
  gram: {
    key: 'g',
  },
  kilogram: {
    key: 'kg',
  },
  'metric-tonne': {
    key: 'mt',
  },
  ounce: {
    key: 'oz',
  },
  pound: {
    key: 'lb',
  },
  ton: {
    key: 't',
  },
  'cubic-millimeter': {
    key: 'mm3',
  },
  'cubic-centimeter': {
    key: 'cm3',
  },
  millilitre: {
    key: 'ml',
  },
  centilitre: {
    key: 'cl',
  },
  decilitre: {
    key: 'dl',
  },
  litre: {
    key: 'l',
  },
  kilolitre: {
    key: 'kl',
  },
  'cubic-meter': {
    key: 'm3',
  },
  'cubic-kilometer': {
    key: 'km3',
  },
  tesked: {
    key: 'tsk',
  },
  matsked: {
    key: 'msk',
  },
  kaffekopp: {
    key: 'kkp',
  },
  glas: {
    key: 'glas',
  },
  kanna: {
    key: 'kanna',
  },
  teaspoon: {
    key: 'tsp',
  },
  tablespoon: {
    key: 'Tbs',
  },
  'cubic-inch': {
    key: 'in3',
  },
  'fluid-ounce': {
    key: 'fl-oz',
  },
  cup: {
    key: 'cup',
  },
  pint: {
    key: 'pnt',
  },
  quart: {
    key: 'qt',
  },
  gallon: {
    key: 'gal',
  },
  'cubic-foot': {
    key: 'ft3',
  },
  'cubic-yard': {
    key: 'yd3',
  },
  each: {
    key: 'ea',
  },
  dozen: {
    key: 'dz',
  },
  celsius: {
    key: 'C',
  },
  kelvin: {
    key: 'K',
  },
  fahrenheit: {
    key: 'F',
  },
  rankine: {
    key: 'R',
  },
  nanosecond: {
    key: 'ns',
  },
  microsecond: {
    key: 'mu',
  },
  millisecond: {
    key: 'ms',
  },
  second: {
    key: 's',
  },
  minute: {
    key: 'min',
  },
  hour: {
    key: 'h',
  },
  day: {
    key: 'd',
  },
  week: {
    key: 'week',
  },
  month: {
    key: 'month',
  },
  year: {
    key: 'year',
  },
  bit: {
    key: 'b',
  },
  kilobit: {
    key: 'Kb',
  },
  megabit: {
    key: 'Mb',
  },
  gigabit: {
    key: 'Gb',
  },
  terabit: {
    key: 'Tb',
  },
  byte: {
    key: 'B',
  },
  kilobyte: {
    key: 'KB',
  },
  megabyte: {
    key: 'MB',
  },
  gigabyte: {
    key: 'GB',
  },
  terabyte: {
    key: 'TB',
  },
  'part-per-million': {
    key: 'ppm',
  },
  'part-per-billion': {
    key: 'ppb',
  },
  'part-per-trillion': {
    key: 'ppt',
  },
  'part-per-quadrillion': {
    key: 'ppq',
  },
  'metre-per-second': {
    key: 'm/s',
  },
  'kilometre-per-hour': {
    key: 'km/h',
  },
  'mile-per-hour': {
    key: 'm/h',
  },
  knot: {
    key: 'knot',
  },
  'foot-per-second': {
    key: 'ft/s',
  },
  'minute-per-kilometre': {
    key: 'min/km',
  },
  'second-per-metre': {
    key: 's/m',
  },
  'minute-per-mile': {
    key: 'min/mi',
  },
  'second-per-foot': {
    key: 's/ft',
  },
  pascal: {
    key: 'Pa',
  },
  kilopascal: {
    key: 'kPa',
  },
  megapascal: {
    key: 'MPa',
  },
  hectopascal: {
    key: 'hPa',
  },
  bar: {
    key: 'bar',
  },
  torr: {
    key: 'torr',
  },
  'pound-per-square-inch': {
    key: 'psi',
  },
  'kilopound-per-square-inch': {
    key: 'ksi',
  },
  ampere: {
    key: 'A',
  },
  milliampere: {
    key: 'mA',
  },
  kiloampere: {
    key: 'kA',
  },
  volt: {
    key: 'V',
  },
  millivolt: {
    key: 'mV',
  },
  kilovolt: {
    key: 'kV',
  },
  watt: {
    key: 'W',
  },
  milliwatt: {
    key: 'mW',
  },
  kilowatt: {
    key: 'kW',
  },
  megawatt: {
    key: 'MW',
  },
  gigawatt: {
    key: 'GW',
  },
  'volt-ampere-reactive': {
    key: 'VAR',
  },
  'millivolt-ampere-reactive': {
    key: 'mVAR',
  },
  'kilovolt-ampere-reactive': {
    key: 'kVAR',
  },
  'megavolt-ampere-reactive': {
    key: 'MVAR',
  },
  'gigavolt-ampere-reactive': {
    key: 'GVAR',
  },
  'volt-ampere': {
    key: 'VA',
  },
  'millivolt-ampere': {
    key: 'mVA',
  },
  'kilovolt-ampere': {
    key: 'kVA',
  },
  'megavolt-ampere': {
    key: 'MVA',
  },
  'gigavolt-ampere': {
    key: 'GVA',
  },
  'watt-hour': {
    key: 'Wh',
  },
  'milliwatt-hour': {
    key: 'mWh',
  },
  'kilowatt-hour': {
    key: 'kWh',
  },
  'megawatt-hour': {
    key: 'MWh',
  },
  'gigawatt-hour': {
    key: 'GWh',
  },
  joule: {
    key: 'J',
  },
  kilojoule: {
    key: 'kJ',
  },
  'volt-ampere-reactive-hour': {
    key: 'VARh',
  },
  'millivolt-ampere-reactive-hour': {
    key: 'mVARh',
  },
  'kilovolt-ampere-reactive-hour': {
    key: 'kVARh',
  },
  'megavolt-ampere-reactive-hour': {
    key: 'MVARh',
  },
  'gigavolt-ampere-reactive-hour': {
    key: 'GVARh',
  },
  'cubic-millimeter-per-second': {
    key: 'mm3/s',
  },
  'cubic-centimeter-per-second': {
    key: 'cm3/s',
  },
  'millilitre-per-second': {
    key: 'ml/s',
  },
  'centilitre-per-second': {
    key: 'cl/s',
  },
  'decilitre-per-second': {
    key: 'dl/s',
  },
  'litre-per-second': {
    key: 'l/s',
  },
  'litre-per-minute': {
    key: 'l/min',
  },
  'litre-per-hour': {
    key: 'l/h',
  },
  'kilolitre-per-second': {
    key: 'kl/s',
  },
  'kilolitre-per-minute': {
    key: 'kl/min',
  },
  'kilolitre-per-hour': {
    key: 'kl/h',
  },
  'cubic-meter-per-second': {
    key: 'm3/s',
  },
  'cubic-meter-per-minute': {
    key: 'm3/min',
  },
  'cubic-meter-per-hour': {
    key: 'm3/h',
  },
  'cubic-kilometer-per-second': {
    key: 'km3/s',
  },
  'teaspoon-per-second': {
    key: 'tsp/s',
  },
  'tablespoon-per-second': {
    key: 'Tbs/s',
  },
  'cubic-inch-per-second': {
    key: 'in3/s',
  },
  'cubic-inch-per-minute': {
    key: 'in3/min',
  },
  'cubic-inch-per-hour': {
    key: 'in3/h',
  },
  'fluid-ounce-per-second': {
    key: 'fl-oz/s',
  },
  'fluid-ounce-per-minute': {
    key: 'fl-oz/min',
  },
  'fluid-ounce-per-hour': {
    key: 'fl-oz/h',
  },
  'cup-per-second': {
    key: 'cup/s',
  },
  'pint-per-second': {
    key: 'pnt/s',
  },
  'pint-per-minute': {
    key: 'pnt/min',
  },
  'pint-per-hour': {
    key: 'pnt/h',
  },
  'quart-per-second': {
    key: 'qt/s',
  },
  'gallon-per-second': {
    key: 'gal/s',
  },
  'gallon-per-minute': {
    key: 'gal/min',
  },
  'gallon-per-hour': {
    key: 'gal/h',
  },
  'cubic-foot-per-second': {
    key: 'ft3/s',
  },
  'cubic-foot-per-minute': {
    key: 'ft3/min',
  },
  'cubic-foot-per-hour': {
    key: 'ft3/h',
  },
  'cubic-yard-per-second': {
    key: 'yd3/s',
  },
  'cubic-yard-per-minute': {
    key: 'yd3/min',
  },
  'cubic-yard-per-hour': {
    key: 'yd3/h',
  },
  lux: {
    key: 'lx',
  },
  'foot-candle': {
    key: 'ft-cd',
  },
  millihertz: {
    key: 'mHz',
  },
  hertz: {
    key: 'Hz',
  },
  kilohertz: {
    key: 'kHz',
  },
  megahertz: {
    key: 'MHz',
  },
  gigahertz: {
    key: 'GHz',
  },
  terahertz: {
    key: 'THz',
  },
  'rotation-per-minute': {
    key: 'rpm',
  },
  'degree-per-second': {
    key: 'deg/s',
  },
  'radian-per-second': {
    key: 'rad/s',
  },
  radian: {
    key: 'rad',
  },
  degree: {
    key: 'deg',
  },
  gradian: {
    key: 'grad',
  },
  arcminute: {
    key: 'arcmin',
  },
  arcsecond: {
    key: 'arcsec',
  },
}
