// AUTO-GENERATED by pnpm make:type. Do not edit.

import type {
  CompileCNodeInput,
  CompileCNodeOutput,
} from '~/code/form/action/compile/code/c/node'
import type {
  CompileCppNodeInput,
  CompileCppNodeOutput,
} from '~/code/form/action/compile/code/cpp/node'
import type {
  CompileRustNodeInput,
  CompileRustNodeOutput,
} from '~/code/form/action/compile/code/rust/node'
import type {
  CompileSwiftNodeInput,
  CompileSwiftNodeOutput,
} from '~/code/form/action/compile/code/swift/node'
import type {
  CompileWastNodeInput,
  CompileWastNodeOutput,
} from '~/code/form/action/compile/code/wast/node'
import type {
  ConvertArchiveNodeInput,
  ConvertArchiveNodeOutput,
} from '~/code/form/action/convert/archive/node'
import type {
  ConvertDataNodeInput,
  ConvertDataNodeOutput,
} from '~/code/form/action/convert/data/node'
import type {
  ConvertDocumentWithCalibreNodeInput,
  ConvertDocumentWithCalibreNodeOutput,
} from '~/code/form/action/convert/calibre/node'
import type {
  ConvertDocumentWithEnscriptNodeInput,
  ConvertDocumentWithEnscriptNodeOutput,
} from '~/code/form/action/convert/enscript/node'
import type {
  ConvertDocumentWithJupyterNodeInput,
  ConvertDocumentWithJupyterNodeOutput,
} from '~/code/form/action/convert/jupyter/node'
import type {
  ConvertDocumentWithLibreOfficeNodeInput,
  ConvertDocumentWithLibreOfficeNodeOutput,
} from '~/code/form/action/convert/libre-office/node'
import type {
  ConvertDocumentWithPandocNodeInput,
  ConvertDocumentWithPandocNodeOutput,
} from '~/code/form/action/convert/pandoc/node'
import type {
  ConvertFontWithFontForgeNodeInput,
  ConvertFontWithFontForgeNodeOutput,
} from '~/code/form/action/convert/font-forge/node'
import type {
  ConvertHtmlWithPuppeteerNodeInput,
  ConvertHtmlWithPuppeteerNodeOutput,
  ConvertMarkdownWithPuppeteerNodeInput,
  ConvertMarkdownWithPuppeteerNodeOutput,
  ConvertTxtWithPuppeteerNodeInput,
  ConvertTxtWithPuppeteerNodeOutput,
} from '~/code/form/action/convert/puppeteer/node'
import type {
  ConvertImageWithImageMagickNodeInput,
  ConvertImageWithImageMagickNodeOutput,
} from '~/code/form/action/convert/imagemagick/node'
import type {
  ConvertImageWithInkscapeNodeInput,
  ConvertImageWithInkscapeNodeOutput,
} from '~/code/form/action/convert/inkscape/node'
import type {
  ConvertLatexToPngNodeInput,
  ConvertLatexToPngNodeOutput,
} from '~/code/form/action/convert/latex-to-png/node'
import type {
  ConvertLatexWithPdfLatexNodeInput,
  ConvertLatexWithPdfLatexNodeOutput,
} from '~/code/form/action/convert/pdf-latex/node'
import type {
  ConvertParquetNodeInput,
  ConvertParquetNodeOutput,
} from '~/code/form/action/convert/parquet/node'
import type {
  ConvertVideoWithFfmpegNodeInput,
  ConvertVideoWithFfmpegNodeOutput,
} from '~/code/form/action/convert/ffmpeg/node'
import type {
  DownloadHuggingFaceNodeInput,
  DownloadHuggingFaceNodeOutput,
} from '~/code/form/action/download/hugging-face/node'
import type {
  FormatAssemblyNodeInput,
  FormatAssemblyNodeOutput,
  FormatCodeWithClangFormatNodeInput,
  FormatCodeWithClangFormatNodeOutput,
  FormatKotlinNodeInput,
  FormatKotlinNodeOutput,
  FormatPythonNodeInput,
  FormatPythonNodeOutput,
  FormatRustNodeInput,
  FormatRustNodeOutput,
  FormatSwiftNodeInput,
  FormatSwiftNodeOutput,
} from '~/code/form/action/format/code/node'
import type {
  SanitizeHtmlNodeInput,
  SanitizeHtmlNodeOutput,
} from '~/code/form/action/sanitize/code/node'

export interface Task {
  compile(input: CompileCNodeInput): Promise<CompileCNodeOutput>
  compile(input: CompileCppNodeInput): Promise<CompileCppNodeOutput>
  compile(input: CompileRustNodeInput): Promise<CompileRustNodeOutput>
  compile(input: CompileSwiftNodeInput): Promise<CompileSwiftNodeOutput>
  compile(input: CompileWastNodeInput): Promise<CompileWastNodeOutput>

  convert(input: ConvertArchiveNodeInput): Promise<ConvertArchiveNodeOutput>
  convert(input: ConvertDataNodeInput): Promise<ConvertDataNodeOutput>
  convert(input: ConvertDocumentWithCalibreNodeInput): Promise<ConvertDocumentWithCalibreNodeOutput>
  convert(input: ConvertDocumentWithEnscriptNodeInput): Promise<ConvertDocumentWithEnscriptNodeOutput>
  convert(input: ConvertDocumentWithJupyterNodeInput): Promise<ConvertDocumentWithJupyterNodeOutput>
  convert(input: ConvertDocumentWithLibreOfficeNodeInput): Promise<ConvertDocumentWithLibreOfficeNodeOutput>
  convert(input: ConvertDocumentWithPandocNodeInput): Promise<ConvertDocumentWithPandocNodeOutput>
  convert(input: ConvertFontWithFontForgeNodeInput): Promise<ConvertFontWithFontForgeNodeOutput>
  convert(input: ConvertHtmlWithPuppeteerNodeInput): Promise<ConvertHtmlWithPuppeteerNodeOutput>
  convert(input: ConvertImageWithImageMagickNodeInput): Promise<ConvertImageWithImageMagickNodeOutput>
  convert(input: ConvertImageWithInkscapeNodeInput): Promise<ConvertImageWithInkscapeNodeOutput>
  convert(input: ConvertLatexToPngNodeInput): Promise<ConvertLatexToPngNodeOutput>
  convert(input: ConvertLatexWithPdfLatexNodeInput): Promise<ConvertLatexWithPdfLatexNodeOutput>
  convert(input: ConvertMarkdownWithPuppeteerNodeInput): Promise<ConvertMarkdownWithPuppeteerNodeOutput>
  convert(input: ConvertParquetNodeInput): Promise<ConvertParquetNodeOutput>
  convert(input: ConvertTxtWithPuppeteerNodeInput): Promise<ConvertTxtWithPuppeteerNodeOutput>
  convert(input: ConvertVideoWithFfmpegNodeInput): Promise<ConvertVideoWithFfmpegNodeOutput>

  download(input: DownloadHuggingFaceNodeInput): Promise<DownloadHuggingFaceNodeOutput>

  format(input: FormatAssemblyNodeInput): Promise<FormatAssemblyNodeOutput>
  format(input: FormatCodeWithClangFormatNodeInput): Promise<FormatCodeWithClangFormatNodeOutput>
  format(input: FormatKotlinNodeInput): Promise<FormatKotlinNodeOutput>
  format(input: FormatPythonNodeInput): Promise<FormatPythonNodeOutput>
  format(input: FormatRustNodeInput): Promise<FormatRustNodeOutput>
  format(input: FormatSwiftNodeInput): Promise<FormatSwiftNodeOutput>

  sanitize(input: SanitizeHtmlNodeInput): Promise<SanitizeHtmlNodeOutput>
}
